// Web-Admin-Vue/src/App.vue
<!-- SPDX-License-Identifier: Apache-2.0 -->
<template>
  <el-config-provider>
    <router-view />
    <GlobalSnackbar />
    <PresetGuideDialog />
  </el-config-provider>
</template>

<script setup lang="ts">
import { watch } from 'vue'
import GlobalSnackbar from '@/components/GlobalSnackbar.vue'
import PresetGuideDialog from '@/components/PresetGuideDialog.vue'
import { useUiStore } from '@/stores/ui'
import { applyTheme } from '@/utils/theme'

const ui = useUiStore()
// 集中应用主题（首个 paint 前），并修复登录页从不应用暗色/主题变体的问题
watch(
  () => [ui.theme, ui.variant] as const,
  ([mode, variant]) => applyTheme(mode, variant),
  { immediate: true },
)
</script>

// Web-Admin-React/src/App.tsx
// SPDX-License-Identifier: Apache-2.0

import { CssBaseline, ThemeProvider } from '@mui/material'
import { RouterProvider } from 'react-router-dom'
import { useUiStore } from '@/stores/ui'
import { lightTheme, darkTheme } from '@/theme'
import { router } from '@/router'
import { GlobalSnackbar } from '@/components/GlobalSnackbar'

export default function App() {
  const theme = useUiStore((s) => s.theme)
  return (
    <ThemeProvider theme={theme === 'dark' ? darkTheme : lightTheme}>
      <CssBaseline />
      <RouterProvider router={router} />
      <GlobalSnackbar />
    </ThemeProvider>
  )
}
