// Front-Taro/src/pages/splash/index.tsx
 import { useEffect } from 'react'
 import { View, Text, Image } from '@tarojs/components'
 import Taro from '@tarojs/taro'
 import { useAuthStore } from '../../stores/auth-store'
 import './index.scss'
 
 export default function SplashPage() {
   const status = useAuthStore((s) => s.status)
 
   useEffect(() => {
     const timer = setTimeout(() => {
       if (status === 'authenticated') {
         Taro.switchTab({ url: '/pages/dashboard/index' })
       } else {
         Taro.redirectTo({ url: '/pages/login/index' })
       }
     }, 800)
 
     return () => clearTimeout(timer)
   }, [status])
 
   return (
     <View className='splash'>
       <View className='splash__content'>
         <View className='splash__icon'>
           <Text className='splash__icon-text'>A</Text>
         </View>
         <Text className='splash__title'>App</Text>
         <View className='splash__loader' />
       </View>
     </View>
   )
 }

// Front-Taro/src/pages/splash/index.vue
<template>
  <view class="splash">
    <view class="splash__content">
      <view class="splash__icon">
        <text class="splash__icon-text">A</text>
      </view>
      <text class="splash__title">App</text>
      <view class="splash__loader" />
    </view>
  </view>
</template>

<script setup lang="ts">
import { watch, onUnmounted } from 'vue'
import Taro from '@tarojs/taro'
import { storeToRefs } from 'pinia'
import { useAuthStore } from '../../stores/auth-store'

const store = useAuthStore()
const { status } = storeToRefs(store)

let timer: ReturnType<typeof setTimeout> | null = null

// 对应原 React useEffect(..., [status])：登录状态变化后延迟跳转，跳转前重置计时器
function scheduleNavigation() {
  if (timer) clearTimeout(timer)
  timer = setTimeout(() => {
    if (status.value === 'authenticated') {
      Taro.redirectTo({ url: '/pages/dashboard/index' })
    } else {
      Taro.redirectTo({ url: '/pages/login/index' })
    }
  }, 800)
}

watch(status, scheduleNavigation, { immediate: true })

onUnmounted(() => {
  if (timer) clearTimeout(timer)
})
</script>

<style src="./index.scss" scoped></style>
