// Front-Taro/src/pages/register/index.tsx
 import { useState } from 'react'
 import { View, Text, Input, Button } from '@tarojs/components'
 import Taro from '@tarojs/taro'
 import { useAuthStore } from '../../stores/auth-store'
 import { validateUsername, validatePassword, validateNickname } from '../../utils/validators'
 import './index.scss'
 
 export default function RegisterPage() {
   const [username, setUsername] = useState('')
   const [password, setPassword] = useState('')
   const [nickname, setNickname] = useState('')
   const [showPassword, setShowPassword] = useState(false)
   const [errors, setErrors] = useState<Record<string, string>>({})
 
   const { register, status, errorMessage } = useAuthStore()
   const isLoading = status === 'loading'
 
   const handleSubmit = async () => {
     const usernameErr = validateUsername(username)
     const passwordErr = validatePassword(password)
     const nicknameErr = validateNickname(nickname)
     setErrors({
       username: usernameErr || '',
       password: passwordErr || '',
       nickname: nicknameErr || '',
     })
 
     if (usernameErr || passwordErr || nicknameErr) return
 
     const success = await register(username.trim(), password, nickname.trim())
     if (success) {
       Taro.switchTab({ url: '/pages/dashboard/index' })
     }
   }
 
   return (
     <View className='register'>
       <View className='register__content'>
         <View className='register__header'>
           <View className='register__icon'>
             <Text className='register__icon-text'>A</Text>
           </View>
           <Text className='register__title'>Create Account</Text>
           <Text className='register__subtitle'>Join App today</Text>
         </View>
 
         {errorMessage && (
           <View className='register__error'>
             <Text className='register__error-text'>{errorMessage}</Text>
           </View>
         )}
 
         <View className='register__form'>
           <View className='form-group'>
             <Text className='form-label'>Username</Text>
             <Input
               className={`form-input ${errors.username ? 'form-input--error' : ''}`}
               placeholder='Choose a username'
               value={username}
               onInput={(e) => setUsername(e.detail.value)}
             />
             {errors.username && <Text className='form-error'>{errors.username}</Text>}
           </View>
 
           <View className='form-group'>
             <Text className='form-label'>Nickname</Text>
             <Input
               className={`form-input ${errors.nickname ? 'form-input--error' : ''}`}
               placeholder='Your display name'
               value={nickname}
               onInput={(e) => setNickname(e.detail.value)}
             />
             {errors.nickname && <Text className='form-error'>{errors.nickname}</Text>}
           </View>
 
           <View className='form-group'>
             <Text className='form-label'>Password</Text>
             <View className='password-input'>
               <Input
                 className={`form-input ${errors.password ? 'form-input--error' : ''}`}
                 placeholder='At least 8 characters'
                 password={!showPassword}
                 value={password}
                 onInput={(e) => setPassword(e.detail.value)}
               />
               <Text className='password-toggle' onClick={() => setShowPassword(!showPassword)}>
                 {showPassword ? 'Hide' : 'Show'}
               </Text>
             </View>
             {errors.password && <Text className='form-error'>{errors.password}</Text>}
           </View>
 
           <Button
             className='register__button'
             loading={isLoading}
             disabled={isLoading}
             onClick={handleSubmit}
           >
             Create Account
           </Button>
 
           <View className='register__footer'>
             <Text className='register__footer-text'>Already have an account? </Text>
             <Text className='register__footer-link' onClick={() => Taro.navigateBack()}>
               Sign In
             </Text>
           </View>
         </View>
       </View>
     </View>
   )
 }

// Front-Taro/src/pages/register/index.vue
<template>
  <view class="register">
    <view class="register__content">
      <view class="register__header">
        <view class="register__icon">
          <text class="register__icon-text">A</text>
        </view>
        <text class="register__title">Create Account</text>
        <text class="register__subtitle">Join App today</text>
      </view>

      <view v-if="errorMessage" class="register__error">
        <text class="register__error-text">{{ errorMessage }}</text>
      </view>

      <view class="register__form">
        <view class="form-group">
          <text class="form-label">Username</text>
          <input
            class="form-input"
            :class="{ 'form-input--error': errors.username }"
            placeholder="Choose a username"
            v-model="username"
          />
          <text v-if="errors.username" class="form-error">{{ errors.username }}</text>
        </view>

        <view class="form-group">
          <text class="form-label">Nickname</text>
          <input
            class="form-input"
            :class="{ 'form-input--error': errors.nickname }"
            placeholder="Your display name"
            v-model="nickname"
          />
          <text v-if="errors.nickname" class="form-error">{{ errors.nickname }}</text>
        </view>

        <view class="form-group">
          <text class="form-label">Password</text>
          <view class="password-input">
            <input
              class="form-input"
              :class="{ 'form-input--error': errors.password }"
              placeholder="At least 8 characters"
              :password="!showPassword"
              v-model="password"
            />
            <text class="password-toggle" @click="showPassword = !showPassword">
              {{ showPassword ? 'Hide' : 'Show' }}
            </text>
          </view>
          <text v-if="errors.password" class="form-error">{{ errors.password }}</text>
        </view>

        <button
          class="register__button"
          :loading="isLoading"
          :disabled="isLoading"
          @click="handleSubmit"
        >
          Create Account
        </button>

        <view class="register__footer">
          <text class="register__footer-text">Already have an account? </text>
          <text class="register__footer-link" @click="goBack">Sign In</text>
        </view>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import './index.scss'
import { ref, computed } from 'vue'
import Taro from '@tarojs/taro'
import { storeToRefs } from 'pinia'
import { useAuthStore } from '../../stores/auth-store'
import { validateUsername, validatePassword, validateNickname } from '../../utils/validators'

const store = useAuthStore()
const { status, errorMessage } = storeToRefs(store)
const username = ref('')
const password = ref('')
const nickname = ref('')
const showPassword = ref(false)
const errors = ref<Record<string, string>>({})

const isLoading = computed(() => status.value === 'loading')

async function handleSubmit() {
  const usernameErr = validateUsername(username.value)
  const passwordErr = validatePassword(password.value)
  const nicknameErr = validateNickname(nickname.value)
  errors.value = {
    username: usernameErr || '',
    password: passwordErr || '',
    nickname: nicknameErr || '',
  }

  if (usernameErr || passwordErr || nicknameErr) return

  const success = await store.register(
    username.value.trim(),
    password.value,
    nickname.value.trim(),
  )
  if (success) {
    Taro.redirectTo({ url: '/pages/dashboard/index' })
  }
}

function goBack() {
  Taro.navigateBack()
}
</script>
