// Front-Taro/src/pages/login/index.tsx
 import { useState } from 'react'
 import { View, Text, Input, Button, Form } from '@tarojs/components'
 import Taro from '@tarojs/taro'
 import { useAuthStore } from '../../stores/auth-store'
 import { validateUsername, validateRequired } from '../../utils/validators'
 import './index.scss'
 
 export default function LoginPage() {
   const [username, setUsername] = useState('')
   const [password, setPassword] = useState('')
   const [showPassword, setShowPassword] = useState(false)
   const [errors, setErrors] = useState<{ username?: string; password?: string }>({})
 
   const { login, status, errorMessage } = useAuthStore()
   const isLoading = status === 'loading'
 
   const handleSubmit = async () => {
     const usernameErr = validateUsername(username)
     const passwordErr = validateRequired(password, 'Password')
     setErrors({ username: usernameErr || undefined, password: passwordErr || undefined })
 
     if (usernameErr || passwordErr) return
 
     const success = await login(username.trim(), password)
     if (success) {
       Taro.switchTab({ url: '/pages/dashboard/index' })
     }
   }
 
   return (
     <View className='login'>
       <View className='login__content'>
         <View className='login__header'>
           <View className='login__icon'>
             <Text className='login__icon-text'>A</Text>
           </View>
           <Text className='login__title'>App</Text>
           <Text className='login__subtitle'>Sign in to continue</Text>
         </View>
 
         {errorMessage && (
           <View className='login__error'>
             <Text className='login__error-text'>{errorMessage}</Text>
           </View>
         )}
 
         <View className='login__form'>
           <View className='form-group'>
             <Text className='form-label'>Username</Text>
             <Input
               className={`form-input ${errors.username ? 'form-input--error' : ''}`}
               placeholder='Enter your username'
               value={username}
               onInput={(e) => setUsername(e.detail.value)}
             />
             {errors.username && <Text className='form-error'>{errors.username}</Text>}
           </View>
 
           <View className='form-group'>
             <Text className='form-label'>Password</Text>
             <View className='password-input'>
               <Input
                 className={`form-input ${errors.password ? 'form-input--error' : ''}`}
                 placeholder='Enter your password'
                 password={!showPassword}
                 value={password}
                 onInput={(e) => setPassword(e.detail.value)}
               />
               <Text className='password-toggle' onClick={() => setShowPassword(!showPassword)}>
                 {showPassword ? 'Hide' : 'Show'}
               </Text>
             </View>
             {errors.password && <Text className='form-error'>{errors.password}</Text>}
           </View>
 
           <Button
             className='login__button'
             loading={isLoading}
             disabled={isLoading}
             onClick={handleSubmit}
           >
             Sign In
           </Button>
 
           <View className='login__footer'>
             <Text className='login__footer-text'>Don't have an account? </Text>
             <Text className='login__footer-link' onClick={() => Taro.navigateTo({ url: '/pages/register/index' })}>
               Register
             </Text>
           </View>
         </View>
       </View>
     </View>
   )
 }

// Front-Taro/src/pages/login/index.vue
<template>
  <view class="login">
    <view class="login__content">
      <view class="login__header">
        <view class="login__icon">
          <text class="login__icon-text">A</text>
        </view>
        <text class="login__title">App</text>
        <text class="login__subtitle">Sign in to continue</text>
      </view>

      <view v-if="errorMessage" class="login__error">
        <text class="login__error-text">{{ errorMessage }}</text>
      </view>

      <view class="login__form">
        <view class="form-group">
          <text class="form-label">Username</text>
          <input
            class="form-input"
            :class="{ 'form-input--error': errors.username }"
            placeholder="Enter your username"
            v-model="username"
          />
          <text v-if="errors.username" class="form-error">{{ errors.username }}</text>
        </view>

        <view class="form-group">
          <text class="form-label">Password</text>
          <view class="password-input">
            <input
              class="form-input"
              :class="{ 'form-input--error': errors.password }"
              placeholder="Enter your password"
              :password="!showPassword"
              v-model="password"
            />
            <text class="password-toggle" @click="showPassword = !showPassword">
              {{ showPassword ? 'Hide' : 'Show' }}
            </text>
          </view>
          <text v-if="errors.password" class="form-error">{{ errors.password }}</text>
        </view>

        <button
          class="login__button"
          :loading="isLoading"
          :disabled="isLoading"
          @click="handleSubmit"
        >
          Sign In
        </button>

        <view class="login__footer">
          <text class="login__footer-text">Don't have an account? </text>
          <text class="login__footer-link" @click="goRegister">Register</text>
        </view>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import Taro from '@tarojs/taro'
import { storeToRefs } from 'pinia'
import { useAuthStore } from '../../stores/auth-store'
import { validateUsername, validateRequired } from '../../utils/validators'

const store = useAuthStore()
const { status, errorMessage } = storeToRefs(store)
const username = ref('')
const password = ref('')
const showPassword = ref(false)
const errors = ref<{ username?: string; password?: string }>({})

const isLoading = computed(() => status.value === 'loading')

async function handleSubmit() {
  const usernameErr = validateUsername(username.value)
  const passwordErr = validateRequired(password.value, 'Password')
  errors.value = { username: usernameErr || undefined, password: passwordErr || undefined }

  if (usernameErr || passwordErr) return

  const success = await store.login(username.value.trim(), password.value)
  if (success) {
    Taro.redirectTo({ url: '/pages/dashboard/index' })
  }
}

function goRegister() {
  Taro.navigateTo({ url: '/pages/register/index' })
}
</script>

<style src="./index.scss" scoped></style>
