// Web-Admin/src/components/GlobalSnackbar.vue
<template>
  <div class="snackbar-stack">
    <v-snackbar
      v-for="item in snackbar.items"
      :key="item.id"
      :model-value="true"
      :color="colorFor(item.type)"
      location="bottom"
      timeout="-1"
    >
      {{ item.message }}
      <template #actions>
        <v-btn icon="mdi-close" variant="text" @click="snackbar.dismiss(item.id)" />
      </template>
    </v-snackbar>
  </div>
</template>

<script setup lang="ts">
import { useSnackbarStore } from '@/stores/snackbar'

const snackbar = useSnackbarStore()

function colorFor(type: string): string {
  return type === 'success' ? 'success' : type === 'error' ? 'error' : 'info'
}
</script>

<style scoped>
.snackbar-stack {
  position: fixed;
  bottom: 16px;
  left: 50%;
  transform: translateX(-50%);
  z-index: 4000;
  display: flex;
  flex-direction: column;
  gap: 8px;
}
</style>

// Web-Admin-React/src/components/GlobalSnackbar.tsx
import { Alert, Box, Snackbar } from '@mui/material'
import { useSnackbarStore } from '@/stores/snackbar'

export function GlobalSnackbar() {
  const items = useSnackbarStore((s) => s.items)
  const dismiss = useSnackbarStore((s) => s.dismiss)

  return (
    <Box
      sx={{
        position: 'fixed',
        bottom: 16,
        left: '50%',
        transform: 'translateX(-50%)',
        zIndex: 4000,
        display: 'flex',
        flexDirection: 'column',
        gap: 1,
      }}
    >
      {items.map((item) => (
        <Snackbar key={item.id} open autoHideDuration={null}>
          <Alert severity={item.type} variant="filled" onClose={() => dismiss(item.id)}>
            {item.message}
          </Alert>
        </Snackbar>
      ))}
    </Box>
  )
}
