// Web-Admin-Vue/src/components/LangToggle.vue
<!-- SPDX-License-Identifier: Apache-2.0 -->
<template>
  <el-button :title="t('toggleLang')" @click="locale.toggle()">
    {{ locale.locale === 'zh' ? 'EN' : '中文' }}
  </el-button>
</template>

<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { useLocaleStore } from '@/i18n'

const locale = useLocaleStore()
const { t } = useI18n()
</script>

// Web-Admin-React/src/components/LangToggle.tsx
// SPDX-License-Identifier: Apache-2.0

import { Button } from '@mui/material'
import { useTranslation } from 'react-i18next'
import { useLocaleStore } from '@/i18n/locale'

export function LangToggle() {
  const locale = useLocaleStore((s) => s.locale)
  const toggle = useLocaleStore((s) => s.toggle)
  const { t } = useTranslation()
  return (
    <Button variant="text" onClick={toggle} title={t('toggleLang')} sx={{ minWidth: 0, px: 1 }}>
      {locale === 'zh' ? 'EN' : '中文'}
    </Button>
  )
}
