// Web-Admin-Vue/src/components/ThemeToggle.vue
<!-- SPDX-License-Identifier: Apache-2.0 -->
<template>
  <el-button circle :title="t('toggleTheme')" @click="ui.toggleTheme()">
    <AppIcon :icon="ui.theme === 'light' ? 'mdi-weather-night' : 'mdi-white-balance-sunny'" />
  </el-button>
</template>

<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { useUiStore } from '@/stores/ui'

const ui = useUiStore()
const { t } = useI18n()
</script>

// Web-Admin-React/src/components/ThemeToggle.tsx
// SPDX-License-Identifier: Apache-2.0

import { IconButton } from '@mui/material'
import DarkModeOutlinedIcon from '@mui/icons-material/DarkModeOutlined'
import LightModeOutlinedIcon from '@mui/icons-material/LightModeOutlined'
import { useTranslation } from 'react-i18next'
import { useUiStore } from '@/stores/ui'

export function ThemeToggle() {
  const theme = useUiStore((s) => s.theme)
  const toggleTheme = useUiStore((s) => s.toggleTheme)
  const { t } = useTranslation()
  return (
    <IconButton onClick={toggleTheme} title={t('toggleTheme')} size="small">
      {theme === 'light' ? <DarkModeOutlinedIcon /> : <LightModeOutlinedIcon />}
    </IconButton>
  )
}
