// Web-Admin-React/src/views/login/LoginView.tsx
import { useState } from 'react'
import { Alert, Box, Button, Card, CardActions, CardContent, CardHeader, Divider, IconButton, InputAdornment, TextField, Typography } from '@mui/material'
import AccountCircleOutlinedIcon from '@mui/icons-material/AccountCircleOutlined'
import LockOutlinedIcon from '@mui/icons-material/LockOutlined'
import VisibilityOutlinedIcon from '@mui/icons-material/VisibilityOutlined'
import VisibilityOffOutlinedIcon from '@mui/icons-material/VisibilityOffOutlined'
import { useLocation, useNavigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { useAuthStore } from '@/stores/auth'
import { LangToggle } from '@/components/LangToggle'

export default function LoginView() {
  const { t } = useTranslation()
  const navigate = useNavigate()
  const location = useLocation()
  const status = useAuthStore((s) => s.status)
  const storeError = useAuthStore((s) => s.errorMessage)
  const login = useAuthStore((s) => s.login)

  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [showPwd, setShowPwd] = useState(false)
  const [errorMessage, setErrorMessage] = useState('')

  const loading = status === 'loading'
  const shownError = errorMessage || storeError

  async function onSubmit() {
    if (!username || !password) {
      setErrorMessage(t('loginFailed'))
      return
    }
    const ok = await login(username, password)
    if (ok) {
      const params = new URLSearchParams(location.search)
      const redirect = params.get('redirect')
      const user = useAuthStore.getState().user
      navigate(typeof redirect === 'string' && redirect ? redirect : user?.role === 'admin' ? '/' : '/workbench', {
        replace: true,
      })
    } else {
      setErrorMessage(useAuthStore.getState().errorMessage || t('loginFailed'))
    }
  }

  return (
    <Box
      sx={{
        minHeight: '100vh',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        background: 'linear-gradient(135deg, #2f6bf5 0%, #f4f5fa 100%)',
      }}
    >
      <Card sx={{ width: 420, maxWidth: '92vw', borderRadius: 3, p: 1 }}>
        <CardHeader
          title={
            <Box sx={{ textAlign: 'center' }}>
              <Typography color="primary" fontSize={40} lineHeight={1} mb={1}>
                K
              </Typography>
              <Typography variant="h5" fontWeight="bold">
                {t('appName')}
              </Typography>
            </Box>
          }
          sx={{ pt: 3, pb: 0 }}
        />
        <CardContent sx={{ px: 4, py: 3 }}>
          <Typography variant="subtitle2" mb={2} textAlign="center">
            {t('loginTitle')}
          </Typography>

          {shownError ? (
            <Alert severity="error" variant="outlined" sx={{ mb: 2 }}>
              {shownError}
            </Alert>
          ) : null}

          <form
            onSubmit={(e) => {
              e.preventDefault()
              void onSubmit()
            }}
          >
            <TextField
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              label={t('username')}
              placeholder={t('usernamePlaceholder')}
              fullWidth
              margin="dense"
              autoComplete="username"
              slotProps={{
                input: {
                  startAdornment: (
                    <InputAdornment position="start">
                      <AccountCircleOutlinedIcon fontSize="small" />
                    </InputAdornment>
                  ),
                },
              }}
            />
            <TextField
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              label={t('password')}
              placeholder={t('passwordPlaceholder')}
              fullWidth
              margin="dense"
              type={showPwd ? 'text' : 'password'}
              autoComplete="current-password"
              slotProps={{
                input: {
                  startAdornment: (
                    <InputAdornment position="start">
                      <LockOutlinedIcon fontSize="small" />
                    </InputAdornment>
                  ),
                  endAdornment: (
                    <IconButton size="small" onClick={() => setShowPwd((v) => !v)}>
                      {showPwd ? <VisibilityOffOutlinedIcon /> : <VisibilityOutlinedIcon />}
                    </IconButton>
                  ),
                },
              }}
            />
            <Button type="submit" color="primary" variant="contained" fullWidth size="large" sx={{ mt: 2 }} loading={loading} disabled={loading}>
              {t('login')}
            </Button>
          </form>

          <Typography variant="caption" color="text.secondary" mt={2} textAlign="center" display="block">
            admin / Admin@1234（控制台）· alex / 123456（工作台）
          </Typography>
        </CardContent>
        <Divider />
        <CardActions sx={{ justifyContent: 'center', pb: 2, pt: 1 }}>
          <LangToggle />
        </CardActions>
      </Card>
    </Box>
  )
}

// Web-Admin-Vue/src/views/login/LoginView.vue
<template>
  <div class="login-bg d-flex align-center justify-center">
    <el-card class="login-card" shadow="always">
      <div class="text-center pt-4">
        <AppIcon icon="mdi-keel" size="40" color="var(--el-color-primary)" class="mb-1" />
        <div class="text-h5 font-weight-bold">{{ t('appName') }}</div>
      </div>
      <div class="px-6 py-4">
        <div class="text-subtitle-2 mb-4 text-center">{{ t('loginTitle') }}</div>

        <el-alert v-if="errorMessage" type="error" :closable="false" class="mb-4">
          {{ errorMessage }}
        </el-alert>

        <el-form @submit.prevent="onSubmit">
          <el-input
            v-model="username"
            :placeholder="t('usernamePlaceholder')"
            autocomplete="username"
            class="mb-3"
          >
            <template #prefix><AppIcon icon="mdi-account-outline" /></template>
          </el-input>
          <el-input
            v-model="password"
            :placeholder="t('passwordPlaceholder')"
            :type="showPwd ? 'text' : 'password'"
            autocomplete="current-password"
            @keyup.enter="onSubmit"
          >
            <template #prefix><AppIcon icon="mdi-lock-outline" /></template>
            <template #suffix>
              <el-button link @click="showPwd = !showPwd">
                <AppIcon :icon="showPwd ? 'mdi-eye-off' : 'mdi-eye'" />
              </el-button>
            </template>
          </el-input>
          <el-button
            type="primary"
            native-type="submit"
            size="large"
            class="mt-3 w-100"
            :loading="auth.status === 'loading'"
          >
            {{ t('login') }}
          </el-button>
        </el-form>

        <div class="text-caption text-medium-emphasis mt-4 text-center">
          admin / Admin@1234（控制台）· alex / 123456（工作台）
        </div>
      </div>
      <div class="text-center pb-4">
        <LangToggle />
      </div>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { useAuthStore } from '@/stores/auth'
import LangToggle from '@/components/LangToggle.vue'

const auth = useAuthStore()
const router = useRouter()
const route = useRoute()
const { t } = useI18n()

const username = ref('')
const password = ref('')
const showPwd = ref(false)
const errorMessage = ref('')

async function onSubmit() {
  if (!username.value || !password.value) {
    errorMessage.value = t('loginFailed')
    return
  }
  const ok = await auth.login(username.value, password.value)
  if (ok) {
    const redirect = route.query.redirect
    router.replace(typeof redirect === 'string' ? redirect : auth.isAdmin ? '/' : '/workbench')
  } else {
    errorMessage.value = auth.errorMessage || t('loginFailed')
  }
}
</script>

<style scoped>
.login-bg {
  min-height: 100vh;
  background: linear-gradient(135deg, var(--el-color-primary) 0%, var(--el-bg-color-page) 100%);
}
.login-card {
  width: 420px;
  max-width: 92vw;
  border-radius: 12px;
}
</style>
