// Front-Taro/src/pages/event-form/index.vue
<template>
  <view class="event-form">
    <view class="event-form__content">
      <view class="form-group">
        <text class="form-label">Title *</text>
        <input
          class="form-input"
          :class="{ 'form-input--error': errors.title }"
          placeholder="Event title"
          v-model="title"
        />
        <text v-if="errors.title" class="form-error">{{ errors.title }}</text>
      </view>

      <view class="form-group">
        <text class="form-label">Description</text>
        <input
          class="form-input form-input--multiline"
          placeholder="Event description (optional)"
          v-model="description"
        />
      </view>

      <view class="form-group">
        <text class="form-label">Location</text>
        <input
          class="form-input"
          placeholder="Event location (optional)"
          v-model="location"
        />
      </view>

      <!-- Start date/time -->
      <text class="form-section-title">Start</text>
      <view class="event-form__datetime">
        <picker mode="date" :value="startDate" @change="startDate = $event.detail.value">
          <view class="event-form__picker">
            <text class="event-form__picker-icon">📅</text>
            <text>{{ startDate }}</text>
          </view>
        </picker>
        <picker mode="time" :value="startTime" @change="startTime = $event.detail.value">
          <view class="event-form__picker">
            <text class="event-form__picker-icon">⏰</text>
            <text>{{ startTime }}</text>
          </view>
        </picker>
      </view>

      <!-- End date/time -->
      <text class="form-section-title">End</text>
      <view class="event-form__datetime">
        <picker mode="date" :value="endDate" @change="endDate = $event.detail.value">
          <view class="event-form__picker">
            <text class="event-form__picker-icon">📅</text>
            <text>{{ endDate }}</text>
          </view>
        </picker>
        <picker mode="time" :value="endTime" @change="endTime = $event.detail.value">
          <view class="event-form__picker">
            <text class="event-form__picker-icon">⏰</text>
            <text>{{ endTime }}</text>
          </view>
        </picker>
      </view>

      <!-- Color picker -->
      <view class="form-group">
        <text class="form-label">Color</text>
        <view class="event-form__colors">
          <view
            v-for="(color, i) in EVENT_COLORS"
            :key="i"
            class="event-form__color"
            :class="{ 'event-form__color--selected': colorRole === i }"
            :style="{ backgroundColor: color }"
            @click="colorRole = i"
          />
        </view>
      </view>

      <button
        class="event-form__submit"
        :loading="store.isLoading"
        :disabled="store.isLoading"
        @click="handleSubmit"
      >
        {{ isEditing ? 'Update Event' : 'Create Event' }}
      </button>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import Taro from '@tarojs/taro'
import { useEventsStore } from '../../stores/events-store'
import { EVENT_COLORS } from '../../utils/constants'
import { validateTitle } from '../../utils/validators'

const store = useEventsStore()

const router = Taro.getCurrentInstance().router
const eventId = router?.params?.id ? Number(router.params.id) : undefined
const isEditing = eventId != null

const title = ref('')
const description = ref('')
const location = ref('')

const now = new Date()
const startDate = ref(
  `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`,
)
const startTime = ref(`${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`)

const baseEnd = new Date()
baseEnd.setHours(baseEnd.getHours() + 1)
const endDate = ref(
  `${baseEnd.getFullYear()}-${String(baseEnd.getMonth() + 1).padStart(2, '0')}-${String(baseEnd.getDate()).padStart(2, '0')}`,
)
const endTime = ref(`${String(baseEnd.getHours()).padStart(2, '0')}:${String(baseEnd.getMinutes()).padStart(2, '0')}`)

const colorRole = ref(0)
const errors = ref<Record<string, string>>({})

async function handleSubmit() {
  const titleErr = validateTitle(title.value)
  errors.value = { title: titleErr || '' }
  if (titleErr) return

  const start = new Date(`${startDate.value}T${startTime.value}`)
  const end = new Date(`${endDate.value}T${endTime.value}`)

  if (end <= start) {
    Taro.showToast({ title: 'End time must be after start', icon: 'none' })
    return
  }

  const success = await store.createEvent({
    title: title.value.trim(),
    description: description.value.trim() || undefined,
    startTime: start.toISOString(),
    endTime: end.toISOString(),
    location: location.value.trim() || undefined,
    colorRole: colorRole.value,
  })

  if (success) {
    Taro.showToast({ title: 'Event created', icon: 'success' })
    setTimeout(() => Taro.navigateBack(), 1500)
  }
}
</script>

<style src="./index.scss" scoped></style>

// Front-Taro/src/pages/event-form/index.tsx
 import { useState } from 'react'
 import { View, Text, Input, Button, Picker } from '@tarojs/components'
 import Taro from '@tarojs/taro'
 import { useEventsStore } from '../../stores/events-store'
 import { EVENT_COLORS, EVENT_COLOR_NAMES } from '../../utils/constants'
 import { validateTitle } from '../../utils/validators'
 import './index.scss'
 
 export default function EventFormPage() {
   const router = Taro.getCurrentInstance().router
   const eventId = router?.params?.id ? Number(router.params.id) : undefined
   const isEditing = eventId != null
 
   const [title, setTitle] = useState('')
   const [description, setDescription] = useState('')
   const [location, setLocation] = useState('')
   const [startDate, setStartDate] = useState(() => {
     const now = new Date()
     return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`
   })
   const [startTime, setStartTime] = useState(() => {
     const now = new Date()
     return `${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`
   })
   const [endDate, setEndDate] = useState(() => {
     const now = new Date()
     now.setHours(now.getHours() + 1)
     return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`
   })
   const [endTime, setEndTime] = useState(() => {
     const now = new Date()
     now.setHours(now.getHours() + 1)
     return `${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`
   })
   const [colorRole, setColorRole] = useState(0)
   const [errors, setErrors] = useState<Record<string, string>>({})
 
   const { createEvent, isLoading } = useEventsStore()
 
   const handleSubmit = async () => {
     const titleErr = validateTitle(title)
     setErrors({ title: titleErr || '' })
     if (titleErr) return
 
     const start = new Date(`${startDate}T${startTime}`)
     const end = new Date(`${endDate}T${endTime}`)
 
     if (end <= start) {
       Taro.showToast({ title: 'End time must be after start', icon: 'none' })
       return
     }
 
     const success = await createEvent({
       title: title.trim(),
       description: description.trim() || undefined,
       startTime: start.toISOString(),
       endTime: end.toISOString(),
       location: location.trim() || undefined,
       colorRole,
     })
 
     if (success) {
       Taro.showToast({ title: 'Event created', icon: 'success' })
       setTimeout(() => Taro.navigateBack(), 1500)
     }
   }
 
   return (
     <View className='event-form'>
       <View className='event-form__content'>
       <View className='form-group'>
           <Text className='form-label'>Title *</Text>
           <Input
             className={`form-input ${errors.title ? 'form-input--error' : ''}`}
             placeholder='Event title'
             value={title}
             onInput={(e) => setTitle(e.detail.value)}
           />
           {errors.title && <Text className='form-error'>{errors.title}</Text>}
         </View>
 
         <View className='form-group'>
           <Text className='form-label'>Description</Text>
           <Input
             className='form-input form-input--multiline'
             placeholder='Event description (optional)'
             value={description}
             onInput={(e) => setDescription(e.detail.value)}
           />
         </View>
 
         <View className='form-group'>
           <Text className='form-label'>Location</Text>
           <Input
             className='form-input'
             placeholder='Event location (optional)'
             value={location}
             onInput={(e) => setLocation(e.detail.value)}
           />
         </View>
 
         {/* Start date/time */}
         <Text className='form-section-title'>Start</Text>
         <View className='event-form__datetime'>
           <Picker mode='date' value={startDate} onChange={(e) => setStartDate(e.detail.value)}>
             <View className='event-form__picker'>
               <Text className='event-form__picker-icon'>📅</Text>
               <Text>{startDate}</Text>
             </View>
           </Picker>
           <Picker mode='time' value={startTime} onChange={(e) => setStartTime(e.detail.value)}>
             <View className='event-form__picker'>
               <Text className='event-form__picker-icon'>⏰</Text>
               <Text>{startTime}</Text>
             </View>
           </Picker>
         </View>
 
         {/* End date/time */}
         <Text className='form-section-title'>End</Text>
         <View className='event-form__datetime'>
           <Picker mode='date' value={endDate} onChange={(e) => setEndDate(e.detail.value)}>
             <View className='event-form__picker'>
               <Text className='event-form__picker-icon'>📅</Text>
               <Text>{endDate}</Text>
             </View>
           </Picker>
           <Picker mode='time' value={endTime} onChange={(e) => setEndTime(e.detail.value)}>
             <View className='event-form__picker'>
               <Text className='event-form__picker-icon'>⏰</Text>
               <Text>{endTime}</Text>
             </View>
           </Picker>
         </View>
 
         {/* Color picker */}
         <View className='form-group'>
           <Text className='form-label'>Color</Text>
           <View className='event-form__colors'>
             {EVENT_COLORS.map((color, i) => (
               <View
                 key={i}
                 className={`event-form__color ${colorRole === i ? 'event-form__color--selected' : ''}`}
                 style={{ backgroundColor: color }}
                 onClick={() => setColorRole(i)}
               />
             ))}
           </View>
         </View>
 
         <Button
           className='event-form__submit'
           loading={isLoading}
           disabled={isLoading}
           onClick={handleSubmit}
         >
           {isEditing ? 'Update Event' : 'Create Event'}
         </Button>
       </View>
     </View>
   )
 }
