// Web-Admin-React/src/views/events/EventsView.tsx
// SPDX-License-Identifier: Apache-2.0

import { useEffect, useState } from 'react'
import { Box, Button, IconButton, MenuItem, Select, TextField } from '@mui/material'
import DownloadIcon from '@mui/icons-material/Download'
import FilterAltIcon from '@mui/icons-material/FilterAlt'
import RefreshIcon from '@mui/icons-material/Refresh'
import DeleteOutlineIcon from '@mui/icons-material/DeleteOutline'
import { useTranslation } from 'react-i18next'
import { PageHeader } from '@/components/PageHeader'
import { AppTable, type AppColumn } from '@/components/AppTable'
import { AppPagination } from '@/components/AppPagination'
import { DebouncedSearch } from '@/components/DebouncedSearch'
import { RangeFilter } from '@/components/RangeFilter'
import { ConfirmDialog } from '@/components/ConfirmDialog'
import { StatusChip } from '@/components/StatusChip'
import { useSnackbarStore } from '@/stores/snackbar'
import { eventsApi, type EventFilter } from '@/api/events'
import { downloadCsv } from '@/utils/csv'
import { formatTime } from '@/utils/format'
import type { AdminEvent } from '@/types/event'

const LIMIT = 20

export default function EventsView() {
  const { t } = useTranslation()
  const snackbar = useSnackbarStore()

  const [events, setEvents] = useState<AdminEvent[]>([])
  const [total, setTotal] = useState(0)
  const [page, setPage] = useState(1)
  const [loading, setLoading] = useState(false)

  const [keyword, setKeyword] = useState('')
  const [userId, setUserId] = useState('')
  const [status, setStatus] = useState('all')
  const [range, setRange] = useState('all')
  const [since, setSince] = useState<string | undefined>(undefined)

  const [showDelete, setShowDelete] = useState(false)
  const [pendingDelete, setPendingDelete] = useState<AdminEvent | null>(null)

  function currentFilter(): EventFilter {
    return {
      keyword: keyword || undefined,
      userId: userId ? Number(userId) : undefined,
      isCancelled: status === 'all' ? undefined : status === 'cancelled',
      start: since,
    }
  }

  async function load(p = 1) {
    setLoading(true)
    try {
      const res = await eventsApi.adminAll(p, LIMIT, currentFilter())
      setEvents(res.items)
      setTotal(res.total)
      setPage(p)
    } catch (err) {
      snackbar.error(err instanceof Error ? err.message : t('loadFailed'))
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    void load(1)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  function onRange(key: string, s?: string) {
    setRange(key)
    setSince(s)
  }

  function reset() {
    setKeyword('')
    setUserId('')
    setStatus('all')
    setRange('all')
    setSince(undefined)
    void load(1)
  }

  function onExport() {
    downloadCsv(
      'events',
      [t('idCol'), t('eventTitle'), t('eventStart'), t('eventEnd'), t('eventUser'), t('eventStatus')],
      events.map((e) => [
        e.id,
        e.title,
        formatTime(e.startTime),
        formatTime(e.endTime),
        e.user?.username || e.userId || '',
        e.isCancelled ? t('cancelled') : t('active'),
      ]),
    )
    snackbar.success(t('exportDone'))
  }

  function confirmDelete(e: AdminEvent) {
    setPendingDelete(e)
    setShowDelete(true)
  }

  async function onDelete() {
    if (!pendingDelete) return
    try {
      await eventsApi.adminRemove(pendingDelete.id)
      snackbar.success(t('deleted'))
      void load(page)
    } catch (err) {
      snackbar.error(err instanceof Error ? err.message : t('deleteFailed'))
    } finally {
      setShowDelete(false)
    }
  }

  const statusLabelMap = { active: t('active'), cancelled: t('cancelled') }
  const headers: AppColumn<AdminEvent>[] = [
    { key: 'id', title: t('idCol'), width: 70 },
    { key: 'title', title: t('eventTitle') },
    { key: 'startTime', title: t('eventStart'), render: (e) => formatTime(e.startTime) },
    { key: 'endTime', title: t('eventEnd'), render: (e) => formatTime(e.endTime) },
    { key: 'user', title: t('eventUser'), render: (e) => e.user?.username || e.userId || '-' },
    {
      key: 'isCancelled',
      title: t('eventStatus'),
      render: (e) => <StatusChip status={e.isCancelled ? 'cancelled' : 'active'} labelMap={statusLabelMap} />,
    },
    {
      key: 'actions',
      title: t('actionCol'),
      render: (e) => (
        <IconButton size="small" color="error" onClick={() => confirmDelete(e)}>
          <DeleteOutlineIcon />
        </IconButton>
      ),
    },
  ]

  return (
    <Box>
      <PageHeader title={t('navEvents')} subtitle={t('eventTotal', { n: total })}>
        <Button variant="outlined" startIcon={<DownloadIcon />} onClick={onExport}>
          {t('export')}
        </Button>
      </PageHeader>

      <Box sx={{ display: 'flex', gap: 1.5, flexWrap: 'wrap', alignItems: 'center', mb: 2, p: 2, bgcolor: 'background.paper', border: 1, borderColor: 'divider', borderRadius: 2 }}>
        <DebouncedSearch value={keyword} placeholder={t('searchTitle')} onChange={setKeyword} onSearch={() => void load(1)} />
        <TextField
          value={userId}
          onChange={(e) => setUserId(e.target.value)}
          label={t('filterByUserId')}
          type="number"
          size="small"
          sx={{ maxWidth: 160 }}
        />
        <Select size="small" value={status} onChange={(e) => setStatus(e.target.value)} sx={{ maxWidth: 150, minWidth: 120 }}>
          <MenuItem value="all">{t('allStatus')}</MenuItem>
          <MenuItem value="active">{t('active')}</MenuItem>
          <MenuItem value="cancelled">{t('cancelled')}</MenuItem>
        </Select>
        <RangeFilter value={range} onChange={onRange} />
        <Button color="primary" variant="contained" startIcon={<FilterAltIcon />} onClick={() => void load(1)}>
          {t('filter')}
        </Button>
        <Button variant="outlined" startIcon={<RefreshIcon />} onClick={reset}>
          {t('reset')}
        </Button>
      </Box>

      <AppTable headers={headers} items={events} loading={loading} emptyText={t('noEvents')} />

      <AppPagination page={page} limit={LIMIT} total={total} loading={loading} onChange={(p) => void load(p)} />

      <ConfirmDialog
        open={showDelete}
        title={t('deleteEventTitle')}
        content={t('deleteEventContent', { title: pendingDelete?.title || '' })}
        onClose={() => setShowDelete(false)}
        onConfirm={() => void onDelete()}
      />
    </Box>
  )
}

// Web-Admin-Vue/src/views/events/EventsView.vue
<!-- SPDX-License-Identifier: Apache-2.0 -->
<template>
  <div>
    <PageHeader :title="t('navEvents')" :subtitle="t('eventTotal', { n: total })">
      <el-button @click="onExport">
        <template #icon><AppIcon icon="mdi-download" /></template>
        {{ t('export') }}
      </el-button>
    </PageHeader>

    <el-card shadow="never" class="mb-4">
      <div class="d-flex ga-3 flex-wrap align-center">
        <DebouncedSearch v-model="keyword" :placeholder="t('searchTitle')" style="max-width: 220px" @search="load(1)" />
        <el-input
          v-model.number="userId"
          :label="t('filterByUserId')"
          type="number"
          style="max-width: 160px"
        />
        <el-select v-model="status" :label="t('eventStatus')" style="max-width: 150px">
          <el-option v-for="o in statusOptions" :key="o.value" :label="o.label" :value="o.value" />
        </el-select>
        <RangeFilter v-model="range" @update:model-value="onRange" />
        <el-button type="primary" @click="load(1)">
          <template #icon><AppIcon icon="mdi-filter-variant" /></template>
          {{ t('filter') }}
        </el-button>
        <el-button @click="reset">
          <template #icon><AppIcon icon="mdi-refresh" /></template>
          {{ t('reset') }}
        </el-button>
      </div>
    </el-card>

    <AppTable :headers="headers" :items="events" :loading="loading" :total="total" :items-per-page="limit">
      <template #item.startTime="{ item }">{{ formatTime(item.startTime) }}</template>
      <template #item.endTime="{ item }">{{ formatTime(item.endTime) }}</template>
      <template #item.user="{ item }">{{ item.user?.username || item.userId || '-' }}</template>
      <template #item.isCancelled="{ item }">
        <StatusChip :status="item.isCancelled ? 'cancelled' : 'active'" :label-map="statusLabelMap" />
      </template>
      <template #item.actions="{ item }">
        <el-button text size="small" type="danger" @click="confirmDelete(item)">
          <AppIcon icon="mdi-delete-outline" />
        </el-button>
      </template>
    </AppTable>

    <AppPagination :page="page" :limit="limit" :total="total" :loading="loading" @update:page="load" />

    <ConfirmDialog
      v-model="showDelete"
      :title="t('deleteEventTitle')"
      :content="t('deleteEventContent', { title: pendingDelete?.title || '' })"
      @confirm="onDelete"
    />
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import PageHeader from '@/components/PageHeader.vue'
import AppTable from '@/components/AppTable.vue'
import AppPagination from '@/components/AppPagination.vue'
import DebouncedSearch from '@/components/DebouncedSearch.vue'
import RangeFilter from '@/components/RangeFilter.vue'
import ConfirmDialog from '@/components/ConfirmDialog.vue'
import StatusChip from '@/components/StatusChip.vue'
import { useSnackbarStore } from '@/stores/snackbar'
import { eventsApi, type EventFilter } from '@/api/events'
import { downloadCsv } from '@/utils/csv'
import { formatTime } from '@/utils/format'
import type { AdminEvent } from '@/types/event'

const { t } = useI18n()
const snackbar = useSnackbarStore()

const events = ref<AdminEvent[]>([])
const total = ref(0)
const page = ref(1)
const limit = 20
const loading = ref(false)

const keyword = ref('')
const userId = ref<number | undefined>(undefined)
const status = ref<string>('all')
const range = ref('all')
const since = ref<string | undefined>(undefined)

const statusOptions = [
  { label: t('allStatus'), value: 'all' },
  { label: t('active'), value: 'active' },
  { label: t('cancelled'), value: 'cancelled' },
]
const statusLabelMap = computed(() => ({ active: t('active'), cancelled: t('cancelled') }))

const headers = computed(() => [
  { key: 'id', title: t('idCol') },
  { key: 'title', title: t('eventTitle') },
  { key: 'startTime', title: t('eventStart') },
  { key: 'endTime', title: t('eventEnd') },
  { key: 'user', title: t('eventUser') },
  { key: 'isCancelled', title: t('eventStatus') },
  { key: 'actions', title: t('actionCol') },
])

function currentFilter(): EventFilter {
  return {
    keyword: keyword.value || undefined,
    userId: userId.value,
    isCancelled: status.value === 'all' ? undefined : status.value === 'cancelled',
    start: since.value,
  }
}

async function load(p = 1) {
  loading.value = true
  try {
    const res = await eventsApi.adminAll(p, limit, currentFilter())
    events.value = res.items
    total.value = res.total
    page.value = p
  } catch (err) {
    snackbar.error(err instanceof Error ? err.message : t('loadFailed'))
  } finally {
    loading.value = false
  }
}

function onRange(key: string, s?: string) {
  range.value = key
  since.value = s
}
function reset() {
  keyword.value = ''
  userId.value = undefined
  status.value = 'all'
  range.value = 'all'
  since.value = undefined
  load(1)
}

function onExport() {
  downloadCsv(
    'events',
    [t('idCol'), t('eventTitle'), t('eventStart'), t('eventEnd'), t('eventUser'), t('eventStatus')],
    events.value.map((e) => [
      e.id,
      e.title,
      formatTime(e.startTime),
      formatTime(e.endTime),
      e.user?.username || e.userId || '',
      e.isCancelled ? t('cancelled') : t('active'),
    ]),
  )
  snackbar.success(t('exportDone'))
}

// 删除
const showDelete = ref(false)
const pendingDelete = ref<AdminEvent | null>(null)
function confirmDelete(e: AdminEvent) {
  pendingDelete.value = e
  showDelete.value = true
}
async function onDelete() {
  if (!pendingDelete.value) return
  try {
    await eventsApi.adminRemove(pendingDelete.value.id)
    snackbar.success(t('deleted'))
    load(page.value)
  } catch (err) {
    snackbar.error(err instanceof Error ? err.message : t('deleteFailed'))
  } finally {
    showDelete.value = false
  }
}

onMounted(() => load(1))
</script>
