// Web-Admin-React/src/views/knowledge/KnowledgeView.tsx
import { useEffect, useRef, useState } from 'react'
import { Box, Button, Chip, IconButton, TextField, Typography } from '@mui/material'
import AddIcon from '@mui/icons-material/Add'
import UploadIcon from '@mui/icons-material/Upload'
import RefreshIcon from '@mui/icons-material/Refresh'
import EditOutlinedIcon from '@mui/icons-material/EditOutlined'
import DeleteOutlineIcon from '@mui/icons-material/DeleteOutline'
import { useTranslation } from 'react-i18next'
import { PageHeader } from '@/components/PageHeader'
import { AppTable, type AppColumn } from '@/components/AppTable'
import { AppPagination } from '@/components/AppPagination'
import { DebouncedSearch } from '@/components/DebouncedSearch'
import { FormDialog } from '@/components/FormDialog'
import { ConfirmDialog } from '@/components/ConfirmDialog'
import { useSnackbarStore } from '@/stores/snackbar'
import { knowledgeApi } from '@/api/knowledge'
import { formatTime } from '@/utils/format'
import type { KnowledgeArticle } from '@/types/admin'

const LIMIT = 20

export default function KnowledgeView() {
  const { t } = useTranslation()
  const snackbar = useSnackbarStore()

  const [knowledge, setKnowledge] = useState<KnowledgeArticle[]>([])
  const [total, setTotal] = useState(0)
  const [page, setPage] = useState(1)
  const [loading, setLoading] = useState(false)
  const [q, setQ] = useState('')

  const [showForm, setShowForm] = useState(false)
  const [editing, setEditing] = useState<KnowledgeArticle | null>(null)
  const [saving, setSaving] = useState(false)
  const [form, setForm] = useState({ title: '', content: '', category: '' })

  const [showDelete, setShowDelete] = useState(false)
  const [pendingDelete, setPendingDelete] = useState<KnowledgeArticle | null>(null)

  const fileInput = useRef<HTMLInputElement>(null)

  async function load(p = 1) {
    setLoading(true)
    try {
      const res = await knowledgeApi.list(p, LIMIT, q || undefined)
      setKnowledge(res.items)
      setTotal(res.total)
      setPage(p)
    } catch (err) {
      snackbar.error(err instanceof Error ? err.message : t('loadFailed'))
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    void load(1)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  function openCreate() {
    setEditing(null)
    setForm({ title: '', content: '', category: '' })
    setShowForm(true)
  }
  function openEdit(item: KnowledgeArticle) {
    setEditing(item)
    setForm({ title: item.title, content: item.content, category: item.category || '' })
    setShowForm(true)
  }
  async function onSave() {
    if (!form.title.trim() || !form.content.trim()) {
      snackbar.error(t('titleContentRequired'))
      return
    }
    setSaving(true)
    try {
      const data = { title: form.title.trim(), content: form.content, category: form.category || undefined }
      if (editing) {
        await knowledgeApi.update(editing.id, data)
      } else {
        await knowledgeApi.create(data)
      }
      snackbar.success(t('saved'))
      setShowForm(false)
      void load(page)
    } catch (err) {
      snackbar.error(err instanceof Error ? err.message : t('saveFailed'))
    } finally {
      setSaving(false)
    }
  }

  function confirmDelete(item: KnowledgeArticle) {
    setPendingDelete(item)
    setShowDelete(true)
  }
  async function onDelete() {
    if (!pendingDelete) return
    try {
      await knowledgeApi.remove(pendingDelete.id)
      snackbar.success(t('deleted'))
      void load(page)
    } catch (err) {
      snackbar.error(err instanceof Error ? err.message : t('deleteFailed'))
    } finally {
      setShowDelete(false)
    }
  }

  async function onUploadFile(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0]
    if (!file) return
    try {
      await knowledgeApi.upload(file)
      snackbar.success(t('uploadSuccess'))
      e.target.value = ''
      void load(1)
    } catch (err) {
      snackbar.error(err instanceof Error ? err.message : t('uploadFailed'))
    }
  }

  const headers: AppColumn<KnowledgeArticle>[] = [
    { key: 'id', title: t('idCol'), width: 70 },
    { key: 'title', title: t('titleLabel') },
    { key: 'category', title: t('categoryOptional'), render: (i) => (i.category ? <Chip size="small" label={i.category} /> : <span>-</span>) },
    { key: 'sourceFile', title: t('sourceFile'), render: (i) => (i.sourceFile ? <Typography variant="caption">{i.sourceFile}</Typography> : <span>-</span>) },
    { key: 'createdAt', title: t('createdAt'), render: (i) => formatTime(i.createdAt) },
    {
      key: 'actions',
      title: t('actionCol'),
      render: (i) => (
        <>
          <IconButton size="small" onClick={() => openEdit(i)}>
            <EditOutlinedIcon fontSize="small" />
          </IconButton>
          <IconButton size="small" color="error" onClick={() => confirmDelete(i)}>
            <DeleteOutlineIcon fontSize="small" />
          </IconButton>
        </>
      ),
    },
  ]

  return (
    <Box>
      <PageHeader title={t('navKnowledge')} subtitle={t('total', { n: total })}>
        <Button color="primary" variant="contained" startIcon={<AddIcon />} onClick={openCreate}>
          {t('newArticle')}
        </Button>
        <Button variant="outlined" startIcon={<UploadIcon />} onClick={() => fileInput.current?.click()}>
          {t('uploadDocument')}
        </Button>
        <input ref={fileInput} type="file" accept=".pdf,.docx" hidden onChange={onUploadFile} />
      </PageHeader>

      <Box sx={{ display: 'flex', gap: 1.5, mb: 2, p: 2, bgcolor: 'background.paper', border: 1, borderColor: 'divider', borderRadius: 2 }}>
        <DebouncedSearch value={q} placeholder={t('searchKnowledge')} onChange={setQ} onSearch={() => void load(1)} />
        <Button variant="outlined" startIcon={<RefreshIcon />} onClick={() => void load(1)}>
          {t('reset')}
        </Button>
      </Box>

      <AppTable headers={headers} items={knowledge} loading={loading} emptyText={t('noKnowledge')} />
      <AppPagination page={page} limit={LIMIT} total={total} loading={loading} onChange={(p) => void load(p)} />

      <FormDialog open={showForm} title={editing ? t('editArticle') : t('createArticle')} loading={saving} onClose={() => setShowForm(false)} onSave={() => void onSave()}>
        <Box component="form" onSubmit={(e) => { e.preventDefault(); void onSave() }}>
          <TextField label={t('titleLabel')} required fullWidth margin="dense" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} />
          <TextField label={t('categoryOptional')} fullWidth margin="dense" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} />
          <TextField label={t('contentMarkdown')} multiline rows={6} required fullWidth margin="dense" value={form.content} onChange={(e) => setForm({ ...form, content: e.target.value })} />
        </Box>
      </FormDialog>

      <ConfirmDialog
        open={showDelete}
        title={t('deleteArticleTitle')}
        content={t('deleteArticleContent', { title: pendingDelete?.title || '' })}
        onClose={() => setShowDelete(false)}
        onConfirm={() => void onDelete()}
      />
    </Box>
  )
}

// Web-Admin-Vue/src/views/knowledge/KnowledgeView.vue
<template>
  <div>
    <PageHeader :title="t('navKnowledge')" :subtitle="t('total', { n: total })">
      <v-btn color="primary" prepend-icon="mdi-plus" @click="openCreate">{{ t('newArticle') }}</v-btn>
      <v-btn variant="tonal" prepend-icon="mdi-upload" @click="fileInput?.click()">{{ t('uploadDocument') }}</v-btn>
      <input ref="fileInput" type="file" accept=".pdf,.docx" class="d-none" @change="onUploadFile" />
    </PageHeader>

    <v-card class="mb-4">
      <v-card-text class="d-flex ga-3">
        <DebouncedSearch v-model="q" :placeholder="t('searchKnowledge')" class="flex-grow-1" @search="load(1)" />
        <v-btn variant="tonal" prepend-icon="mdi-refresh" @click="load(1)">{{ t('reset') }}</v-btn>
      </v-card-text>
    </v-card>

    <AppTable :headers="headers" :items="knowledge" :loading="loading" :total="total" :items-per-page="limit">
      <template #item.category="{ item }">
        <v-chip v-if="item.category" size="small" variant="tonal">{{ item.category }}</v-chip>
        <span v-else>-</span>
      </template>
      <template #item.sourceFile="{ item }">
        <span v-if="item.sourceFile" class="text-caption">{{ item.sourceFile }}</span>
        <span v-else>-</span>
      </template>
      <template #item.actions="{ item }">
        <v-btn icon="mdi-pencil-outline" variant="text" size="small" @click="openEdit(item)" />
        <v-btn icon="mdi-delete-outline" variant="text" size="small" color="error" @click="confirmDelete(item)" />
      </template>
    </AppTable>

    <AppPagination :page="page" :limit="limit" :total="total" :loading="loading" @update:page="load" />

    <FormDialog v-model="showForm" :title="editing ? t('editArticle') : t('createArticle')" :loading="saving" @save="onSave">
      <v-form @submit.prevent="onSave">
        <v-text-field v-model="form.title" :label="t('titleLabel')" required />
        <v-text-field v-model="form.category" :label="t('categoryOptional')" />
        <v-textarea v-model="form.content" :label="t('contentMarkdown')" rows="6" required />
      </v-form>
    </FormDialog>

    <ConfirmDialog
      v-model="showDelete"
      :title="t('deleteArticleTitle')"
      :content="t('deleteArticleContent', { title: pendingDelete?.title || '' })"
      @confirm="onDelete"
    />
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import PageHeader from '@/components/PageHeader.vue'
import AppTable from '@/components/AppTable.vue'
import AppPagination from '@/components/AppPagination.vue'
import DebouncedSearch from '@/components/DebouncedSearch.vue'
import FormDialog from '@/components/FormDialog.vue'
import ConfirmDialog from '@/components/ConfirmDialog.vue'
import { useSnackbarStore } from '@/stores/snackbar'
import { knowledgeApi } from '@/api/knowledge'
import type { KnowledgeArticle } from '@/types/admin'

const { t } = useI18n()
const snackbar = useSnackbarStore()

const knowledge = ref<KnowledgeArticle[]>([])
const total = ref(0)
const page = ref(1)
const limit = 20
const loading = ref(false)
const q = ref('')

const headers = computed(() => [
  { key: 'id', title: t('idCol') },
  { key: 'title', title: t('titleLabel') },
  { key: 'category', title: t('categoryOptional') },
  { key: 'sourceFile', title: t('sourceFile') },
  { key: 'createdAt', title: t('createdAt') },
  { key: 'actions', title: t('actionCol') },
])

async function load(p = 1) {
  loading.value = true
  try {
    const res = await knowledgeApi.list(p, limit, q.value || undefined)
    knowledge.value = res.items
    total.value = res.total
    page.value = p
  } catch (err) {
    snackbar.error(err instanceof Error ? err.message : t('loadFailed'))
  } finally {
    loading.value = false
  }
}

// 新建/编辑
const showForm = ref(false)
const editing = ref<KnowledgeArticle | null>(null)
const saving = ref(false)
const form = ref({ title: '', content: '', category: '' })

function openCreate() {
  editing.value = null
  form.value = { title: '', content: '', category: '' }
  showForm.value = true
}
function openEdit(item: KnowledgeArticle) {
  editing.value = item
  form.value = { title: item.title, content: item.content, category: item.category || '' }
  showForm.value = true
}
async function onSave() {
  if (!form.value.title.trim() || !form.value.content.trim()) {
    snackbar.error(t('titleContentRequired'))
    return
  }
  saving.value = true
  try {
    const data = { title: form.value.title.trim(), content: form.value.content, category: form.value.category || undefined }
    if (editing.value) {
      await knowledgeApi.update(editing.value.id, data)
    } else {
      await knowledgeApi.create(data)
    }
    snackbar.success(t('saved'))
    showForm.value = false
    load(page.value)
  } catch (err) {
    snackbar.error(err instanceof Error ? err.message : t('saveFailed'))
  } finally {
    saving.value = false
  }
}

// 删除
const showDelete = ref(false)
const pendingDelete = ref<KnowledgeArticle | null>(null)
function confirmDelete(item: KnowledgeArticle) {
  pendingDelete.value = item
  showDelete.value = true
}
async function onDelete() {
  if (!pendingDelete.value) return
  try {
    await knowledgeApi.remove(pendingDelete.value.id)
    snackbar.success(t('deleted'))
    load(page.value)
  } catch (err) {
    snackbar.error(err instanceof Error ? err.message : t('deleteFailed'))
  } finally {
    showDelete.value = false
  }
}

// 上传
const fileInput = ref<HTMLInputElement | null>(null)
const uploading = ref(false)
async function onUploadFile(e: Event) {
  const input = e.target as HTMLInputElement
  const file = input.files?.[0]
  if (!file) return
  uploading.value = true
  try {
    await knowledgeApi.upload(file)
    snackbar.success(t('uploadSuccess'))
    input.value = ''
    load(1)
  } catch (err) {
    snackbar.error(err instanceof Error ? err.message : t('uploadFailed'))
  } finally {
    uploading.value = false
  }
}

onMounted(() => load(1))
</script>
