// Front-Taro/src/pages/login/index.vue
<template>
  <view class="login">
    <view class="login__content">
      <view class="login__header">
        <view class="login__icon">
          <text class="login__icon-text">A</text>
        </view>
        <text class="login__title">App</text>
        <text class="login__subtitle">Sign in to continue</text>
      </view>

      <view v-if="errorMessage" class="login__error">
        <text class="login__error-text">{{ errorMessage }}</text>
      </view>

      <view class="login__form">
        <view class="form-group">
          <text class="form-label">Username</text>
          <input
            class="form-input"
            :class="{ 'form-input--error': errors.username }"
            placeholder="Enter your username"
            v-model="username"
          />
          <text v-if="errors.username" class="form-error">{{ errors.username }}</text>
        </view>

        <view class="form-group">
          <text class="form-label">Password</text>
          <view class="password-input">
            <input
              class="form-input"
              :class="{ 'form-input--error': errors.password }"
              placeholder="Enter your password"
              :password="!showPassword"
              v-model="password"
            />
            <text class="password-toggle" @click="showPassword = !showPassword">
              {{ showPassword ? 'Hide' : 'Show' }}
            </text>
          </view>
          <text v-if="errors.password" class="form-error">{{ errors.password }}</text>
        </view>

        <button
          class="login__button"
          :loading="isLoading"
          :disabled="isLoading"
          @click="handleSubmit"
        >
          Sign In
        </button>

        <view class="login__footer">
          <text class="login__footer-text">Don't have an account? </text>
          <text class="login__footer-link" @click="goRegister">Register</text>
        </view>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import Taro from '@tarojs/taro'
import { storeToRefs } from 'pinia'
import { useAuthStore } from '../../stores/auth-store'
import { validateUsername, validateRequired } from '../../utils/validators'

const store = useAuthStore()
const { status, errorMessage } = storeToRefs(store)
const username = ref('')
const password = ref('')
const showPassword = ref(false)
const errors = ref<{ username?: string; password?: string }>({})

const isLoading = computed(() => status.value === 'loading')

async function handleSubmit() {
  const usernameErr = validateUsername(username.value)
  const passwordErr = validateRequired(password.value, 'Password')
  errors.value = { username: usernameErr || undefined, password: passwordErr || undefined }

  if (usernameErr || passwordErr) return

  const success = await store.login(username.value.trim(), password.value)
  if (success) {
    Taro.redirectTo({ url: '/pages/dashboard/index' })
  }
}

function goRegister() {
  Taro.navigateTo({ url: '/pages/register/index' })
}
</script>

<style src="./index.scss" scoped></style>

// Front-Taro-Admin/src/pages/login/index.tsx
import { useState } from 'react'
import { View, Text, Input, Button } from '@tarojs/components'
import Taro from '@tarojs/taro'
import { useAuthStore } from '../../stores/auth-store'
import { APP_NAME } from '../../utils/constants'
import { useLocaleStore, t } from '../../i18n'
import './index.scss'

function LoginPage() {
  const { status, errorMessage, login, tryAutoLogin } = useAuthStore()
  const { locale, toggle } = useLocaleStore()
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [showPassword, setShowPassword] = useState(false)

  const handleSubmit = async () => {
    if (!username || !password) return
    const ok = await login(username, password)
    if (ok) {
      Taro.redirectTo({ url: '/pages/main/index' })
    }
  }

  return (
    <View className='admin-login'>
      <View className='admin-login__card'>
        <View className='admin-login__header'>
          <Text className='admin-login__title'>{APP_NAME}</Text>
          <Text className='admin-login__subtitle'>{t('loginTitle')}</Text>
          <Text className='admin-login__lang' onClick={toggle}>
            {locale === 'zh' ? 'EN' : '中文'}
          </Text>
        </View>

        {errorMessage && (
          <View className='admin-login__error'>
            <Text>{errorMessage}</Text>
          </View>
        )}

        <View className='admin-login__form'>
          <View className='admin-login__field'>
            <Text className='admin-login__label'>{t('username')}</Text>
            <Input
              className='admin-login__input'
              placeholder={t('usernamePlaceholder')}
              value={username}
              onInput={(e) => setUsername(e.detail.value)}
            />
          </View>

          <View className='admin-login__field'>
            <Text className='admin-login__label'>{t('password')}</Text>
            <View className='admin-login__password'>
              <Input
                className='admin-login__input'
                password={!showPassword}
                placeholder={t('passwordPlaceholder')}
                value={password}
                onInput={(e) => setPassword(e.detail.value)}
                onConfirm={handleSubmit}
              />
              <Text
                className='admin-login__toggle'
                onClick={() => setShowPassword(!showPassword)}
              >
                {showPassword ? t('cancel') : t('show')}
              </Text>
            </View>
          </View>

          <Button
            className='admin-login__button'
            onClick={handleSubmit}
            disabled={status === 'loading'}
          >
            {status === 'loading' ? t('loggingIn') : t('login')}
          </Button>
        </View>
      </View>
    </View>
  )
}

export default LoginPage
