// Web-Admin-Vue/src/views/users/UsersView.vue
<template>
  <div>
    <PageHeader :title="t('navUsers')" :subtitle="t('userTotal', { n: total })">
      <v-btn color="primary" prepend-icon="mdi-plus" @click="openCreate">{{ t('newUser') }}</v-btn>
    </PageHeader>

    <v-card class="mb-4">
      <v-card-text class="d-flex ga-3 flex-wrap">
        <DebouncedSearch
          v-model="searchInput"
          :placeholder="t('searchUserPlaceholder')"
          class="flex-grow-1"
          style="max-width: 320px"
          @search="onSearch"
        />
        <v-btn variant="tonal" prepend-icon="mdi-refresh" @click="load(1)">{{ t('reset') }}</v-btn>
      </v-card-text>
    </v-card>

    <AppTable
      :headers="headers"
      :items="users"
      :loading="loading"
      :total="total"
      :items-per-page="limit"
    >
      <template #item.username="{ item }">
        <a class="text-decoration-none" href="#" @click.prevent="openDetail(item.id)">{{ item.username }}</a>
      </template>
      <template #item.role="{ item }">
        <v-select
          :model-value="item.role"
          :items="['user', 'admin']"
          density="compact"
          variant="outlined"
          hide-details
          style="max-width: 110px"
          @update:model-value="(v) => onChangeRole(item.id, v as string)"
        />
      </template>
      <template #item.createdAt="{ item }">
        {{ formatTime(item.createdAt) }}
      </template>
      <template #item.actions="{ item }">
        <v-btn
          icon="mdi-delete-outline"
          variant="text"
          size="small"
          color="error"
          @click="confirmDelete(item)"
        />
      </template>
    </AppTable>

    <AppPagination :page="page" :limit="limit" :total="total" :loading="loading" @update:page="load" />

    <!-- 新建用户 -->
    <FormDialog
      v-model="showCreate"
      :title="t('newUser')"
      :loading="creating"
      @save="onCreate"
    >
      <v-form @submit.prevent="onCreate">
        <v-text-field v-model="createForm.username" :label="t('usernameCol')" required />
        <v-text-field v-model="createForm.email" label="Email" type="email" required />
        <v-text-field v-model="createForm.password" :label="t('password')" type="password" required />
        <v-text-field v-model="createForm.nickname" :label="t('nicknameCol')" required />
        <v-row>
          <v-col cols="6">
            <v-text-field v-model="createForm.firstName" label="First name" />
          </v-col>
          <v-col cols="6">
            <v-text-field v-model="createForm.lastName" label="Last name" />
          </v-col>
        </v-row>
      </v-form>
    </FormDialog>

    <!-- 删除确认 -->
    <ConfirmDialog
      v-model="showDelete"
      :title="t('deleteUserTitle')"
      :content="t('deleteUserContent', { name: pendingDelete?.username || '' })"
      @confirm="onDelete"
    />
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import PageHeader from '@/components/PageHeader.vue'
import AppTable from '@/components/AppTable.vue'
import AppPagination from '@/components/AppPagination.vue'
import DebouncedSearch from '@/components/DebouncedSearch.vue'
import FormDialog from '@/components/FormDialog.vue'
import ConfirmDialog from '@/components/ConfirmDialog.vue'
import { useSnackbarStore } from '@/stores/snackbar'
import { usersApi } from '@/api/users'
import { formatTime } from '@/utils/format'
import type { AdminUser, UserRole } from '@/types/user'

const { t } = useI18n()
const router = useRouter()
const snackbar = useSnackbarStore()

const users = ref<AdminUser[]>([])
const total = ref(0)
const page = ref(1)
const limit = 20
const loading = ref(false)
const searchInput = ref('')

const headers = [
  { key: 'id', title: t('idCol') },
  { key: 'username', title: t('usernameCol') },
  { key: 'email', title: t('emailCol') },
  { key: 'role', title: t('roleCol') },
  { key: 'createdAt', title: t('createdAt') },
  { key: 'actions', title: t('actionCol') },
]

async function load(p = 1) {
  loading.value = true
  try {
    const res = await usersApi.list(p, limit, searchInput.value || undefined)
    users.value = res.items
    total.value = res.total
    page.value = p
  } catch (err) {
    snackbar.error(err instanceof Error ? err.message : t('loadFailed'))
  } finally {
    loading.value = false
  }
}

function onSearch() {
  load(1)
}

// 新建
const showCreate = ref(false)
const creating = ref(false)
const emptyCreate = { username: '', email: '', password: '', nickname: '', firstName: '', lastName: '' }
const createForm = ref({ ...emptyCreate })

function openCreate() {
  createForm.value = { ...emptyCreate }
  showCreate.value = true
}

async function onCreate() {
  const f = createForm.value
  if (!f.username.trim() || !f.email.trim() || !f.password.trim() || !f.nickname.trim()) {
    snackbar.error(t('fillCreateForm'))
    return
  }
  creating.value = true
  try {
    await usersApi.create({
      username: f.username.trim(),
      email: f.email.trim(),
      password: f.password,
      nickname: f.nickname.trim(),
      firstName: f.firstName.trim() || undefined,
      lastName: f.lastName.trim() || undefined,
    })
    snackbar.success(t('userCreated'))
    showCreate.value = false
    load(1)
  } catch (err) {
    snackbar.error(err instanceof Error ? err.message : t('createFailed'))
  } finally {
    creating.value = false
  }
}

// 改角色
async function onChangeRole(id: number, role: string) {
  try {
    await usersApi.updateRole(id, role as UserRole)
    snackbar.success(t('roleUpdated'))
  } catch (err) {
    snackbar.error(err instanceof Error ? err.message : t('updateFailed'))
    load(page.value)
  }
}

// 删除
const showDelete = ref(false)
const pendingDelete = ref<AdminUser | null>(null)
function confirmDelete(user: AdminUser) {
  pendingDelete.value = user
  showDelete.value = true
}
async function onDelete() {
  if (!pendingDelete.value) return
  try {
    await usersApi.remove(pendingDelete.value.id)
    snackbar.success(t('deleted'))
    load(page.value)
  } catch (err) {
    snackbar.error(err instanceof Error ? err.message : t('deleteFailed'))
  } finally {
    showDelete.value = false
  }
}

function openDetail(id: number) {
  router.push(`/users/${id}`)
}

onMounted(() => load(1))
</script>

// Web-Admin-React/src/views/users/UsersView.tsx
import { useEffect, useState } from 'react'
import { Box, Button, IconButton, MenuItem, Select, TextField, Typography } from '@mui/material'
import AddIcon from '@mui/icons-material/Add'
import RefreshIcon from '@mui/icons-material/Refresh'
import DeleteOutlineIcon from '@mui/icons-material/DeleteOutline'
import { useNavigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { PageHeader } from '@/components/PageHeader'
import { AppTable, type AppColumn } from '@/components/AppTable'
import { AppPagination } from '@/components/AppPagination'
import { DebouncedSearch } from '@/components/DebouncedSearch'
import { FormDialog } from '@/components/FormDialog'
import { ConfirmDialog } from '@/components/ConfirmDialog'
import { useSnackbarStore } from '@/stores/snackbar'
import { usersApi } from '@/api/users'
import { formatTime } from '@/utils/format'
import type { AdminUser, UserRole } from '@/types/user'

const LIMIT = 20
const emptyCreate = { username: '', email: '', password: '', nickname: '', firstName: '', lastName: '' }

export default function UsersView() {
  const { t } = useTranslation()
  const navigate = useNavigate()
  const snackbar = useSnackbarStore()

  const [users, setUsers] = useState<AdminUser[]>([])
  const [total, setTotal] = useState(0)
  const [page, setPage] = useState(1)
  const [loading, setLoading] = useState(false)
  const [searchInput, setSearchInput] = useState('')

  const [showCreate, setShowCreate] = useState(false)
  const [creating, setCreating] = useState(false)
  const [createForm, setCreateForm] = useState({ ...emptyCreate })

  const [showDelete, setShowDelete] = useState(false)
  const [pendingDelete, setPendingDelete] = useState<AdminUser | null>(null)

  async function load(p = 1) {
    setLoading(true)
    try {
      const res = await usersApi.list(p, LIMIT, searchInput || undefined)
      setUsers(res.items)
      setTotal(res.total)
      setPage(p)
    } catch (err) {
      snackbar.error(err instanceof Error ? err.message : t('loadFailed'))
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    void load(1)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  function onSearch() {
    void load(1)
  }

  function openCreate() {
    setCreateForm({ ...emptyCreate })
    setShowCreate(true)
  }

  async function onCreate() {
    const f = createForm
    if (!f.username.trim() || !f.email.trim() || !f.password.trim() || !f.nickname.trim()) {
      snackbar.error(t('fillCreateForm'))
      return
    }
    setCreating(true)
    try {
      await usersApi.create({
        username: f.username.trim(),
        email: f.email.trim(),
        password: f.password,
        nickname: f.nickname.trim(),
        firstName: f.firstName.trim() || undefined,
        lastName: f.lastName.trim() || undefined,
      })
      snackbar.success(t('userCreated'))
      setShowCreate(false)
      void load(1)
    } catch (err) {
      snackbar.error(err instanceof Error ? err.message : t('createFailed'))
    } finally {
      setCreating(false)
    }
  }

  async function onChangeRole(id: number, role: string) {
    try {
      await usersApi.updateRole(id, role as UserRole)
      snackbar.success(t('roleUpdated'))
    } catch (err) {
      snackbar.error(err instanceof Error ? err.message : t('updateFailed'))
      void load(page)
    }
  }

  function confirmDelete(user: AdminUser) {
    setPendingDelete(user)
    setShowDelete(true)
  }

  async function onDelete() {
    if (!pendingDelete) return
    try {
      await usersApi.remove(pendingDelete.id)
      snackbar.success(t('deleted'))
      void load(page)
    } catch (err) {
      snackbar.error(err instanceof Error ? err.message : t('deleteFailed'))
    } finally {
      setShowDelete(false)
    }
  }

  const headers: AppColumn<AdminUser>[] = [
    { key: 'id', title: t('idCol'), width: 70 },
    {
      key: 'username',
      title: t('usernameCol'),
      render: (item) => (
        <Typography
          component="a"
          color="primary"
          sx={{ textDecoration: 'none', cursor: 'pointer' }}
          onClick={() => navigate(`/users/${item.id}`)}
        >
          {item.username}
        </Typography>
      ),
    },
    { key: 'email', title: t('emailCol') },
    {
      key: 'role',
      title: t('roleCol'),
      width: 130,
      render: (item) => (
        <Select
          size="small"
          value={item.role}
          onChange={(e) => void onChangeRole(item.id, e.target.value as string)}
          sx={{ minWidth: 100 }}
        >
          <MenuItem value="user">user</MenuItem>
          <MenuItem value="admin">admin</MenuItem>
        </Select>
      ),
    },
    {
      key: 'createdAt',
      title: t('createdAt'),
      render: (item) => formatTime(item.createdAt),
    },
    {
      key: 'actions',
      title: t('actionCol'),
      render: (item) => (
        <IconButton size="small" color="error" onClick={() => confirmDelete(item)}>
          <DeleteOutlineIcon />
        </IconButton>
      ),
    },
  ]

  return (
    <Box>
      <PageHeader title={t('navUsers')} subtitle={t('userTotal', { n: total })}>
        <Button color="primary" variant="contained" startIcon={<AddIcon />} onClick={openCreate}>
          {t('newUser')}
        </Button>
      </PageHeader>

      <Box sx={{ display: 'flex', gap: 1.5, flexWrap: 'wrap', mb: 2, p: 2, bgcolor: 'background.paper', border: 1, borderColor: 'divider', borderRadius: 2 }}>
        <DebouncedSearch value={searchInput} placeholder={t('searchUserPlaceholder')} onChange={setSearchInput} onSearch={onSearch} />
        <Button variant="outlined" startIcon={<RefreshIcon />} onClick={() => void load(1)}>
          {t('reset')}
        </Button>
      </Box>

      <AppTable headers={headers} items={users} loading={loading} emptyText={t('noUsers')} />

      <AppPagination page={page} limit={LIMIT} total={total} loading={loading} onChange={(p) => void load(p)} />

      <FormDialog open={showCreate} title={t('newUser')} loading={creating} onClose={() => setShowCreate(false)} onSave={() => void onCreate()}>
        <Box component="form" onSubmit={(e) => { e.preventDefault(); void onCreate() }}>
          <TextField label={t('usernameCol')} required fullWidth margin="dense" value={createForm.username} onChange={(e) => setCreateForm({ ...createForm, username: e.target.value })} />
          <TextField label="Email" type="email" required fullWidth margin="dense" value={createForm.email} onChange={(e) => setCreateForm({ ...createForm, email: e.target.value })} />
          <TextField label={t('password')} type="password" required fullWidth margin="dense" value={createForm.password} onChange={(e) => setCreateForm({ ...createForm, password: e.target.value })} />
          <TextField label={t('nicknameCol')} required fullWidth margin="dense" value={createForm.nickname} onChange={(e) => setCreateForm({ ...createForm, nickname: e.target.value })} />
          <Box sx={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 1.5 }}>
            <TextField label="First name" margin="dense" value={createForm.firstName} onChange={(e) => setCreateForm({ ...createForm, firstName: e.target.value })} />
            <TextField label="Last name" margin="dense" value={createForm.lastName} onChange={(e) => setCreateForm({ ...createForm, lastName: e.target.value })} />
          </Box>
        </Box>
      </FormDialog>

      <ConfirmDialog
        open={showDelete}
        title={t('deleteUserTitle')}
        content={t('deleteUserContent', { name: pendingDelete?.username || '' })}
        onClose={() => setShowDelete(false)}
        onConfirm={() => void onDelete()}
      />
    </Box>
  )
}
