// Web-Admin/src/views/users/UserDetailView.vue
<template>
  <div>
    <PageHeader :title="`${t('navUsers')} #${id}`" :subtitle="detail?.username || ''">
      <v-btn variant="text" prepend-icon="mdi-arrow-left" @click="router.back()">{{ t('back') }}</v-btn>
    </PageHeader>

    <div v-if="loading" class="text-medium-emphasis pa-4">{{ t('loading') }}</div>

    <template v-else-if="detail">
      <v-row>
        <v-col cols="12" md="6">
          <v-card class="mb-4">
            <v-card-title>{{ t('appInfo') }}</v-card-title>
            <v-card-text>
              <v-list density="compact">
                <v-list-item><template #prepend><v-icon icon="mdi-account" size="small" /></template>{{ t('usernameCol') }}：{{ detail.username }}</v-list-item>
                <v-list-item><template #prepend><v-icon icon="mdi-email" size="small" /></template>{{ t('emailCol') }}：{{ detail.email }}</v-list-item>
                <v-list-item><template #prepend><v-icon icon="mdi-shield-account" size="small" /></template>{{ t('roleCol') }}：{{ detail.role }}</v-list-item>
                <v-list-item><template #prepend><v-icon icon="mdi-clock-outline" size="small" /></template>{{ t('createdAt') }}：{{ formatTime(detail.createdAt) }}</v-list-item>
              </v-list>
            </v-card-text>
          </v-card>
        </v-col>
        <v-col cols="12" md="6">
          <v-row>
            <v-col v-for="stat in statCards" :key="stat.label" cols="6">
              <StatCard v-bind="stat" />
            </v-col>
          </v-row>
        </v-col>
      </v-row>

      <v-row>
        <v-col cols="12" md="6">
          <v-card>
            <v-card-title>{{ t('sessions') }}</v-card-title>
            <v-card-text>
              <v-list v-if="detail.sessions.length" density="compact">
                <v-list-item v-for="s in detail.sessions" :key="s.id">
                  <v-list-item-title>{{ s.deviceName || t('unknownDevice') }}</v-list-item-title>
                  <v-list-item-subtitle>{{ s.ip }} · {{ formatTime(s.lastActiveAt) }}</v-list-item-subtitle>
                </v-list-item>
              </v-list>
              <div v-else class="text-medium-emphasis">{{ t('noSessions') }}</div>
            </v-card-text>
          </v-card>
        </v-col>
        <v-col cols="12" md="6">
          <v-card>
            <v-card-title>{{ t('notifications') }}</v-card-title>
            <v-card-text>
              <v-list v-if="detail.notifications.length" density="compact">
                <v-list-item v-for="n in detail.notifications" :key="n.id">
                  <v-list-item-title>{{ n.title }} <StatusChip :status="n.isRead ? 'read' : 'unread'" :label-map="readMap" /></v-list-item-title>
                  <v-list-item-subtitle>{{ n.body }} · {{ formatTime(n.createdAt) }}</v-list-item-subtitle>
                </v-list-item>
              </v-list>
              <div v-else class="text-medium-emphasis">{{ t('noNotifications') }}</div>
            </v-card-text>
          </v-card>
        </v-col>
      </v-row>
    </template>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import PageHeader from '@/components/PageHeader.vue'
import StatCard from '@/components/StatCard.vue'
import StatusChip from '@/components/StatusChip.vue'
import { usersApi } from '@/api/users'
import { formatTime } from '@/utils/format'
import type { UserDetail } from '@/types/admin'

const route = useRoute()
const router = useRouter()
const { t } = useI18n()
const id = Number(route.params.id)

const detail = ref<UserDetail | null>(null)
const loading = ref(true)

const readMap = { read: t('read'), unread: t('unread') }

const statCards = computed(() => [
  { label: t('events'), value: detail.value?.counts.events ?? '-', icon: 'mdi-calendar-blank-outline', color: 'success' },
  { label: t('opAuditLogs'), value: detail.value?.counts.operationAuditLogs ?? '-', icon: 'mdi-clipboard-text-outline', color: 'info' },
  { label: t('aiAuditLogs'), value: detail.value?.counts.aiAuditLogs ?? '-', icon: 'mdi-history', color: 'primary' },
  { label: t('totalTokens'), value: detail.value?.counts.totalTokens ?? '-', icon: 'mdi-database-outline', color: 'warning' },
])

async function load() {
  try {
    detail.value = await usersApi.detail(id)
  } catch (err) {
    // global snackbar
  } finally {
    loading.value = false
  }
}

onMounted(load)
</script>

// Web-Admin-React/src/views/users/UserDetailView.tsx
import { useEffect, useState } from 'react'
import { Box, Card, CardContent, CardHeader, Grid, List, ListItem, ListItemIcon, ListItemText, Typography } from '@mui/material'
import ArrowBackIcon from '@mui/icons-material/ArrowBack'
import AccountCircleIcon from '@mui/icons-material/AccountCircle'
import EmailIcon from '@mui/icons-material/Email'
import AdminPanelSettingsIcon from '@mui/icons-material/AdminPanelSettings'
import ClockOutlineIcon from '@mui/icons-material/Schedule'
import CalendarMonthOutlinedIcon from '@mui/icons-material/CalendarMonthOutlined'
import DescriptionOutlinedIcon from '@mui/icons-material/DescriptionOutlined'
import HistoryOutlinedIcon from '@mui/icons-material/HistoryOutlined'
import StorageOutlinedIcon from '@mui/icons-material/StorageOutlined'
import { useNavigate, useParams } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { PageHeader } from '@/components/PageHeader'
import { StatCard } from '@/components/StatCard'
import { StatusChip } from '@/components/StatusChip'
import { useSnackbarStore } from '@/stores/snackbar'
import { usersApi } from '@/api/users'
import { formatTime } from '@/utils/format'
import type { UserDetail } from '@/types/admin'

export default function UserDetailView() {
  const { t } = useTranslation()
  const navigate = useNavigate()
  const { id } = useParams()
  const snackbar = useSnackbarStore()

  const [detail, setDetail] = useState<UserDetail | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    async function load() {
      try {
        setDetail(await usersApi.detail(Number(id)))
      } catch (err) {
        snackbar.error(err instanceof Error ? err.message : t('loadFailed'))
      } finally {
        setLoading(false)
      }
    }
    void load()
  }, [id, snackbar, t])

  if (loading) {
    return (
      <Typography color="text.secondary" sx={{ p: 2 }}>
        {t('loading')}
      </Typography>
    )
  }

  if (!detail) return null

  const statCards = [
    { label: t('events'), value: detail.counts.events ?? '-', icon: <CalendarMonthOutlinedIcon />, color: 'success' as const },
    { label: t('opAuditLogs'), value: detail.counts.operationAuditLogs ?? '-', icon: <DescriptionOutlinedIcon />, color: 'info' as const },
    { label: t('aiAuditLogs'), value: detail.counts.aiAuditLogs ?? '-', icon: <HistoryOutlinedIcon />, color: 'primary' as const },
    { label: t('totalTokens'), value: detail.counts.totalTokens ?? '-', icon: <StorageOutlinedIcon />, color: 'warning' as const },
  ]
  const readMap = { read: t('read'), unread: t('unread') }

  return (
    <Box>
      <PageHeader title={`${t('navUsers')} #${id}`} subtitle={detail.username}>
        <ButtonBack onClick={() => navigate(-1)} label={t('back')} />
      </PageHeader>

      <Grid container spacing={3}>
        <Grid item xs={12} md={6}>
          <Card sx={{ mb: 3 }}>
            <CardHeader title={t('appInfo')} />
            <CardContent>
              <List dense>
                <ListItem>
                  <ListItemIcon><AccountCircleIcon fontSize="small" /></ListItemIcon>
                  <ListItemText primary={`${t('usernameCol')}：${detail.username}`} />
                </ListItem>
                <ListItem>
                  <ListItemIcon><EmailIcon fontSize="small" /></ListItemIcon>
                  <ListItemText primary={`${t('emailCol')}：${detail.email}`} />
                </ListItem>
                <ListItem>
                  <ListItemIcon><AdminPanelSettingsIcon fontSize="small" /></ListItemIcon>
                  <ListItemText primary={`${t('roleCol')}：${detail.role}`} />
                </ListItem>
                <ListItem>
                  <ListItemIcon><ClockOutlineIcon fontSize="small" /></ListItemIcon>
                  <ListItemText primary={`${t('createdAt')}：${formatTime(detail.createdAt)}`} />
                </ListItem>
              </List>
            </CardContent>
          </Card>
        </Grid>
        <Grid item xs={12} md={6}>
          <Grid container spacing={2}>
            {statCards.map((s) => (
              <Grid key={s.label}  item xs={6}>
                <StatCard label={s.label} value={s.value} icon={s.icon} color={s.color} />
              </Grid>
            ))}
          </Grid>
        </Grid>
      </Grid>

      <Grid container spacing={3}>
        <Grid item xs={12} md={6}>
          <Card>
            <CardHeader title={t('sessions')} />
            <CardContent>
              {detail.sessions.length ? (
                <List dense>
                  {detail.sessions.map((s) => (
                    <ListItem key={s.id}>
                      <ListItemText
                        primary={s.deviceName || t('unknownDevice')}
                        secondary={`${s.ip} · ${formatTime(s.lastActiveAt)}`}
                      />
                    </ListItem>
                  ))}
                </List>
              ) : (
                <Typography color="text.secondary">{t('noSessions')}</Typography>
              )}
            </CardContent>
          </Card>
        </Grid>
        <Grid item xs={12} md={6}>
          <Card>
            <CardHeader title={t('notifications')} />
            <CardContent>
              {detail.notifications.length ? (
                <List dense>
                  {detail.notifications.map((n) => (
                    <ListItem key={n.id}>
                      <ListItemText
                        primary={
                          <Box sx={{ display: 'inline-flex', alignItems: 'center', gap: 1 }}>
                            {n.title}
                            <StatusChip status={n.isRead ? 'read' : 'unread'} labelMap={readMap} />
                          </Box>
                        }
                        secondary={`${n.body} · ${formatTime(n.createdAt)}`}
                      />
                    </ListItem>
                  ))}
                </List>
              ) : (
                <Typography color="text.secondary">{t('noNotifications')}</Typography>
              )}
            </CardContent>
          </Card>
        </Grid>
      </Grid>
    </Box>
  )
}

function ButtonBack({ onClick, label }: { onClick: () => void; label: string }) {
  return (
    <Typography component="a" color="inherit" sx={{ display: 'inline-flex', alignItems: 'center', gap: 0.5, cursor: 'pointer', textDecoration: 'none' }} onClick={onClick}>
      <ArrowBackIcon fontSize="small" />
      {label}
    </Typography>
  )
}
