// Web-Admin-Vue/src/layouts/AdminLayout.vue
<template>
  <v-layout class="rounded rounded-md">
    <v-navigation-drawer v-model="ui.drawer" :rail="rail" permanent @click="onDrawerClick">
      <template #prepend>
        <v-list-item
          :title="t('appName')"
          subtitle="KeelBase"
          prepend-icon="mdi-keel"
          class="brand-item"
        />
      </template>

      <v-list v-if="auth.isAdmin" density="comfortable" nav>
        <v-list-item
          :prepend-icon="'mdi-view-dashboard-outline'"
          :title="t('overview')"
          :active="route.path === '/'"
          @click="go('/')"
        />
      </v-list>

      <template v-for="group in navGroups" :key="group.label">
        <div class="nav-group-label">{{ group.label }}</div>
        <v-list density="comfortable" nav>
          <v-list-item
            v-for="item in group.items"
            :key="item.to"
            :prepend-icon="item.icon"
            :title="item.label"
            :active="isActive(item.name)"
            @click="go(item.to)"
          />
        </v-list>
      </template>

      <template #append>
        <div class="px-2 py-3">
          <v-divider class="mb-2" />
          <v-list-item
            :title="auth.user?.username || '-'"
            :subtitle="auth.user?.role || ''"
            prepend-icon="mdi-account-circle"
          />
          <div class="d-flex justify-space-between align-center px-2">
            <LangToggle />
            <ThemeToggle />
            <v-btn icon="mdi-logout" variant="text" size="small" :title="t('logout')" @click="onLogout" />
          </div>
        </div>
      </template>
    </v-navigation-drawer>

    <v-main class="admin-main">
      <v-app-bar elevation="0" border="b" class="admin-topbar">
        <v-app-bar-nav-icon variant="text" @click.stop="toggleRail" />
        <v-breadcrumbs :items="breadcrumbs" class="flex-grow-0" />
        <v-spacer />
        <ThemeToggle />
        <LangToggle />
        <v-btn variant="tonal" prepend-icon="mdi-logout" :title="t('logout')" @click="onLogout">
          {{ t('logout') }}
        </v-btn>
      </v-app-bar>

      <v-container fluid class="v-content-pad">
        <router-view />
      </v-container>
    </v-main>
  </v-layout>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { useUiStore } from '@/stores/ui'
import { useAuthStore } from '@/stores/auth'
import ThemeToggle from '@/components/ThemeToggle.vue'
import LangToggle from '@/components/LangToggle.vue'

const route = useRoute()
const router = useRouter()
const { t } = useI18n()
const ui = useUiStore()
const auth = useAuthStore()

const rail = ref(false)
function toggleRail() {
  rail.value = !rail.value
}
// rail 折叠时点击任意区域展开
function onDrawerClick() {
  if (rail.value) rail.value = false
}

function go(path: string) {
  router.push(path)
}

function isActive(name: string): boolean {
  // 详情页归其父导航激活（users/:id → 用户管理高亮）
  return route.name === name || (name === 'users' && route.name === 'user-detail')
}

async function onLogout() {
  await auth.logout()
  router.replace('/login')
}

const breadcrumbs = computed(() => {
  const metaTitle = route.meta?.title as string | undefined
  return [
    { title: t('appName') },
    ...(metaTitle ? [{ title: t(metaTitle) }] : []),
  ]
})

// 工作台（应用侧）导航：普通企业用户；WEB-FRONT-3 子页在此追加
const workspaceNavGroups = computed(() => [
  {
    label: t('navWorkbench'),
    items: [{ name: 'workbench-home', to: '/workbench', icon: 'mdi-home-outline', label: t('navWorkbench') }],
  },
  {
    label: t('navMy'),
    items: [
      { name: 'workbench-events', to: '/workbench/events', icon: 'mdi-calendar-blank-outline', label: t('workbenchMyEvents') },
      { name: 'workbench-todos', to: '/workbench/todos', icon: 'mdi-checkbox-marked-circle-outline', label: t('workbenchMyTodos') },
      { name: 'workbench-notifications', to: '/workbench/notifications', icon: 'mdi-bell-outline', label: t('workbenchNotifications') },
      { name: 'workbench-org', to: '/workbench/org', icon: 'mdi-account-group-outline', label: t('workbenchOrgDir') },
    ],
  },
])

// 控制台（管理侧）导航：对齐旧 NAV_GROUPS；P3 新增页面在对应组追加
const consoleNavGroups = computed(() => [
  {
    label: t('navData'),
    items: [
      { name: 'users', to: '/users', icon: 'mdi-account-group-outline', label: t('navUsers') },
      { name: 'org', to: '/org', icon: 'mdi-sitemap', label: t('navOrg') },
      { name: 'events', to: '/events', icon: 'mdi-calendar-blank-outline', label: t('navEvents') },
      { name: 'knowledge', to: '/knowledge', icon: 'mdi-book-open-variant', label: t('navKnowledge') },
      { name: 'notifications', to: '/notifications', icon: 'mdi-bullhorn-outline', label: t('navNotifications') },
      { name: 'trash', to: '/trash', icon: 'mdi-delete-outline', label: t('navTrash') },
      { name: 'data-import', to: '/data-import', icon: 'mdi-upload-multiple', label: t('navDataImport') },
      { name: 'tags', to: '/tags', icon: 'mdi-database-outline', label: t('navTags') },
      { name: 'notes', to: '/notes', icon: 'mdi-database-outline', label: t('navNotes') },
    ],
  },
  {
    label: t('navMonitor'),
    items: [
      { name: 'monitor', to: '/monitor', icon: 'mdi-heart-pulse', label: t('navMonitorCenter') },
      { name: 'audit', to: '/audit', icon: 'mdi-history', label: t('navAiAudit') },
      { name: 'op-audit', to: '/op-audit', icon: 'mdi-clipboard-text-outline', label: t('navOpAudit') },
      { name: 'sessions', to: '/sessions', icon: 'mdi-monitor-cellphone', label: t('navSessions') },
      { name: 'analytics', to: '/analytics', icon: 'mdi-chart-areaspline', label: t('navAnalytics') },
      { name: 'ai-eval', to: '/ai-eval', icon: 'mdi-flask-outline', label: t('navAiEval') },
      { name: 'ai-timeline', to: '/ai-timeline', icon: 'mdi-timeline-clock-outline', label: t('navAiTimeline') },
    ],
  },
  {
    label: t('navSystem'),
    items: [
      { name: 'observability', to: '/observability', icon: 'mdi-lan', label: t('navObservability') },
      { name: 'system', to: '/system', icon: 'mdi-cog-outline', label: t('navSystemInfo') },
      { name: 'templates', to: '/templates', icon: 'mdi-view-grid-plus-outline', label: t('navTemplates') },
      { name: 'ai-tools', to: '/ai-tools', icon: 'mdi-tools', label: t('navAiTools') },
    ],
  },
])

const navGroups = computed(() => (auth.isAdmin ? consoleNavGroups.value : workspaceNavGroups.value))
</script>

<style scoped>
.admin-main {
  background-color: rgb(var(--v-theme-background));
}
.brand-item {
  min-height: 56px;
}
</style>

// Web-Admin-React/src/layouts/AdminLayout.tsx
import { useState, type ComponentType } from 'react'
import {
  AppBar,
  Avatar,
  Box,
  Breadcrumbs,
  Button,
  Drawer,
  Divider,
  IconButton,
  List,
  ListItemButton,
  ListItemIcon,
  ListItemText,
  Toolbar,
  Typography,
} from '@mui/material'
import MenuIcon from '@mui/icons-material/Menu'
import LogoutIcon from '@mui/icons-material/Logout'
import DashboardOutlinedIcon from '@mui/icons-material/DashboardOutlined'
import GroupOutlinedIcon from '@mui/icons-material/GroupOutlined'
import AccountTreeOutlinedIcon from '@mui/icons-material/AccountTreeOutlined'
import CalendarMonthOutlinedIcon from '@mui/icons-material/CalendarMonthOutlined'
import MenuBookOutlinedIcon from '@mui/icons-material/MenuBookOutlined'
import CampaignOutlinedIcon from '@mui/icons-material/CampaignOutlined'
import DeleteOutlinedIcon from '@mui/icons-material/DeleteOutlined'
import FileUploadOutlinedIcon from '@mui/icons-material/FileUploadOutlined'
import StorageOutlinedIcon from '@mui/icons-material/StorageOutlined'
import MonitorHeartOutlinedIcon from '@mui/icons-material/MonitorHeartOutlined'
import HistoryOutlinedIcon from '@mui/icons-material/HistoryOutlined'
import DescriptionOutlinedIcon from '@mui/icons-material/DescriptionOutlined'
import DevicesOutlinedIcon from '@mui/icons-material/DevicesOutlined'
import InsightsOutlinedIcon from '@mui/icons-material/InsightsOutlined'
import ScienceOutlinedIcon from '@mui/icons-material/ScienceOutlined'
import TimelineOutlinedIcon from '@mui/icons-material/TimelineOutlined'
import LanOutlinedIcon from '@mui/icons-material/LanOutlined'
import SettingsOutlinedIcon from '@mui/icons-material/SettingsOutlined'
import GridViewOutlinedIcon from '@mui/icons-material/GridViewOutlined'
import HandymanOutlinedIcon from '@mui/icons-material/HandymanOutlined'
import HomeOutlinedIcon from '@mui/icons-material/HomeOutlined'
import CheckCircleOutlinedIcon from '@mui/icons-material/CheckCircleOutlined'
import NotificationsOutlinedIcon from '@mui/icons-material/NotificationsOutlined'
import type { SvgIconProps } from '@mui/material/SvgIcon'
import { Outlet, useLocation, useNavigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { useAuthStore, useIsAdmin } from '@/stores/auth'
import { ThemeToggle } from '@/components/ThemeToggle'
import { LangToggle } from '@/components/LangToggle'

interface NavItem {
  name: string
  to: string
  icon: ComponentType<SvgIconProps>
  label: string
}
interface NavGroup {
  label: string
  items: NavItem[]
}

// 面包屑标题映射：path → i18n key（等价 Vue route.meta.title）
const TITLE_BY_PATH: Record<string, string> = {
  '/': 'overview',
  '/users': 'navUsers',
  '/events': 'navEvents',
  '/knowledge': 'navKnowledge',
  '/notifications': 'navNotifications',
  '/monitor': 'navMonitorCenter',
  '/audit': 'navAiAudit',
  '/op-audit': 'navOpAudit',
  '/sessions': 'navSessions',
  '/observability': 'navObservability',
  '/system': 'navSystemInfo',
  '/trash': 'navTrash',
  '/data-import': 'navDataImport',
  '/tags': 'navTags',
  '/notes': 'navNotes',
  '/templates': 'navTemplates',
  '/ai-eval': 'navAiEval',
  '/ai-timeline': 'navAiTimeline',
  '/ai-tools': 'navAiTools',
  '/analytics': 'navAnalytics',
  '/org': 'navOrg',
  '/workbench': 'navWorkbench',
  '/workbench/events': 'workbenchMyEvents',
  '/workbench/todos': 'workbenchMyTodos',
  '/workbench/notifications': 'workbenchNotifications',
  '/workbench/org': 'workbenchOrgDir',
}

const DRAWER_WIDTH = 260
const DRAWER_RAIL_WIDTH = 72

export default function AdminLayout() {
  const { t } = useTranslation()
  const navigate = useNavigate()
  const location = useLocation()
  const isAdmin = useIsAdmin()
  const user = useAuthStore((s) => s.user)
  const logout = useAuthStore((s) => s.logout)

  const [rail, setRail] = useState(false)

  const navGroups: NavGroup[] = isAdmin
    ? [
        {
          label: t('navData'),
          items: [
            { name: 'users', to: '/users', icon: GroupOutlinedIcon, label: t('navUsers') },
            { name: 'org', to: '/org', icon: AccountTreeOutlinedIcon, label: t('navOrg') },
            { name: 'events', to: '/events', icon: CalendarMonthOutlinedIcon, label: t('navEvents') },
            { name: 'knowledge', to: '/knowledge', icon: MenuBookOutlinedIcon, label: t('navKnowledge') },
            { name: 'notifications', to: '/notifications', icon: CampaignOutlinedIcon, label: t('navNotifications') },
            { name: 'trash', to: '/trash', icon: DeleteOutlinedIcon, label: t('navTrash') },
            { name: 'data-import', to: '/data-import', icon: FileUploadOutlinedIcon, label: t('navDataImport') },
            { name: 'tags', to: '/tags', icon: StorageOutlinedIcon, label: t('navTags') },
            { name: 'notes', to: '/notes', icon: StorageOutlinedIcon, label: t('navNotes') },
          ],
        },
        {
          label: t('navMonitor'),
          items: [
            { name: 'monitor', to: '/monitor', icon: MonitorHeartOutlinedIcon, label: t('navMonitorCenter') },
            { name: 'audit', to: '/audit', icon: HistoryOutlinedIcon, label: t('navAiAudit') },
            { name: 'op-audit', to: '/op-audit', icon: DescriptionOutlinedIcon, label: t('navOpAudit') },
            { name: 'sessions', to: '/sessions', icon: DevicesOutlinedIcon, label: t('navSessions') },
            { name: 'analytics', to: '/analytics', icon: InsightsOutlinedIcon, label: t('navAnalytics') },
            { name: 'ai-eval', to: '/ai-eval', icon: ScienceOutlinedIcon, label: t('navAiEval') },
            { name: 'ai-timeline', to: '/ai-timeline', icon: TimelineOutlinedIcon, label: t('navAiTimeline') },
          ],
        },
        {
          label: t('navSystem'),
          items: [
            { name: 'observability', to: '/observability', icon: LanOutlinedIcon, label: t('navObservability') },
            { name: 'system', to: '/system', icon: SettingsOutlinedIcon, label: t('navSystemInfo') },
            { name: 'templates', to: '/templates', icon: GridViewOutlinedIcon, label: t('navTemplates') },
            { name: 'ai-tools', to: '/ai-tools', icon: HandymanOutlinedIcon, label: t('navAiTools') },
          ],
        },
      ]
    : [
        {
          label: t('navWorkbench'),
          items: [{ name: 'workbench-home', to: '/workbench', icon: HomeOutlinedIcon, label: t('navWorkbench') }],
        },
        {
          label: t('navMy'),
          items: [
            { name: 'workbench-events', to: '/workbench/events', icon: CalendarMonthOutlinedIcon, label: t('workbenchMyEvents') },
            { name: 'workbench-todos', to: '/workbench/todos', icon: CheckCircleOutlinedIcon, label: t('workbenchMyTodos') },
            { name: 'workbench-notifications', to: '/workbench/notifications', icon: NotificationsOutlinedIcon, label: t('workbenchNotifications') },
            { name: 'workbench-org', to: '/workbench/org', icon: GroupOutlinedIcon, label: t('workbenchOrgDir') },
          ],
        },
      ]

  const isActive = (to: string): boolean => {
    const path = location.pathname
    if (to === '/') return path === '/'
    if (to === '/users') return path === '/users' || path.startsWith('/users/')
    return path === to
  }

  const go = (to: string) => {
    if (rail) setRail(false)
    navigate(to)
  }

  const onLogout = async () => {
    await logout()
    navigate('/login', { replace: true })
  }

  const metaTitleKey = TITLE_BY_PATH[location.pathname]
  const drawerWidth = rail ? DRAWER_RAIL_WIDTH : DRAWER_WIDTH

  return (
    <Box sx={{ display: 'flex', minHeight: '100vh' }}>
      <Drawer
        variant="permanent"
        open
        sx={{
          width: drawerWidth,
          flexShrink: 0,
          '& .MuiDrawer-paper': {
            width: drawerWidth,
            boxSizing: 'border-box',
            overflowX: 'hidden',
            transition: 'width 0.2s ease',
            borderRight: '1px solid',
            borderColor: 'divider',
          },
        }}
      >
        <Box
          sx={{ minHeight: 56, display: 'flex', alignItems: 'center', gap: 1, px: rail ? 1.5 : 2, cursor: 'pointer' }}
          onClick={() => go('/')}
        >
          <Avatar sx={{ bgcolor: 'primary.main', width: 32, height: 32, fontSize: 16, fontWeight: 700 }}>K</Avatar>
          {!rail ? (
            <Box>
              <Typography fontWeight="bold" fontSize={14} lineHeight={1.2}>
                {t('appName')}
              </Typography>
              <Typography variant="caption" color="text.secondary" lineHeight={1.2}>
                KeelBase
              </Typography>
            </Box>
          ) : null}
        </Box>
        <Divider />

        {isAdmin ? (
          <List dense sx={{ px: rail ? 1 : 1.5 }}>
            <ListItemButton selected={isActive('/')} onClick={() => go('/')} sx={{ px: 1.5 }}>
              <ListItemIcon sx={{ minWidth: 36 }}>
                <DashboardOutlinedIcon fontSize="small" />
              </ListItemIcon>
              {!rail ? <ListItemText primary={t('overview')} /> : null}
            </ListItemButton>
          </List>
        ) : null}

        <Box sx={{ flexGrow: 1, overflowY: 'auto' }}>
          {navGroups.map((group) => (
            <Box key={group.label}>
              {!rail ? (
                <Typography
                  variant="caption"
                  color="text.secondary"
                  sx={{
                    display: 'block',
                    px: 2,
                    pt: 1.5,
                    pb: 0.5,
                    textTransform: 'uppercase',
                    fontSize: 11,
                    letterSpacing: 0.5,
                  }}
                >
                  {group.label}
                </Typography>
              ) : null}
              <List dense sx={{ px: rail ? 1 : 1.5 }}>
                {group.items.map((item) => {
                  const Icon = item.icon
                  return (
                    <ListItemButton key={item.to} selected={isActive(item.to)} onClick={() => go(item.to)} sx={{ px: 1.5 }}>
                      <ListItemIcon sx={{ minWidth: 36 }}>
                        <Icon fontSize="small" />
                      </ListItemIcon>
                      {!rail ? <ListItemText primary={item.label} /> : null}
                    </ListItemButton>
                  )
                })}
              </List>
            </Box>
          ))}
        </Box>

        <Box sx={{ px: 2, py: 1.5 }}>
          <Divider sx={{ mb: 1 }} />
          <ListItemButton sx={{ px: 1.5 }}>
            <ListItemIcon sx={{ minWidth: 36 }}>
              <Avatar sx={{ width: 28, height: 28, bgcolor: 'primary.main', fontSize: 13 }}>{user?.username?.[0]?.toUpperCase() ?? '-'}</Avatar>
            </ListItemIcon>
            {!rail ? (
              <ListItemText
                primary={user?.username || '-'}
                secondary={user?.role || ''}
                slotProps={{ primary: { fontSize: 14, fontWeight: 600 }, secondary: { fontSize: 12 } }}
              />
            ) : null}
          </ListItemButton>
          <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', px: 0.5 }}>
            <LangToggle />
            <ThemeToggle />
            <IconButton size="small" title={t('logout')} onClick={onLogout}>
              <LogoutIcon fontSize="small" />
            </IconButton>
          </Box>
        </Box>
      </Drawer>

      <Box component="main" sx={{ flexGrow: 1, display: 'flex', flexDirection: 'column', minWidth: 0, bgcolor: 'background.default' }}>
        <AppBar position="sticky" color="transparent" elevation={0} sx={{ borderBottom: 1, borderColor: 'divider', bgcolor: 'background.default' }}>
          <Toolbar>
            <IconButton onClick={() => setRail((r) => !r)} size="small" sx={{ mr: 1 }}>
              <MenuIcon />
            </IconButton>
            <Breadcrumbs aria-label="breadcrumb">
              <Typography variant="body2" color="text.secondary">
                {t('appName')}
              </Typography>
              {metaTitleKey ? (
                <Typography variant="body2" color="text.primary">
                  {t(metaTitleKey)}
                </Typography>
              ) : null}
            </Breadcrumbs>
            <Box sx={{ flexGrow: 1 }} />
            <ThemeToggle />
            <LangToggle />
            <Button variant="outlined" startIcon={<LogoutIcon />} onClick={onLogout} sx={{ ml: 1 }}>
              {t('logout')}
            </Button>
          </Toolbar>
        </AppBar>
        <Box sx={{ p: 3, flexGrow: 1 }}>
          <Outlet />
        </Box>
      </Box>
    </Box>
  )
}
