// Web-Admin-React/src/views/ai-eval/AiEvalView.tsx
import { useEffect, useState } from 'react'
import { Accordion, AccordionDetails, AccordionSummary, Box, Button, Card, CardContent, CardHeader, Chip, IconButton, TextField, Typography } from '@mui/material'
import AddIcon from '@mui/icons-material/Add'
import LayersOutlinedIcon from '@mui/icons-material/LayersOutlined'
import PlayArrowIcon from '@mui/icons-material/PlayArrow'
import CheckCircleIcon from '@mui/icons-material/CheckCircle'
import CancelIcon from '@mui/icons-material/Cancel'
import ExpandMoreIcon from '@mui/icons-material/ExpandMore'
import DeleteOutlineIcon from '@mui/icons-material/DeleteOutline'
import { useTranslation } from 'react-i18next'
import { PageHeader } from '@/components/PageHeader'
import { AppTable, type AppColumn } from '@/components/AppTable'
import { StatusChip } from '@/components/StatusChip'
import { FormDialog } from '@/components/FormDialog'
import { ConfirmDialog } from '@/components/ConfirmDialog'
import { useSnackbarStore } from '@/stores/snackbar'
import { aiEvalApi } from '@/api/aiEval'
import { formatTime } from '@/utils/format'
import type { EvalCase, EvalRunReport } from '@/types/eval'

export default function AiEvalView() {
  const { t } = useTranslation()
  const snackbar = useSnackbarStore()

  const [cases, setCases] = useState<EvalCase[]>([])
  const [report, setReport] = useState<EvalRunReport | null>(null)
  const [loading, setLoading] = useState(false)
  const [running, setRunning] = useState(false)

  const [showCreate, setShowCreate] = useState(false)
  const [saving, setSaving] = useState(false)
  const [form, setForm] = useState({ category: '', prompt: '', expected: '' })

  const [showDelete, setShowDelete] = useState(false)
  const [pendingDelete, setPendingDelete] = useState<EvalCase | null>(null)

  async function load() {
    setLoading(true)
    try {
      const [c, r] = await Promise.all([aiEvalApi.listCases(), aiEvalApi.report()])
      setCases(c)
      setReport(r)
    } catch (err) {
      snackbar.error(err instanceof Error ? err.message : t('loadFailed'))
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    void load()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  function openCreate() {
    setForm({ category: '', prompt: '', expected: '' })
    setShowCreate(true)
  }
  async function onCreate() {
    if (!form.category.trim() || !form.prompt.trim()) return
    setSaving(true)
    try {
      await aiEvalApi.createCase({
        category: form.category.trim(),
        prompt: form.prompt.trim(),
        expected: form.expected || undefined,
      })
      snackbar.success(t('saved'))
      setShowCreate(false)
      void load()
    } catch (err) {
      snackbar.error(err instanceof Error ? err.message : t('createFailed'))
    } finally {
      setSaving(false)
    }
  }

  function confirmDelete(item: EvalCase) {
    setPendingDelete(item)
    setShowDelete(true)
  }
  async function onDelete() {
    if (!pendingDelete) return
    try {
      await aiEvalApi.removeCase(pendingDelete.id)
      snackbar.success(t('deleted'))
      void load()
    } catch (err) {
      snackbar.error(err instanceof Error ? err.message : t('deleteFailed'))
    } finally {
      setShowDelete(false)
    }
  }

  async function onSeed() {
    try {
      const res = await aiEvalApi.seed()
      snackbar.success(t('seedDone', { n: res.added }))
      void load()
    } catch (err) {
      snackbar.error(err instanceof Error ? err.message : t('seedFailed'))
    }
  }

  async function onRun() {
    setRunning(true)
    try {
      setReport(await aiEvalApi.run())
      snackbar.success(t('runDone'))
    } catch (err) {
      snackbar.error(err instanceof Error ? err.message : t('runFailed'))
    } finally {
      setRunning(false)
    }
  }

  const enabledMap = { ok: t('enabled'), cancelled: t('disabled') }
  const headers: AppColumn<EvalCase>[] = [
    { key: 'id', title: t('idCol'), width: 70 },
    { key: 'category', title: t('category') },
    { key: 'prompt', title: t('prompt') },
    { key: 'expected', title: t('expected'), render: (c) => c.expected || '-' },
    { key: 'enabled', title: t('statusCol'), render: (c) => <StatusChip status={c.enabled ? 'ok' : 'cancelled'} labelMap={enabledMap} /> },
    { key: 'createdAt', title: t('createdAt'), render: (c) => formatTime(c.createdAt) },
    {
      key: 'actions',
      title: t('actionCol'),
      render: (c) => (
        <IconButton size="small" color="error" onClick={() => confirmDelete(c)}>
          <DeleteOutlineIcon fontSize="small" />
        </IconButton>
      ),
    },
  ]

  return (
    <Box>
      <PageHeader title={t('navAiEval')}>
        <Button variant="outlined" startIcon={<AddIcon />} onClick={openCreate}>
          {t('newEvalCase')}
        </Button>
        <Button variant="outlined" startIcon={<LayersOutlinedIcon />} onClick={() => void onSeed()}>
          {t('seedCases')}
        </Button>
        <Button color="primary" variant="contained" startIcon={<PlayArrowIcon />} loading={running} onClick={() => void onRun()}>
          {t('runEval')}
        </Button>
      </PageHeader>

      {report ? (
        <Box sx={{ mb: 3 }}>
          <Card>
            <CardHeader
              title={
                <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                  {t('lastReport')}
                  <Chip size="small" color="success" variant="outlined" label={t('passed', { n: report.passed })} />
                  <Chip size="small" color="error" variant="outlined" label={t('failed', { n: report.failed })} />
                  <Chip size="small" variant="outlined" label={t('total')} />
                </Box>
              }
            />
            <CardContent>
              {report.cases.map((c) => (
                <Accordion key={c.id}>
                  <AccordionSummary expandIcon={<ExpandMoreIcon />} sx={{ alignItems: 'center' }}>
                    {c.ok ? <CheckCircleIcon color="success" fontSize="small" /> : <CancelIcon color="error" fontSize="small" />}
                    <Typography variant="body2" sx={{ ml: 1 }}>
                      {c.category} / {c.prompt}
                    </Typography>
                  </AccordionSummary>
                  <AccordionDetails>
                    <Typography variant="body2">
                      {t('assertType')}: {c.assertType}
                    </Typography>
                    <Typography variant="body2">
                      {t('detail')}: {c.detail}
                    </Typography>
                    {c.actualToolCalls?.length ? (
                      <Typography variant="body2">
                        {t('actualToolCalls')}: {c.actualToolCalls.join(', ')}
                      </Typography>
                    ) : null}
                    {c.replyPreview ? (
                      <Typography variant="body2">
                        {t('replyPreview')}: {c.replyPreview}
                      </Typography>
                    ) : null}
                    {c.error ? (
                      <Typography variant="body2" color="error">
                        {t('error')}: {c.error}
                      </Typography>
                    ) : null}
                    <Typography variant="caption" color="text.secondary">
                      {c.durationMs}ms
                    </Typography>
                  </AccordionDetails>
                </Accordion>
              ))}
            </CardContent>
          </Card>
        </Box>
      ) : null}

      <AppTable headers={headers} items={cases} loading={loading} emptyText={t('noTrend')} />

      <FormDialog open={showCreate} title={t('newEvalCase')} loading={saving} onClose={() => setShowCreate(false)} onSave={() => void onCreate()}>
        <Box component="form" onSubmit={(e) => { e.preventDefault(); void onCreate() }}>
          <TextField label={t('category')} required fullWidth margin="dense" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} />
          <TextField label={t('prompt')} multiline rows={3} required fullWidth margin="dense" value={form.prompt} onChange={(e) => setForm({ ...form, prompt: e.target.value })} />
          <TextField label={t('expected')} fullWidth margin="dense" value={form.expected} onChange={(e) => setForm({ ...form, expected: e.target.value })} />
        </Box>
      </FormDialog>

      <ConfirmDialog
        open={showDelete}
        title={t('deleteEvalCase')}
        content={t('deleteEvalCaseConfirm', { id: pendingDelete?.id || '' })}
        onClose={() => setShowDelete(false)}
        onConfirm={() => void onDelete()}
      />
    </Box>
  )
}

// Web-Admin/src/views/ai-eval/AiEvalView.vue
<template>
  <div>
    <PageHeader :title="t('navAiEval')">
      <v-btn variant="tonal" prepend-icon="mdi-plus" @click="openCreate">{{ t('newEvalCase') }}</v-btn>
      <v-btn variant="tonal" prepend-icon="mdi-seed" @click="onSeed">{{ t('seedCases') }}</v-btn>
      <v-btn color="primary" prepend-icon="mdi-play" :loading="running" @click="onRun">{{ t('runEval') }}</v-btn>
    </PageHeader>

    <!-- 最近报告 -->
    <v-card v-if="report" class="mb-4">
      <v-card-title class="d-flex align-center ga-2">
        <v-icon icon="mdi-chart-box" color="primary" />
        {{ t('lastReport') }}
        <v-chip size="small" color="success" variant="tonal">{{ t('passed', { n: report.passed }) }}</v-chip>
        <v-chip size="small" color="error" variant="tonal">{{ t('failed', { n: report.failed }) }}</v-chip>
        <v-chip size="small" variant="tonal">{{ t('total') }} {{ report.total }}</v-chip>
      </v-card-title>
      <v-card-text>
        <v-expansion-panels variant="accordion">
          <v-expansion-panel v-for="c in report.cases" :key="c.id">
            <v-expansion-panel-title class="d-flex align-center ga-2">
              <v-icon :icon="c.ok ? 'mdi-check-circle' : 'mdi-close-circle'" :color="c.ok ? 'success' : 'error'" />
              <span class="text-body-2">{{ c.category }} / {{ c.prompt }}</span>
            </v-expansion-panel-title>
            <v-expansion-panel-text>
              <div class="text-body-2">{{ t('assertType') }}: {{ c.assertType }}</div>
              <div class="text-body-2">{{ t('detail') }}: {{ c.detail }}</div>
              <div v-if="c.actualToolCalls?.length" class="text-body-2">{{ t('actualToolCalls') }}: {{ c.actualToolCalls.join(', ') }}</div>
              <div v-if="c.replyPreview" class="text-body-2">{{ t('replyPreview') }}: {{ c.replyPreview }}</div>
              <div v-if="c.error" class="text-body-2 text-error">{{ t('error') }}: {{ c.error }}</div>
              <div class="text-caption text-medium-emphasis">{{ c.durationMs }}ms</div>
            </v-expansion-panel-text>
          </v-expansion-panel>
        </v-expansion-panels>
      </v-card-text>
    </v-card>

    <AppTable :headers="headers" :items="cases" :loading="loading" :total="cases.length" :items-per-page="cases.length || 1">
      <template #item.enabled="{ item }">
        <StatusChip :status="item.enabled ? 'ok' : 'cancelled'" :label-map="enabledMap" />
      </template>
      <template #item.expected="{ item }">{{ item.expected || '-' }}</template>
      <template #item.createdAt="{ item }">{{ formatTime(item.createdAt) }}</template>
      <template #item.actions="{ item }">
        <v-btn icon="mdi-delete-outline" variant="text" size="small" color="error" @click="confirmDelete(item)" />
      </template>
    </AppTable>

    <FormDialog v-model="showCreate" :title="t('newEvalCase')" :loading="saving" @save="onCreate">
      <v-form @submit.prevent="onCreate">
        <v-text-field v-model="form.category" :label="t('category')" required />
        <v-textarea v-model="form.prompt" :label="t('prompt')" rows="3" required />
        <v-text-field v-model="form.expected" :label="t('expected')" />
      </v-form>
    </FormDialog>

    <ConfirmDialog
      v-model="showDelete"
      :title="t('deleteEvalCase')"
      :content="t('deleteEvalCaseConfirm', { id: pendingDelete?.id || '' })"
      @confirm="onDelete"
    />
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import PageHeader from '@/components/PageHeader.vue'
import AppTable from '@/components/AppTable.vue'
import StatusChip from '@/components/StatusChip.vue'
import FormDialog from '@/components/FormDialog.vue'
import ConfirmDialog from '@/components/ConfirmDialog.vue'
import { useSnackbarStore } from '@/stores/snackbar'
import { aiEvalApi } from '@/api/aiEval'
import { formatTime } from '@/utils/format'
import type { EvalCase, EvalRunReport } from '@/types/eval'

const { t } = useI18n()
const snackbar = useSnackbarStore()

const cases = ref<EvalCase[]>([])
const report = ref<EvalRunReport | null>(null)
const loading = ref(false)
const running = ref(false)

const headers = computed(() => [
  { key: 'id', title: t('idCol') },
  { key: 'category', title: t('category') },
  { key: 'prompt', title: t('prompt') },
  { key: 'expected', title: t('expected') },
  { key: 'enabled', title: t('statusCol') },
  { key: 'createdAt', title: t('createdAt') },
  { key: 'actions', title: t('actionCol') },
])

const enabledMap = computed(() => ({ ok: t('enabled'), cancelled: t('disabled') }))

async function load() {
  loading.value = true
  try {
    const [c, r] = await Promise.all([aiEvalApi.listCases(), aiEvalApi.report()])
    cases.value = c
    report.value = r
  } catch (err) {
    snackbar.error(err instanceof Error ? err.message : t('loadFailed'))
  } finally {
    loading.value = false
  }
}

// 新建
const showCreate = ref(false)
const saving = ref(false)
const form = ref({ category: '', prompt: '', expected: '' })
function openCreate() {
  form.value = { category: '', prompt: '', expected: '' }
  showCreate.value = true
}
async function onCreate() {
  if (!form.value.category.trim() || !form.value.prompt.trim()) return
  saving.value = true
  try {
    await aiEvalApi.createCase({
      category: form.value.category.trim(),
      prompt: form.value.prompt.trim(),
      expected: form.value.expected || undefined,
    })
    snackbar.success(t('saved'))
    showCreate.value = false
    load()
  } catch (err) {
    snackbar.error(err instanceof Error ? err.message : t('createFailed'))
  } finally {
    saving.value = false
  }
}

// 删除
const showDelete = ref(false)
const pendingDelete = ref<EvalCase | null>(null)
function confirmDelete(item: EvalCase) {
  pendingDelete.value = item
  showDelete.value = true
}
async function onDelete() {
  if (!pendingDelete.value) return
  try {
    await aiEvalApi.removeCase(pendingDelete.value.id)
    snackbar.success(t('deleted'))
    load()
  } catch (err) {
    snackbar.error(err instanceof Error ? err.message : t('deleteFailed'))
  } finally {
    showDelete.value = false
  }
}

async function onSeed() {
  try {
    const res = await aiEvalApi.seed()
    snackbar.success(t('seedDone', { n: res.added }))
    load()
  } catch (err) {
    snackbar.error(err instanceof Error ? err.message : t('seedFailed'))
  }
}

async function onRun() {
  running.value = true
  try {
    report.value = await aiEvalApi.run()
    snackbar.success(t('runDone'))
  } catch (err) {
    snackbar.error(err instanceof Error ? err.message : t('runFailed'))
  } finally {
    running.value = false
  }
}

onMounted(load)
</script>
