// Web-Admin-Vue/src/views/trash/TrashView.vue
<!-- SPDX-License-Identifier: Apache-2.0 -->
<template>
  <div>
    <PageHeader :title="t('navTrash')" :subtitle="t('total', { n: total })">
      <el-button @click="load(1)">
        <template #icon><AppIcon icon="mdi-refresh" /></template>
        {{ t('refresh') }}
      </el-button>
    </PageHeader>

    <AppTable :headers="headers" :items="trash" :loading="loading" :total="total" :items-per-page="limit">
      <template #item.type="{ item }">
        <StatusChip :status="item.type" :label-map="typeLabelMap" />
      </template>
      <template #item.deletedAt="{ item }">{{ formatTime(item.deletedAt) }}</template>
      <template #item.actions="{ item }">
        <el-button text size="small" type="primary" :title="t('restore')" @click="confirmRestore(item)">
          <AppIcon icon="mdi-restore" />
        </el-button>
      </template>
    </AppTable>

    <AppPagination :page="page" :limit="limit" :total="total" :loading="loading" @update:page="load" />

    <ConfirmDialog
      v-model="showRestore"
      :title="t('restore')"
      :content="t('restoreConfirm', { title: pending?.title || '' })"
      color="primary"
      @confirm="onRestore"
    />
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import PageHeader from '@/components/PageHeader.vue'
import AppTable from '@/components/AppTable.vue'
import AppPagination from '@/components/AppPagination.vue'
import StatusChip from '@/components/StatusChip.vue'
import ConfirmDialog from '@/components/ConfirmDialog.vue'
import { useSnackbarStore } from '@/stores/snackbar'
import { adminApi } from '@/api/admin'
import { formatTime } from '@/utils/format'
import type { TrashItem } from '@/types/admin'

const { t } = useI18n()
const snackbar = useSnackbarStore()

const trash = ref<TrashItem[]>([])
const total = ref(0)
const page = ref(1)
const limit = 20
const loading = ref(false)

const headers = computed(() => [
  { key: 'type', title: t('typeLabel') },
  { key: 'title', title: t('titleLabel') },
  { key: 'username', title: t('userCol') },
  { key: 'deletedAt', title: t('deletedAt') },
  { key: 'actions', title: t('actionCol') },
])

const typeLabelMap = computed(() => ({ event: t('events'), todo: t('todos') }))

async function load(p = 1) {
  loading.value = true
  try {
    const res = await adminApi.trash(p, limit)
    trash.value = res.items
    total.value = res.total
    page.value = p
  } catch (err) {
    snackbar.error(err instanceof Error ? err.message : t('loadFailed'))
  } finally {
    loading.value = false
  }
}

const showRestore = ref(false)
const pending = ref<TrashItem | null>(null)
function confirmRestore(item: TrashItem) {
  pending.value = item
  showRestore.value = true
}
async function onRestore() {
  if (!pending.value) return
  try {
    await adminApi.restoreTrash(pending.value.type, pending.value.id)
    snackbar.success(t('restored'))
    load(page.value)
  } catch (err) {
    snackbar.error(err instanceof Error ? err.message : t('restoreFailed'))
  } finally {
    showRestore.value = false
  }
}

onMounted(() => load(1))
</script>

// Web-Admin-React/src/views/trash/TrashView.tsx
// SPDX-License-Identifier: Apache-2.0

import { useEffect, useState } from 'react'
import { Box, Button, IconButton } from '@mui/material'
import RefreshIcon from '@mui/icons-material/Refresh'
import RestoreIcon from '@mui/icons-material/Restore'
import { useTranslation } from 'react-i18next'
import { PageHeader } from '@/components/PageHeader'
import { AppTable, type AppColumn } from '@/components/AppTable'
import { AppPagination } from '@/components/AppPagination'
import { StatusChip } from '@/components/StatusChip'
import { ConfirmDialog } from '@/components/ConfirmDialog'
import { useSnackbarStore } from '@/stores/snackbar'
import { adminApi } from '@/api/admin'
import { formatTime } from '@/utils/format'
import type { TrashItem } from '@/types/admin'

const LIMIT = 20

export default function TrashView() {
  const { t } = useTranslation()
  const snackbar = useSnackbarStore()

  const [trash, setTrash] = useState<TrashItem[]>([])
  const [total, setTotal] = useState(0)
  const [page, setPage] = useState(1)
  const [loading, setLoading] = useState(false)
  const [showRestore, setShowRestore] = useState(false)
  const [pending, setPending] = useState<TrashItem | null>(null)

  async function load(p = 1) {
    setLoading(true)
    try {
      const res = await adminApi.trash(p, LIMIT)
      setTrash(res.items)
      setTotal(res.total)
      setPage(p)
    } catch (err) {
      snackbar.error(err instanceof Error ? err.message : t('loadFailed'))
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    void load(1)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  function confirmRestore(item: TrashItem) {
    setPending(item)
    setShowRestore(true)
  }

  async function onRestore() {
    if (!pending) return
    try {
      await adminApi.restoreTrash(pending.type, pending.id)
      snackbar.success(t('restored'))
      void load(page)
    } catch (err) {
      snackbar.error(err instanceof Error ? err.message : t('restoreFailed'))
    } finally {
      setShowRestore(false)
    }
  }

  const typeLabelMap = { event: t('events'), todo: t('todos') }
  const headers: AppColumn<TrashItem>[] = [
    { key: 'type', title: t('typeLabel'), render: (i) => <StatusChip status={i.type} labelMap={typeLabelMap} /> },
    { key: 'title', title: t('titleLabel') },
    { key: 'username', title: t('userCol'), render: (i) => i.username || '-' },
    { key: 'deletedAt', title: t('deletedAt'), render: (i) => formatTime(i.deletedAt) },
    {
      key: 'actions',
      title: t('actionCol'),
      render: (i) => (
        <IconButton size="small" color="primary" title={t('restore')} onClick={() => confirmRestore(i)}>
          <RestoreIcon />
        </IconButton>
      ),
    },
  ]

  return (
    <Box>
      <PageHeader title={t('navTrash')} subtitle={t('total', { n: total })}>
        <Button variant="outlined" startIcon={<RefreshIcon />} onClick={() => void load(1)}>
          {t('refresh')}
        </Button>
      </PageHeader>
      <AppTable headers={headers} items={trash} loading={loading} />
      <AppPagination page={page} limit={LIMIT} total={total} loading={loading} onChange={(p) => void load(p)} />
      <ConfirmDialog
        open={showRestore}
        title={t('restore')}
        content={t('restoreConfirm', { title: pending?.title || '' })}
        color="primary"
        onClose={() => setShowRestore(false)}
        onConfirm={() => void onRestore()}
      />
    </Box>
  )
}
