// Web-Admin-React/src/components/AppPagination.tsx
import { Box, IconButton, Typography } from '@mui/material'
import ChevronLeftIcon from '@mui/icons-material/ChevronLeft'
import ChevronRightIcon from '@mui/icons-material/ChevronRight'
import { useTranslation } from 'react-i18next'

interface AppPaginationProps {
  page: number
  limit: number
  total: number
  loading?: boolean
  onChange: (page: number) => void
}

export function AppPagination({ page, limit, total, loading, onChange }: AppPaginationProps) {
  const { t } = useTranslation()
  const pages = total ? Math.max(1, Math.ceil(total / limit)) : 1
  return (
    <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'flex-end', gap: 1, py: 1.5, px: 2 }}>
      <Typography variant="caption" color="text.secondary">
        {t('total', { n: total })}
      </Typography>
      <IconButton size="small" disabled={page <= 1 || loading} onClick={() => onChange(page - 1)}>
        <ChevronLeftIcon />
      </IconButton>
      <Typography variant="caption">{t('pageInfo', { page, pages })}</Typography>
      <IconButton size="small" disabled={page >= pages || loading} onClick={() => onChange(page + 1)}>
        <ChevronRightIcon />
      </IconButton>
    </Box>
  )
}

// Web-Admin/src/components/AppPagination.vue
<template>
  <div class="d-flex align-center justify-end ga-2 py-2">
    <span class="text-caption text-medium-emphasis">
      {{ t('total', { n: total }) }}
    </span>
    <v-btn
      icon="mdi-chevron-left"
      variant="text"
      size="small"
      :disabled="page <= 1 || loading"
      @click="emit('update:page', page - 1)"
    />
    <span class="text-caption">
      {{ t('pageInfo', { page, pages: pages }) }}
    </span>
    <v-btn
      icon="mdi-chevron-right"
      variant="text"
      size="small"
      :disabled="page >= pages || loading"
      @click="emit('update:page', page + 1)"
    />
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'

const props = defineProps<{
  page: number
  limit: number
  total: number
  loading?: boolean
}>()
const emit = defineEmits<{ (e: 'update:page', page: number): void }>()
const { t } = useI18n()

const pages = computed(() => (props.total ? Math.max(1, Math.ceil(props.total / props.limit)) : 1))
</script>
