// Front-Taro/src/pages/users/index.tsx
 import { useEffect, useRef } from 'react'
 import { View, Text, ScrollView, Button } from '@tarojs/components'
 import Taro from '@tarojs/taro'
 import { useUsersStore } from '../../stores/users-store'
 import './index.scss'
 
 export default function UserListPage() {
   const { users, isLoading, error, hasMore, loadUsers } = useUsersStore()
   const pageLoaded = useRef(false)
 
   useEffect(() => {
     if (!pageLoaded.current) {
       loadUsers(true)
       pageLoaded.current = true
     }
   }, [])
 
   const handleScrollToLower = () => {
     if (!isLoading && hasMore) {
       loadUsers()
     }
   }
 
   return (
     <View className='users-page'>
       {error && users.length === 0 && (
         <View className='users-page__error'>
           <Text className='users-page__error-text'>{error}</Text>
           <Button className='users-page__retry' onClick={() => loadUsers(true)}>
             Retry
           </Button>
         </View>
       )}
 
       {isLoading && users.length === 0 ? (
         <View className='users-page__loading'>
           <View className='spinner' />
         </View>
       ) : (
         <ScrollView
           className='users-page__list'
           scrollY
           onScrollToLower={handleScrollToLower}
           lowerThreshold={200}
         >
           {users.map((user) => (
             <View
               key={user.id}
               className='users-page__item card'
               onClick={() => Taro.navigateTo({ url: `/pages/user-detail/index?id=${user.id}` })}
             >
               <View className='users-page__item-avatar'>
                 <Text className='users-page__item-avatar-text'>
                   {user.nickname?.[0]?.toUpperCase() || '?'}
                 </Text>
               </View>
               <View className='users-page__item-info'>
                 <Text className='users-page__item-name'>{user.nickname}</Text>
                 <Text className='users-page__item-username'>@{user.username}</Text>
               </View>
               <Text className='users-page__item-arrow'>›</Text>
             </View>
           ))}
           {isLoading && hasMore && (
             <View className='users-page__list-loading'>
               <View className='spinner' />
             </View>
           )}
         </ScrollView>
       )}
     </View>
   )
 }

// Front-Taro/src/pages/users/index.vue
<template>
  <view class="users-page">
    <view v-if="error && users.length === 0" class="users-page__error">
      <text class="users-page__error-text">{{ error }}</text>
      <button class="users-page__retry" @click="store.loadUsers(true)">Retry</button>
    </view>

    <view v-if="isLoading && users.length === 0" class="users-page__loading">
      <view class="spinner" />
    </view>
    <scroll-view
      v-else
      class="users-page__list"
      scroll-y
      :lower-threshold="200"
      @scrolltolower="handleScrollToLower"
    >
      <view
        v-for="user in users"
        :key="user.id"
        class="users-page__item card"
        @click="goToDetail(user.id)"
      >
        <view class="users-page__item-avatar">
          <text class="users-page__item-avatar-text">{{ avatarInitial(user) }}</text>
        </view>
        <view class="users-page__item-info">
          <text class="users-page__item-name">{{ user.nickname }}</text>
          <text class="users-page__item-username">@{{ user.username }}</text>
        </view>
        <text class="users-page__item-arrow">›</text>
      </view>
      <view v-if="isLoading && hasMore" class="users-page__list-loading">
        <view class="spinner" />
      </view>
    </scroll-view>
  </view>
</template>

<script setup lang="ts">
import Taro from '@tarojs/taro'
import { onMounted } from 'vue'
import { storeToRefs } from 'pinia'
import { useUsersStore } from '../../stores/users-store'
import type { UserItem } from '../../types/user'

const store = useUsersStore()
const { users, isLoading, error, hasMore } = storeToRefs(store)

onMounted(() => {
  store.loadUsers(true)
})

const handleScrollToLower = () => {
  if (!isLoading.value && hasMore.value) {
    store.loadUsers()
  }
}

function avatarInitial(user: UserItem) {
  return user.nickname?.[0]?.toUpperCase() || '?'
}

function goToDetail(id: number) {
  Taro.navigateTo({ url: `/pages/user-detail/index?id=${id}` })
}
</script>

<style src="./index.scss" scoped></style>
