// Web-Admin-Vue/src/views/workbench/MyNotificationsView.vue
<!-- SPDX-License-Identifier: Apache-2.0 -->
<template>
  <div>
    <PageHeader :title="t('workbenchNotifications')">
      <el-button plain @click="onReadAll">
        <template #icon><AppIcon icon="mdi-check-all" /></template>
        {{ t('markAllRead') }}
      </el-button>
    </PageHeader>

    <el-row :gutter="16" class="mb-4">
      <el-col :xs="24" :sm="12" :md="6">
        <StatCard :label="t('unreadCount')" :value="unread" icon="mdi-bell-badge-outline" color="warning" />
      </el-col>
    </el-row>

    <AppTable :headers="headers" :items="notifications" :loading="loading" :total="total" :items-per-page="limit">
      <template #item.title="{ item }">
        <div>{{ item.title }}</div>
        <div v-if="item.body" class="text-caption text-medium-emphasis">{{ item.body }}</div>
      </template>
      <template #item.type="{ item }">{{ item.type }}</template>
      <template #item.isRead="{ item }">
        <StatusChip :status="item.isRead ? 'read' : 'unread'" />
      </template>
      <template #item.createdAt="{ item }">{{ formatTime(item.createdAt) }}</template>
      <template #item.actions="{ item }">
        <el-button
          v-if="!item.isRead"
          text
          size="small"
          :title="t('markRead')"
          @click="markRead(item)"
        >
          <AppIcon icon="mdi-email-open-outline" />
        </el-button>
        <el-button text size="small" type="danger" @click="confirmDelete(item)">
          <AppIcon icon="mdi-delete-outline" />
        </el-button>
      </template>
    </AppTable>

    <AppPagination :page="page" :limit="limit" :total="total" :loading="loading" @update:page="load" />

    <ConfirmDialog
      v-model="showDelete"
      :title="t('deleteNotificationTitle')"
      :content="t('deleteNotificationContent', { title: pendingDelete?.title || '' })"
      @confirm="onDelete"
    />
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import PageHeader from '@/components/PageHeader.vue'
import AppTable from '@/components/AppTable.vue'
import AppPagination from '@/components/AppPagination.vue'
import ConfirmDialog from '@/components/ConfirmDialog.vue'
import StatCard from '@/components/StatCard.vue'
import StatusChip from '@/components/StatusChip.vue'
import { useSnackbarStore } from '@/stores/snackbar'
import { workbenchApi } from '@/api/workbench'
import { isEmailNotVerified } from '@/api/client'
import { connectRealtime, onRealtimeMessage } from '@/api/ws'
import { formatTime } from '@/utils/format'
import type { MyNotification } from '@/types/workbench'

const { t } = useI18n()
const snackbar = useSnackbarStore()

const notifications = ref<MyNotification[]>([])
const total = ref(0)
const page = ref(1)
const limit = 20
const loading = ref(false)
const unread = ref(0)

const headers = computed(() => [
  { key: 'title', title: t('titleLabel') },
  { key: 'type', title: t('typeLabel') },
  { key: 'isRead', title: t('read') },
  { key: 'createdAt', title: t('createdAt') },
  { key: 'actions', title: t('actionCol') },
])

async function load(p = 1) {
  loading.value = true
  try {
    const [res, count] = await Promise.all([workbenchApi.notifications(p, limit), workbenchApi.unreadCount()])
    notifications.value = res.items
    total.value = res.total
    page.value = p
    unread.value = count.count
  } catch (err) {
    snackbar.error(err instanceof Error ? err.message : t('loadFailed'))
  } finally {
    loading.value = false
  }
}

async function refresh() {
  load(page.value)
}

// 标为已读
async function markRead(item: MyNotification) {
  try {
    await workbenchApi.readNotification(item.id)
    refresh()
  } catch (err) {
    if (isEmailNotVerified(err)) snackbar.warning(t('emailNotVerifiedHint'))
    else snackbar.error(err instanceof Error ? err.message : t('updateFailed'))
  }
}

// 全部已读
async function onReadAll() {
  try {
    await workbenchApi.readAllNotifications()
    snackbar.success(t('markAllReadDone'))
    refresh()
  } catch (err) {
    if (isEmailNotVerified(err)) snackbar.warning(t('emailNotVerifiedHint'))
    else snackbar.error(err instanceof Error ? err.message : t('updateFailed'))
  }
}

// 删除
const showDelete = ref(false)
const pendingDelete = ref<MyNotification | null>(null)
function confirmDelete(n: MyNotification) {
  pendingDelete.value = n
  showDelete.value = true
}
async function onDelete() {
  if (!pendingDelete.value) return
  try {
    await workbenchApi.removeNotification(pendingDelete.value.id)
    snackbar.success(t('deleted'))
    refresh()
  } catch (err) {
    if (isEmailNotVerified(err)) snackbar.warning(t('emailNotVerifiedHint'))
    else snackbar.error(err instanceof Error ? err.message : t('deleteFailed'))
  } finally {
    showDelete.value = false
  }
}

// RG-6：连接 WS 实时通道，新通知实时插入列表（REST 轮询保留为降级）
onMounted(() => {
  load(1)
  connectRealtime()
  onRealtimeMessage((msg) => {
    if (msg.event !== 'notification') return
    const n = msg.data as MyNotification
    notifications.value = [n, ...notifications.value]
    total.value += 1
    if (!n.isRead) unread.value += 1
  })
})
</script>

// Web-Admin-React/src/views/workbench/MyNotificationsView.tsx
// SPDX-License-Identifier: Apache-2.0

import { useEffect, useState } from 'react'
import { Box, Button, Grid, IconButton, Typography } from '@mui/material'
import DoneAllIcon from '@mui/icons-material/DoneAll'
import NotificationsActiveOutlinedIcon from '@mui/icons-material/NotificationsActiveOutlined'
import MarkEmailReadOutlinedIcon from '@mui/icons-material/MarkEmailReadOutlined'
import DeleteOutlineIcon from '@mui/icons-material/DeleteOutline'
import { useTranslation } from 'react-i18next'
import { PageHeader } from '@/components/PageHeader'
import { AppTable, type AppColumn } from '@/components/AppTable'
import { AppPagination } from '@/components/AppPagination'
import { ConfirmDialog } from '@/components/ConfirmDialog'
import { StatCard } from '@/components/StatCard'
import { StatusChip } from '@/components/StatusChip'
import { useSnackbarStore } from '@/stores/snackbar'
import { workbenchApi } from '@/api/workbench'
import { isEmailNotVerified } from '@/api/client'
import { connectRealtime, onRealtimeMessage } from '@/api/ws'
import { formatTime } from '@/utils/format'
import type { MyNotification } from '@/types/workbench'

const LIMIT = 20

export default function MyNotificationsView() {
  const { t } = useTranslation()
  const snackbar = useSnackbarStore()

  const [notifications, setNotifications] = useState<MyNotification[]>([])
  const [total, setTotal] = useState(0)
  const [page, setPage] = useState(1)
  const [loading, setLoading] = useState(false)
  const [unread, setUnread] = useState(0)
  const [showDelete, setShowDelete] = useState(false)
  const [pendingDelete, setPendingDelete] = useState<MyNotification | null>(null)

  async function load(p = 1) {
    setLoading(true)
    try {
      const [res, count] = await Promise.all([workbenchApi.notifications(p, LIMIT), workbenchApi.unreadCount()])
      setNotifications(res.items)
      setTotal(res.total)
      setPage(p)
      setUnread(count.count)
    } catch (err) {
      snackbar.error(err instanceof Error ? err.message : t('loadFailed'))
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    void load(1)
    // RG-6：连接 WS 实时通道，新通知实时插入列表（REST 轮询保留为降级）
    connectRealtime()
    const off = onRealtimeMessage((msg) => {
      if (msg.event !== 'notification') return
      const n = msg.data as MyNotification
      setNotifications((prev) => [n, ...prev])
      setTotal((prev) => prev + 1)
      if (!n.isRead) setUnread((prev) => prev + 1)
    })
    return () => {
      off()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  async function refresh() {
    void load(page)
  }

  async function markRead(item: MyNotification) {
    try {
      await workbenchApi.readNotification(item.id)
      await refresh()
    } catch (err) {
      if (isEmailNotVerified(err)) snackbar.warning(t('emailNotVerifiedHint'))
      else snackbar.error(err instanceof Error ? err.message : t('updateFailed'))
    }
  }

  async function onReadAll() {
    try {
      await workbenchApi.readAllNotifications()
      snackbar.success(t('markAllReadDone'))
      await refresh()
    } catch (err) {
      if (isEmailNotVerified(err)) snackbar.warning(t('emailNotVerifiedHint'))
      else snackbar.error(err instanceof Error ? err.message : t('updateFailed'))
    }
  }

  function confirmDelete(n: MyNotification) {
    setPendingDelete(n)
    setShowDelete(true)
  }
  async function onDelete() {
    if (!pendingDelete) return
    try {
      await workbenchApi.removeNotification(pendingDelete.id)
      snackbar.success(t('deleted'))
      await refresh()
    } catch (err) {
      if (isEmailNotVerified(err)) snackbar.warning(t('emailNotVerifiedHint'))
      else snackbar.error(err instanceof Error ? err.message : t('deleteFailed'))
    } finally {
      setShowDelete(false)
    }
  }

  const headers: AppColumn<MyNotification>[] = [
    {
      key: 'title',
      title: t('titleLabel'),
      render: (n) => (
        <Box>
          <div>{n.title}</div>
          {n.body ? (
            <Typography variant="caption" color="text.secondary">
              {n.body}
            </Typography>
          ) : null}
        </Box>
      ),
    },
    { key: 'type', title: t('typeLabel'), render: (n) => n.type },
    { key: 'isRead', title: t('read'), render: (n) => <StatusChip status={n.isRead ? 'read' : 'unread'} /> },
    { key: 'createdAt', title: t('createdAt'), render: (n) => formatTime(n.createdAt) },
    {
      key: 'actions',
      title: t('actionCol'),
      render: (n) => (
        <>
          {!n.isRead ? (
            <IconButton size="small" title={t('markRead')} onClick={() => void markRead(n)}>
              <MarkEmailReadOutlinedIcon fontSize="small" />
            </IconButton>
          ) : null}
          <IconButton size="small" color="error" onClick={() => confirmDelete(n)}>
            <DeleteOutlineIcon fontSize="small" />
          </IconButton>
        </>
      ),
    },
  ]

  return (
    <Box>
      <PageHeader title={t('workbenchNotifications')}>
        <Button variant="outlined" startIcon={<DoneAllIcon />} onClick={() => void onReadAll()}>
          {t('markAllRead')}
        </Button>
      </PageHeader>

      <Grid container spacing={2} sx={{ mb: 3 }}>
        <Grid item xs={12} sm={6} md={3}>
          <StatCard label={t('unreadCount')} value={unread} icon={<NotificationsActiveOutlinedIcon />} color="warning" />
        </Grid>
      </Grid>

      <AppTable headers={headers} items={notifications} loading={loading} emptyText={t('noNotifications')} />
      <AppPagination page={page} limit={LIMIT} total={total} loading={loading} onChange={(p) => void load(p)} />

      <ConfirmDialog
        open={showDelete}
        title={t('deleteNotificationTitle')}
        content={t('deleteNotificationContent', { title: pendingDelete?.title || '' })}
        onClose={() => setShowDelete(false)}
        onConfirm={() => void onDelete()}
      />
    </Box>
  )
}
