// Front-Taro/src/pages/user-detail/index.vue
<template>
  <view class="user-detail">
    <view v-if="loading" class="user-detail__loading">
      <view class="spinner" />
    </view>

    <view v-else-if="!user" class="user-detail__not-found">
      <text>User not found</text>
    </view>

    <template v-else>
      <view class="user-detail__header">
        <view class="user-detail__avatar">
          <text class="user-detail__avatar-text">{{ avatarInitial }}</text>
        </view>
        <text class="user-detail__name">{{ user.nickname }}</text>
        <text class="user-detail__username">@{{ user.username }}</text>
      </view>

      <view class="user-detail__info card">
        <view v-for="row in infoRows" :key="row.label" class="info-row">
          <text class="info-row__label">{{ row.label }}</text>
          <text class="info-row__value">{{ row.value }}</text>
        </view>
        <view v-if="user.isLocked" class="user-detail__locked">
          <text>🔒 Account is locked</text>
        </view>
      </view>
    </template>
  </view>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import Taro from '@tarojs/taro'
import { usersService } from '../../services/users-service'
import type { UserItem } from '../../types/user'
import { formatDateTime } from '../../utils/format'

const router = Taro.getCurrentInstance().router
const userId = Number(router?.params?.id || 0)
const user = ref<UserItem | null>(null)
const loading = ref(true)

const avatarInitial = computed(() => user.value?.nickname?.[0]?.toUpperCase() || '?')

const infoRows = computed(() => {
  const u = user.value
  if (!u) return []
  const rows: { label: string; value: string }[] = [
    { label: 'ID', value: String(u.id) },
    { label: 'Username', value: u.username },
    { label: 'Nickname', value: u.nickname },
  ]
  if (u.createdAt) rows.push({ label: 'Created', value: formatDateTime(u.createdAt) })
  if (u.updatedAt) rows.push({ label: 'Updated', value: formatDateTime(u.updatedAt) })
  return rows
})

onMounted(() => {
  if (userId) {
    usersService
      .getUser(userId)
      .then((data) => {
        user.value = data
      })
      .catch(() => {})
      .finally(() => {
        loading.value = false
      })
  } else {
    loading.value = false
  }
})
</script>

<style src="./index.scss" scoped></style>

// Front-Taro/src/pages/user-detail/index.tsx
 import { useEffect, useState } from 'react'
 import { View, Text } from '@tarojs/components'
 import Taro from '@tarojs/taro'
 import { usersService } from '../../services/users-service'
 import type { UserItem } from '../../types/user'
 import { formatDateTime } from '../../utils/format'
 import './index.scss'
 
 export default function UserDetailPage() {
   const router = Taro.getCurrentInstance().router
   const userId = Number(router?.params?.id || 0)
   const [user, setUser] = useState<UserItem | null>(null)
   const [loading, setLoading] = useState(true)
 
   useEffect(() => {
     if (userId) {
       usersService
         .getUser(userId)
         .then(setUser)
         .catch(() => {})
         .finally(() => setLoading(false))
     }
   }, [userId])
 
   if (loading) {
     return (
       <View className='user-detail'>
         <View className='user-detail__loading'>
           <View className='spinner' />
         </View>
       </View>
     )
   }
 
   if (!user) {
     return (
       <View className='user-detail'>
         <View className='user-detail__not-found'>
           <Text>User not found</Text>
         </View>
       </View>
     )
   }
 
   return (
     <View className='user-detail'>
       <View className='user-detail__header'>
         <View className='user-detail__avatar'>
           <Text className='user-detail__avatar-text'>
             {user.nickname?.[0]?.toUpperCase() || '?'}
           </Text>
         </View>
         <Text className='user-detail__name'>{user.nickname}</Text>
         <Text className='user-detail__username'>@{user.username}</Text>
       </View>
 
       <View className='user-detail__info card'>
         <InfoRow label='ID' value={String(user.id)} />
         <InfoRow label='Username' value={user.username} />
         <InfoRow label='Nickname' value={user.nickname} />
         {user.createdAt && <InfoRow label='Created' value={formatDateTime(user.createdAt)} />}
         {user.updatedAt && <InfoRow label='Updated' value={formatDateTime(user.updatedAt)} />}
         {user.isLocked && (
           <View className='user-detail__locked'>
             <Text>🔒 Account is locked</Text>
           </View>
         )}
       </View>
     </View>
   )
 }
 
 function InfoRow({ label, value }: { label: string; value: string }) {
   return (
     <View className='info-row'>
       <Text className='info-row__label'>{label}</Text>
       <Text className='info-row__value'>{value}</Text>
     </View>
   )
 }
