// Web-Admin-React/src/views/observability/ObservabilityView.tsx
// SPDX-License-Identifier: Apache-2.0

import { Alert, Box, Card, CardContent, Grid, Typography } from '@mui/material'
import InsertChartOutlinedIcon from '@mui/icons-material/InsertChartOutlined'
import LocalFireDepartmentIcon from '@mui/icons-material/LocalFireDepartment'
import AccountTreeOutlinedIcon from '@mui/icons-material/AccountTreeOutlined'
import StorageOutlinedIcon from '@mui/icons-material/StorageOutlined'
import { useTranslation } from 'react-i18next'
import { PageHeader } from '@/components/PageHeader'
import { OBSERVABILITY_URLS } from '@/utils/constants'

const systems = [
  { key: 'grafana', label: 'Grafana', icon: <InsertChartOutlinedIcon />, color: 'primary' as const, url: OBSERVABILITY_URLS.grafana },
  { key: 'prometheus', label: 'Prometheus', icon: <LocalFireDepartmentIcon />, color: 'error' as const, url: OBSERVABILITY_URLS.prometheus },
  { key: 'jaeger', label: 'Jaeger', icon: <AccountTreeOutlinedIcon />, color: 'success' as const, url: OBSERVABILITY_URLS.jaeger },
  { key: 'loki', label: 'Loki', icon: <StorageOutlinedIcon />, color: 'warning' as const, url: OBSERVABILITY_URLS.loki },
]

export default function ObservabilityView() {
  const { t } = useTranslation()
  return (
    <Box>
      <PageHeader title={t('obsTitle')} />
      <Alert severity="info" variant="outlined" sx={{ mb: 3 }}>
        {t('obsHint')}
      </Alert>
      <Grid container spacing={3}>
        {systems.map((sys) => (
          <Grid key={sys.key}  item  xs={12} sm={6} md={3} >
            <Card sx={{ textAlign: 'center', py: 3, cursor: 'pointer' }} onClick={() => window.open(sys.url, '_blank')}>
              <CardContent>
                <Box color={`${sys.color}.main`} fontSize={42} mb={1} sx={{ display: 'flex', justifyContent: 'center' }}>
                  {sys.icon}
                </Box>
                <Typography variant="h6">{sys.label}</Typography>
                <Typography variant="caption" color="text.secondary">
                  {sys.url}
                </Typography>
              </CardContent>
            </Card>
          </Grid>
        ))}
      </Grid>
    </Box>
  )
}

// Web-Admin-Vue/src/views/observability/ObservabilityView.vue
<!-- SPDX-License-Identifier: Apache-2.0 -->
<template>
  <div>
    <PageHeader :title="t('obsTitle')" />

    <el-alert type="info" :closable="false" class="mb-4">
      {{ t('obsHint') }}
    </el-alert>

    <el-row :gutter="16">
      <el-col v-for="sys in systems" :key="sys.key" :xs="24" :sm="12" :md="6">
        <el-card shadow="hover" class="text-center pa-4 cursor-pointer mb-4" @click="open(sys.url)">
          <AppIcon
            :icon="sys.icon"
            :size="42"
            :color="sys.color === 'error' ? 'var(--el-color-error)' : 'var(--el-color-' + sys.color + ')'"
            class="mb-2"
          />
          <div class="text-h6">{{ sys.label }}</div>
          <div class="text-caption text-medium-emphasis">{{ sys.url }}</div>
        </el-card>
      </el-col>
    </el-row>
  </div>
</template>

<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import PageHeader from '@/components/PageHeader.vue'
import { OBSERVABILITY_URLS } from '@/utils/constants'

const { t } = useI18n()

const systems = [
  { key: 'grafana', label: 'Grafana', icon: 'mdi-chart-box', color: 'primary', url: OBSERVABILITY_URLS.grafana },
  { key: 'prometheus', label: 'Prometheus', icon: 'mdi-fire', color: 'error', url: OBSERVABILITY_URLS.prometheus },
  { key: 'jaeger', label: 'Jaeger', icon: 'mdi-graph-outline', color: 'success', url: OBSERVABILITY_URLS.jaeger },
  { key: 'loki', label: 'Loki', icon: 'mdi-database-eye', color: 'warning', url: OBSERVABILITY_URLS.loki },
]

function open(url: string) {
  window.open(url, '_blank')
}
</script>
