// Web-Admin-React/src/components/FormDialog.tsx
// SPDX-License-Identifier: Apache-2.0

import type { ReactNode } from 'react'
import { Button, Dialog, DialogActions, DialogContent, DialogTitle, Divider, Stack, Typography } from '@mui/material'
import { useTranslation } from 'react-i18next'

interface FormDialogProps {
  open: boolean
  title: string
  icon?: ReactNode
  loading?: boolean
  maxWidth?: number | string
  saveLabel?: string
  onClose: () => void
  onSave: () => void
  children: ReactNode
}

export function FormDialog({
  open,
  title,
  icon,
  loading,
  maxWidth = 560,
  saveLabel,
  onClose,
  onSave,
  children,
}: FormDialogProps) {
  const { t } = useTranslation()
  return (
    <Dialog
      open={open}
      maxWidth={false}
      onClose={(_, reason) => {
        if (reason !== 'backdropClick') onClose()
      }}
      PaperProps={{ sx: { width: maxWidth, maxWidth: '100%' } }}
    >
      <DialogTitle sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
        <Typography color="primary" sx={{ display: 'inline-flex' }}>
          {icon}
        </Typography>
        {title}
      </DialogTitle>
      <Divider />
      <DialogContent sx={{ pt: 3 }}>{children}</DialogContent>
      <DialogActions sx={{ px: 3, pb: 2 }}>
        <Button variant="text" disabled={loading} onClick={onClose}>
          {t('cancel')}
        </Button>
        <Button color="primary" variant="outlined" disabled={loading} onClick={onSave}>
          {saveLabel || t('save')}
        </Button>
      </DialogActions>
      {loading ? (
        <Stack sx={{ px: 3, pb: 1, alignItems: 'flex-end' }}></Stack>
      ) : null}
    </Dialog>
  )
}

// Web-Admin-Vue/src/components/FormDialog.vue
<!-- SPDX-License-Identifier: Apache-2.0 -->
<template>
  <el-dialog v-model="show" :width="maxWidth" :title="title" :close-on-click-modal="false">
    <div class="d-flex align-center ga-2 mb-3">
      <AppIcon :icon="icon" color="var(--el-color-primary)" />
    </div>
    <slot />
    <template #footer>
      <el-button :disabled="loading" @click="show = false">{{ t('cancel') }}</el-button>
      <el-button type="primary" :loading="loading" @click="emit('save')">
        {{ saveLabel || t('save') }}
      </el-button>
    </template>
  </el-dialog>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'

const props = withDefaults(
  defineProps<{
    modelValue: boolean
    title: string
    icon?: string
    loading?: boolean
    maxWidth?: string | number
    saveLabel?: string
  }>(),
  { icon: 'mdi-form-select', maxWidth: 560 },
)
const emit = defineEmits<{
  (e: 'update:modelValue', v: boolean): void
  (e: 'save'): void
}>()
const { t } = useI18n()

const show = ref(props.modelValue)
watch(
  () => props.modelValue,
  (v) => (show.value = v),
)
watch(show, (v) => emit('update:modelValue', v))
</script>
