// Web-Admin-React/src/components/PageHeader.tsx
// SPDX-License-Identifier: Apache-2.0

import type { ReactNode } from 'react'
import { Box, Typography } from '@mui/material'

interface PageHeaderProps {
  title: string
  subtitle?: string
  children?: ReactNode
}

export function PageHeader({ title, subtitle, children }: PageHeaderProps) {
  return (
    <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 3, flexWrap: 'wrap', gap: 1 }}>
      <Box>
        <Typography variant="h6" fontWeight="bold">
          {title}
        </Typography>
        {subtitle ? (
          <Typography variant="body2" color="text.secondary">
            {subtitle}
          </Typography>
        ) : null}
      </Box>
      <Box sx={{ display: 'flex', gap: 1, flexWrap: 'wrap' }}>{children}</Box>
    </Box>
  )
}

// Web-Admin-Vue/src/components/PageHeader.vue
<!-- SPDX-License-Identifier: Apache-2.0 -->
<template>
  <div class="d-flex justify-space-between align-center mb-4 flex-wrap ga-2">
    <div>
      <h2 class="text-h5 font-weight-bold">{{ title }}</h2>
      <div v-if="subtitle" class="text-body-2 text-medium-emphasis">{{ subtitle }}</div>
    </div>
    <div class="d-flex ga-2 flex-wrap">
      <slot />
    </div>
  </div>
</template>

<script setup lang="ts">
defineProps<{
  title: string
  subtitle?: string
}>()
</script>
