// Web-Admin-React/src/views/403/ForbiddenView.tsx
// SPDX-License-Identifier: Apache-2.0

import { Box, Button, Card, Typography } from '@mui/material'
import ShieldOutlinedIcon from '@mui/icons-material/ShieldOutlined'
import { useNavigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'

export default function ForbiddenView() {
  const { t } = useTranslation()
  const navigate = useNavigate()
  return (
    <Box sx={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
      <Card sx={{ textAlign: 'center', px: 6, py: 5 }}>
        <ShieldOutlinedIcon color="error" sx={{ fontSize: 64, mb: 1 }} />
        <Typography variant="h5" fontWeight="bold" mb={1}>
          {t('forbidden')}
        </Typography>
        <Typography variant="body2" color="text.secondary" mb={3}>
          {t('forbiddenHint')}
        </Typography>
        <Button color="primary" variant="contained" onClick={() => navigate('/login')}>
          {t('back')}
        </Button>
      </Card>
    </Box>
  )
}

// Web-Admin-Vue/src/views/403/ForbiddenView.vue
<!-- SPDX-License-Identifier: Apache-2.0 -->
<template>
  <div class="d-flex align-center justify-center" style="min-height: 100vh">
    <el-card shadow="never" class="text-center px-10 py-8">
      <AppIcon icon="mdi-shield-lock-outline" :size="64" color="var(--el-color-danger)" class="mb-3" />
      <div class="text-h5 font-weight-bold mb-2">{{ t('forbidden') }}</div>
      <div class="text-body-2 text-medium-emphasis mb-4">{{ t('forbiddenHint') }}</div>
      <el-button type="primary" @click="$router.push('/login')">{{ t('back') }}</el-button>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { useI18n } from 'vue-i18n'
const { t } = useI18n()
</script>
