// Web-Admin-React/src/views/org/components/OrgDeptTree.tsx
import { Box, IconButton, List, ListItemButton, ListItemText } from '@mui/material'
import AddIcon from '@mui/icons-material/Add'
import EditOutlinedIcon from '@mui/icons-material/EditOutlined'
import DeleteOutlineIcon from '@mui/icons-material/DeleteOutline'
import { useTranslation } from 'react-i18next'
import type { DeptTreeNode } from '@/types/org'

interface OrgDeptTreeProps {
  node: DeptTreeNode
  selectedId: number | null
  /** 只读模式：隐藏增删改按钮（工作台通讯录用） */
  readonly?: boolean
  onSelect: (id: number) => void
  onAdd: (parentId: number) => void
  onRename: (id: number) => void
  onRemove: (id: number) => void
}

export function OrgDeptTree({ node, selectedId, readonly, onSelect, onAdd, onRename, onRemove }: OrgDeptTreeProps) {
  const { t } = useTranslation()
  return (
    <Box>
      <ListItemButton
        selected={selectedId === node.id}
        onClick={() => onSelect(node.id)}
        sx={{ py: 0.5, minHeight: 36 }}
      >
        <ListItemText primary={node.name} primaryTypographyProps={{ fontSize: 14 }} />
        {!readonly ? (
          <Box sx={{ display: 'flex', gap: 0 }}>
            <IconButton size="small" title={t('deptAdd')} onClick={(e) => { e.stopPropagation(); onAdd(node.id) }}>
              <AddIcon fontSize="small" />
            </IconButton>
            <IconButton size="small" title={t('edit')} onClick={(e) => { e.stopPropagation(); onRename(node.id) }}>
              <EditOutlinedIcon fontSize="small" />
            </IconButton>
            <IconButton size="small" color="error" title={t('delete')} onClick={(e) => { e.stopPropagation(); onRemove(node.id) }}>
              <DeleteOutlineIcon fontSize="small" />
            </IconButton>
          </Box>
        ) : null}
      </ListItemButton>
      {node.children.length ? (
        <List dense sx={{ pl: 2, pt: 0 }}>
          {node.children.map((c) => (
            <OrgDeptTree key={c.id} node={c} selectedId={selectedId} readonly={readonly} onSelect={onSelect} onAdd={onAdd} onRename={onRename} onRemove={onRemove} />
          ))}
        </List>
      ) : null}
    </Box>
  )
}

// Web-Admin-Vue/src/views/org/components/OrgDeptTree.vue
<template>
  <!-- 有子部门：可展开的 list-group -->
  <v-list-group v-if="node.children.length" :value="node.id">
    <template #activator="{ props: groupProps }">
      <v-list-item
        v-bind="groupProps"
        :title="node.name"
        :active="selectedId === node.id"
        :readonly="readonly"
        @click="emit('select', node.id)"
      >
        <template #append>
          <div v-if="!readonly" class="d-flex ga-0" @click.stop>
            <v-btn icon="mdi-plus" size="x-small" variant="text" :title="t('deptAdd')" @click="emit('add', node.id)" />
            <v-btn icon="mdi-pencil-outline" size="x-small" variant="text" :title="t('edit')" @click="emit('rename', node.id)" />
            <v-btn icon="mdi-delete-outline" size="x-small" variant="text" color="error" :title="t('delete')" @click="emit('remove', node.id)" />
          </div>
        </template>
      </v-list-item>
    </template>
    <OrgDeptTree
      v-for="c in node.children"
      :key="c.id"
      :node="c"
      :selected-id="selectedId"
      :readonly="readonly"
      @select="emit('select', $event)"
      @add="emit('add', $event)"
      @rename="emit('rename', $event)"
      @remove="emit('remove', $event)"
    />
  </v-list-group>

  <!-- 叶子部门 -->
  <v-list-item
    v-else
    :title="node.name"
    :active="selectedId === node.id"
    :readonly="readonly"
    @click="emit('select', node.id)"
  >
    <template #append>
      <div v-if="!readonly" class="d-flex ga-0" @click.stop>
        <v-btn icon="mdi-plus" size="x-small" variant="text" :title="t('deptAdd')" @click="emit('add', node.id)" />
        <v-btn icon="mdi-pencil-outline" size="x-small" variant="text" :title="t('edit')" @click="emit('rename', node.id)" />
        <v-btn icon="mdi-delete-outline" size="x-small" variant="text" color="error" :title="t('delete')" @click="emit('remove', node.id)" />
      </div>
    </template>
  </v-list-item>
</template>

<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import type { DeptTreeNode } from '@/types/org'

defineOptions({ name: 'OrgDeptTree' })

withDefaults(
  defineProps<{
    node: DeptTreeNode
    selectedId: number | null
    /** 只读模式：隐藏增删改按钮（工作台通讯录用） */
    readonly?: boolean
  }>(),
  { readonly: false },
)

const emit = defineEmits<{
  (e: 'select', id: number): void
  (e: 'add', parentId: number): void
  (e: 'rename', id: number): void
  (e: 'remove', id: number): void
}>()

const { t } = useI18n()
</script>
