// Web-Admin-React/src/views/org/OrgView.tsx
import { useEffect, useMemo, useState } from 'react'
import { Box, Button, Card, CardContent, CardHeader, Divider, IconButton, List, ListItemButton, MenuItem, Select, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material'
import AddIcon from '@mui/icons-material/Add'
import DeleteOutlineIcon from '@mui/icons-material/DeleteOutline'
import GroupOutlinedIcon from '@mui/icons-material/GroupOutlined'
import PersonAddAltOutlinedIcon from '@mui/icons-material/PersonAddAltOutlined'
import LinkOutlinedIcon from '@mui/icons-material/LinkOutlined'
import ContentCopyIcon from '@mui/icons-material/ContentCopy'
import AccountTreeOutlinedIcon from '@mui/icons-material/AccountTreeOutlined'
import { useTranslation } from 'react-i18next'
import { PageHeader } from '@/components/PageHeader'
import { AppTable, type AppColumn } from '@/components/AppTable'
import { AppPagination } from '@/components/AppPagination'
import { FormDialog } from '@/components/FormDialog'
import { ConfirmDialog } from '@/components/ConfirmDialog'
import { DebouncedSearch } from '@/components/DebouncedSearch'
import { useSnackbarStore } from '@/stores/snackbar'
import { orgApi } from '@/api/org'
import { usersApi } from '@/api/users'
import { OrgDeptTree } from './components/OrgDeptTree'
import { buildDeptTree, collectDescendantIds } from './orgTree'
import type { Organization, Department, OrgMember, OrgMemberRole, OrgInvite, DeptTreeNode } from '@/types/org'

const roleOptions = [
  { value: 'owner', label: 'roleOwner' },
  { value: 'admin', label: 'roleAdmin' },
  { value: 'member', label: 'roleMember' },
] as const

const cap = (s: string) => (s ? s.charAt(0).toUpperCase() + s.slice(1) : s)

export default function OrgView() {
  const { t } = useTranslation()
  const snackbar = useSnackbarStore()

  // 组织
  const [orgs, setOrgs] = useState<Organization[]>([])
  const [currentOrgId, setCurrentOrgId] = useState<number | null>(null)
  const [savingOrg, setSavingOrg] = useState(false)
  const [showOrgDialog, setShowOrgDialog] = useState(false)
  const [orgForm, setOrgForm] = useState({ id: 0, name: '', description: '' })

  // 部门
  const [departments, setDepartments] = useState<Department[]>([])
  const [selectedDeptId, setSelectedDeptId] = useState<number | null>(null)
  const [savingDept, setSavingDept] = useState(false)
  const [showDeptDialog, setShowDeptDialog] = useState(false)
  const [deptForm, setDeptForm] = useState({ id: 0, name: '', parentId: null as number | null })

  // 成员
  const [members, setMembers] = useState<OrgMember[]>([])
  const [memberTotal, setMemberTotal] = useState(0)
  const [memberPage, setMemberPage] = useState(1)
  const [memberKeyword, setMemberKeyword] = useState('')
  const [memberLoading, setMemberLoading] = useState(false)
  const [savingMember, setSavingMember] = useState(false)
  const [showMemberDialog, setShowMemberDialog] = useState(false)
  const [memberForm, setMemberForm] = useState({ userId: null as number | null, role: 'member' as OrgMemberRole, deptId: null as number | null })
  const [users, setUsers] = useState<Array<{ id: number; username: string; nickname: string }>>([])

  // 邀请
  const [invites, setInvites] = useState<OrgInvite[]>([])
  const [showInviteDialog, setShowInviteDialog] = useState(false)
  const [savingInvite, setSavingInvite] = useState(false)
  const [inviteForm, setInviteForm] = useState({ role: 'member' as OrgMemberRole, deptId: null as number | null })
  const [inviteResult, setInviteResult] = useState('')

  // 通用确认
  const [confirm, setConfirm] = useState<{ show: boolean; title: string; content: string; action: (() => Promise<void>) | null }>({
    show: false,
    title: '',
    content: '',
    action: null,
  })

  const deptTree = useMemo(() => buildDeptTree(departments), [departments])

  const parentDeptOptions = useMemo(() => {
    const exclude = new Set<number>()
    if (deptForm.id) {
      const self = departments.find((d) => d.id === deptForm.id)
      if (self) {
        const root = buildDeptTree(departments).find((n) => n.id === self.id)
        if (root) collectDescendantIds(root, [...exclude.values()]).forEach((id) => exclude.add(id))
      }
    }
    return departments.filter((d) => !exclude.has(d.id)).map((d) => ({ label: d.name, value: d.id }))
  }, [departments, deptForm.id])

  const deptOptions = useMemo(() => departments.map((d) => ({ label: d.name, value: d.id })), [departments])
  const memberUserOptions = useMemo(
    () => users.filter((u) => !members.some((m) => m.userId === u.id)).map((u) => ({ label: `${u.nickname || u.username} (${u.username})`, value: u.id })),
    [users, members],
  )

  // 组织
  async function loadOrgs() {
    const res = await orgApi.listOrganizations(1, 100)
    setOrgs(res.items)
    setCurrentOrgId((cur) => (cur ?? (res.items.length ? res.items[0].id : null)))
  }

  async function onSelectOrg(id: number | null) {
    setCurrentOrgId(id)
    setSelectedDeptId(null)
    setMemberPage(1)
    if (id) {
      void loadDepartments(id)
      void loadMembers(1, id)
      void loadInvites(id)
    }
  }

  function openCreateOrg() {
    setOrgForm({ id: 0, name: '', description: '' })
    setShowOrgDialog(true)
  }

  async function onSaveOrg() {
    if (!orgForm.name.trim()) return
    setSavingOrg(true)
    try {
      if (orgForm.id) {
        await orgApi.updateOrganization(orgForm.id, { name: orgForm.name, description: orgForm.description })
        snackbar.success(t('saved'))
      } else {
        const org = await orgApi.createOrganization({ name: orgForm.name, description: orgForm.description })
        snackbar.success(t('orgCreated'))
        await loadOrgs()
        setCurrentOrgId(org.id)
        void onSelectOrg(org.id)
      }
      setShowOrgDialog(false)
    } catch {
      snackbar.error(t('saveFailed'))
    } finally {
      setSavingOrg(false)
    }
  }

  function confirmDeleteOrg() {
    const orgId = currentOrgId
    if (!orgId) return
    setConfirm({
      show: true,
      title: t('deleteOrgTitle'),
      content: t('deleteOrgContent'),
      action: async () => {
        await orgApi.removeOrganization(orgId)
        snackbar.success(t('deleted'))
        setCurrentOrgId(null)
        await loadOrgs()
      },
    })
  }

  // 部门
  async function loadDepartments(orgId = currentOrgId) {
    if (!orgId) return
    setDepartments(await orgApi.listDepartments(orgId))
  }

  function selectDept(id: number | null) {
    setSelectedDeptId(id)
    void loadMembers(1)
  }

  function openAddDept(parentId: number | null) {
    setDeptForm({ id: 0, name: '', parentId })
    setShowDeptDialog(true)
  }

  function openEditDept(id: number) {
    const d = departments.find((x) => x.id === id)
    if (!d) return
    setDeptForm({ id: d.id, name: d.name, parentId: d.parentId ?? null })
    setShowDeptDialog(true)
  }

  async function onSaveDept() {
    if (!deptForm.name.trim()) return
    setSavingDept(true)
    try {
      if (deptForm.id) {
        await orgApi.updateDepartment(deptForm.id, { name: deptForm.name, parentId: deptForm.parentId })
      } else {
        if (!currentOrgId) return
        await orgApi.createDepartment(currentOrgId, { name: deptForm.name, parentId: deptForm.parentId ?? undefined })
      }
      snackbar.success(t('saved'))
      setShowDeptDialog(false)
      await loadDepartments()
    } catch {
      snackbar.error(t('saveFailed'))
    } finally {
      setSavingDept(false)
    }
  }

  function confirmDeleteDept(id: number) {
    const d = departments.find((x) => x.id === id)
    setConfirm({
      show: true,
      title: t('deleteDeptTitle'),
      content: t('deleteDeptContent', { name: d?.name ?? '' }),
      action: async () => {
        await orgApi.removeDepartment(id)
        snackbar.success(t('deleted'))
        if (selectedDeptId === id) setSelectedDeptId(null)
        await loadDepartments()
        void loadMembers(1)
      },
    })
  }

  // 成员
  async function loadMembers(page = memberPage, orgId = currentOrgId) {
    if (!orgId) return
    setMemberLoading(true)
    try {
      const res = await orgApi.listMembers(orgId, page, 20, memberKeyword || undefined, selectedDeptId ?? undefined)
      setMembers(res.items)
      setMemberTotal(res.total)
      setMemberPage(page)
    } catch {
      snackbar.error(t('loadFailed'))
    } finally {
      setMemberLoading(false)
    }
  }

  async function openAddMember() {
    const res = await usersApi.list(1, 100)
    setUsers(res.items.map((u) => ({ id: u.id, username: u.username, nickname: u.nickname })))
    setMemberForm({ userId: null, role: 'member', deptId: null })
    setShowMemberDialog(true)
  }

  async function onSaveMember() {
    if (!currentOrgId || !memberForm.userId) return
    setSavingMember(true)
    try {
      await orgApi.addMember(currentOrgId, {
        userId: memberForm.userId,
        role: memberForm.role,
        ...(memberForm.deptId ? { deptId: memberForm.deptId } : {}),
      })
      snackbar.success(t('memberAdded'))
      setShowMemberDialog(false)
      await loadMembers()
      await loadDepartments()
    } catch {
      snackbar.error(t('saveFailed'))
    } finally {
      setSavingMember(false)
    }
  }

  async function updateMemberRole(item: OrgMember, role: OrgMemberRole) {
    try {
      await orgApi.updateMember(item.id, { role })
      snackbar.success(t('saved'))
      setMembers((prev) => prev.map((m) => (m.id === item.id ? { ...m, role } : m)))
    } catch {
      snackbar.error(t('saveFailed'))
      void loadMembers()
    }
  }

  function confirmDeleteMember(item: OrgMember) {
    setConfirm({
      show: true,
      title: t('memberRemove'),
      content: t('memberRemoveContent', { name: item.nickname || item.username || '' }),
      action: async () => {
        await orgApi.removeMember(item.id)
        snackbar.success(t('deleted'))
        void loadMembers()
      },
    })
  }

  // 邀请
  async function loadInvites(orgId = currentOrgId) {
    if (!orgId) return
    setInvites(await orgApi.listInvites(orgId))
  }

  function openInvite() {
    setInviteForm({ role: 'member', deptId: null })
    setInviteResult('')
    setShowInviteDialog(true)
  }

  async function onSaveInvite() {
    if (!currentOrgId) return
    setSavingInvite(true)
    try {
      const inv = await orgApi.createInvite(currentOrgId, {
        role: inviteForm.role,
        ...(inviteForm.deptId ? { deptId: inviteForm.deptId } : {}),
      })
      setInviteResult(inv.code)
      await loadInvites()
    } catch {
      snackbar.error(t('saveFailed'))
    } finally {
      setSavingInvite(false)
    }
  }

  async function copyInvite(code: string) {
    try {
      await navigator.clipboard.writeText(code)
      snackbar.success(t('inviteCopied'))
    } catch {
      snackbar.error(t('saveFailed'))
    }
  }

  function revokeInvite(inv: OrgInvite) {
    setConfirm({
      show: true,
      title: t('inviteRevoke'),
      content: t('inviteRevokeContent', { code: inv.code }),
      action: async () => {
        await orgApi.removeInvite(inv.id)
        snackbar.success(t('deleted'))
        void loadInvites()
      },
    })
  }

  async function runConfirm() {
    const action = confirm.action
    setConfirm({ show: false, title: '', content: '', action: null })
    if (action) await action()
  }

  useEffect(() => {
    void (async () => {
      await loadOrgs()
      if (currentOrgId) void onSelectOrg(currentOrgId)
    })()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const memberHeaders: AppColumn<OrgMember>[] = [
    { key: 'nickname', title: t('nicknameCol'), render: (m) => m.nickname || '-' },
    { key: 'username', title: t('usernameCol'), render: (m) => m.username || '-' },
    { key: 'email', title: t('emailCol'), render: (m) => m.email || '-' },
    {
      key: 'role',
      title: t('roleCol'),
      render: (m) => (
        <Select size="small" value={m.role} onChange={(e) => void updateMemberRole(m, e.target.value as OrgMemberRole)} sx={{ maxWidth: 130, minWidth: 100 }}>
          {roleOptions.map((r) => (
            <MenuItem key={r.value} value={r.value}>
              {t(r.label)}
            </MenuItem>
          ))}
        </Select>
      ),
    },
    { key: 'deptName', title: t('deptCol'), render: (m) => m.deptName || '-' },
    {
      key: 'actions',
      title: t('actionCol'),
      render: (m) => (
        <IconButton size="small" color="error" title={t('delete')} onClick={() => confirmDeleteMember(m)}>
          <DeleteOutlineIcon fontSize="small" />
        </IconButton>
      ),
    },
  ]

  return (
    <Box>
      <PageHeader title={t('navOrg')} subtitle={t('orgSubtitle')}>
        <Button color="primary" variant="contained" startIcon={<AddIcon />} onClick={openCreateOrg}>
          {t('orgCreate')}
        </Button>
      </PageHeader>

      <Card sx={{ mb: 3 }}>
        <CardContent sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
          <Select size="small" fullWidth value={currentOrgId ?? ''} onChange={(e) => void onSelectOrg(e.target.value === '' ? null : Number(e.target.value))} displayEmpty>
            <MenuItem value="">{t('selectOrg')}</MenuItem>
            {orgs.map((o) => (
              <MenuItem key={o.id} value={o.id}>
                {o.name}
              </MenuItem>
            ))}
          </Select>
          {currentOrgId ? (
            <Button variant="outlined" color="error" startIcon={<DeleteOutlineIcon />} onClick={confirmDeleteOrg}>
              {t('deleteOrg')}
            </Button>
          ) : null}
        </CardContent>
      </Card>

      {currentOrgId ? (
        <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: '4fr 8fr' }, gap: 3 }}>
          <Card>
            <CardHeader
              avatar={<AccountTreeOutlinedIcon />}
              title={t('deptTitle')}
              action={
                <IconButton size="small" title={t('deptAdd')} onClick={() => openAddDept(null)}>
                  <AddIcon />
                </IconButton>
              }
            />
            <Divider />
            <CardContent sx={{ p: 1 }}>
              <List dense>
                <DeptTreeItem
                  active={selectedDeptId == null}
                  label={t('allDepartments')}
                  onClick={() => selectDept(null)}
                />
                {deptTree.map((n: DeptTreeNode) => (
                  <OrgDeptTree key={n.id} node={n} selectedId={selectedDeptId} onSelect={(id) => selectDept(id)} onAdd={openAddDept} onRename={openEditDept} onRemove={confirmDeleteDept} />
                ))}
              </List>
              {!departments.length ? (
                <Typography variant="caption" color="text.secondary" sx={{ p: 1 }}>
                  {t('noDept')}
                </Typography>
              ) : null}
            </CardContent>
          </Card>

          <Card>
            <CardHeader
              avatar={<GroupOutlinedIcon />}
              title={t('memberTitle')}
              action={
                <Box sx={{ display: 'flex', gap: 1 }}>
                  <Button variant="outlined" startIcon={<LinkOutlinedIcon />} onClick={openInvite}>
                    {t('inviteCreate')}
                  </Button>
                  <Button color="primary" variant="contained" startIcon={<PersonAddAltOutlinedIcon />} onClick={() => void openAddMember()}>
                    {t('memberAdd')}
                  </Button>
                </Box>
              }
            />
            <Divider />
            <CardContent>
              <Box sx={{ mb: 2 }}>
                <DebouncedSearch value={memberKeyword} placeholder={t('searchMember')} onChange={setMemberKeyword} onSearch={() => void loadMembers(1)} />
              </Box>
              <AppTable headers={memberHeaders} items={members} loading={memberLoading} emptyText={t('noMember')} />
              <AppPagination page={memberPage} limit={20} total={memberTotal} loading={memberLoading} onChange={(p) => void loadMembers(p)} />

              <Divider sx={{ my: 2 }} />
              <Typography variant="subtitle2" mb={1}>
                {t('inviteList')}
              </Typography>
              {invites.length ? (
                <Table size="small">
                  <TableHead>
                    <TableRow>
                      <TableCell>{t('inviteCode')}</TableCell>
                      <TableCell>{t('roleCol')}</TableCell>
                      <TableCell>{t('statusCol')}</TableCell>
                      <TableCell>{t('actionCol')}</TableCell>
                    </TableRow>
                  </TableHead>
                  <TableBody>
                    {invites.map((inv) => (
                      <TableRow key={inv.id}>
                        <TableCell><code>{inv.code}</code></TableCell>
                        <TableCell>{t(`role${cap(inv.role)}`)}</TableCell>
                        <TableCell>{inv.usedBy ? t('inviteUsed') : t('invitePending')}</TableCell>
                        <TableCell>
                          <IconButton size="small" title={t('inviteCopy')} onClick={() => void copyInvite(inv.code)}>
                            <ContentCopyIcon fontSize="small" />
                          </IconButton>
                          <IconButton size="small" color="error" title={t('inviteRevoke')} onClick={() => revokeInvite(inv)}>
                            <DeleteOutlineIcon fontSize="small" />
                          </IconButton>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              ) : (
                <Typography variant="caption" color="text.secondary">
                  {t('noInvite')}
                </Typography>
              )}
            </CardContent>
          </Card>
        </Box>
      ) : (
        <Card sx={{ textAlign: 'center', py: 6 }}>
          <Typography variant="h6">{t('selectOrgFirst')}</Typography>
          <Typography variant="body2" color="text.secondary" mt={0.5}>
            {t('selectOrgFirstHint')}
          </Typography>
        </Card>
      )}

      {/* 新建/编辑组织 */}
      <FormDialog open={showOrgDialog} title={orgForm.id ? t('editOrg') : t('orgCreate')} loading={savingOrg} onClose={() => setShowOrgDialog(false)} onSave={() => void onSaveOrg()}>
        <Box component="form" onSubmit={(e) => { e.preventDefault(); void onSaveOrg() }}>
          <TextField label={t('orgName')} required fullWidth margin="dense" value={orgForm.name} onChange={(e) => setOrgForm({ ...orgForm, name: e.target.value })} />
          <TextField label={t('orgDescription')} fullWidth margin="dense" value={orgForm.description} onChange={(e) => setOrgForm({ ...orgForm, description: e.target.value })} />
        </Box>
      </FormDialog>

      {/* 新建/编辑部门 */}
      <FormDialog open={showDeptDialog} title={deptForm.id ? t('editDept') : t('deptAdd')} loading={savingDept} onClose={() => setShowDeptDialog(false)} onSave={() => void onSaveDept()}>
        <Box component="form" onSubmit={(e) => { e.preventDefault(); void onSaveDept() }}>
          <TextField label={t('deptName')} required fullWidth margin="dense" value={deptForm.name} onChange={(e) => setDeptForm({ ...deptForm, name: e.target.value })} />
          <Select size="small" fullWidth displayEmpty value={deptForm.parentId ?? ''} onChange={(e) => setDeptForm({ ...deptForm, parentId: e.target.value === '' ? null : Number(e.target.value) })}>
            <MenuItem value="">{t('deptParent')}</MenuItem>
            {parentDeptOptions.map((o) => (
              <MenuItem key={o.value} value={o.value}>
                {o.label}
              </MenuItem>
            ))}
          </Select>
        </Box>
      </FormDialog>

      {/* 添加成员 */}
      <FormDialog open={showMemberDialog} title={t('memberAdd')} loading={savingMember} onClose={() => setShowMemberDialog(false)} onSave={() => void onSaveMember()}>
        <Box component="form" onSubmit={(e) => { e.preventDefault(); void onSaveMember() }}>
          <Select size="small" fullWidth displayEmpty value={memberForm.userId ?? ''} onChange={(e) => setMemberForm({ ...memberForm, userId: e.target.value === '' ? null : Number(e.target.value) })}>
            <MenuItem value="" disabled>{t('selectUser')}</MenuItem>
            {memberUserOptions.map((o) => (
              <MenuItem key={o.value} value={o.value}>
                {o.label}
              </MenuItem>
            ))}
          </Select>
          <Select size="small" fullWidth sx={{ mt: 2 }} value={memberForm.role} onChange={(e) => setMemberForm({ ...memberForm, role: e.target.value as OrgMemberRole })}>
            {roleOptions.map((r) => (
              <MenuItem key={r.value} value={r.value}>
                {t(r.label)}
              </MenuItem>
            ))}
          </Select>
          <Select size="small" fullWidth displayEmpty sx={{ mt: 2 }} value={memberForm.deptId ?? ''} onChange={(e) => setMemberForm({ ...memberForm, deptId: e.target.value === '' ? null : Number(e.target.value) })}>
            <MenuItem value="">{t('deptOptional')}</MenuItem>
            {deptOptions.map((o) => (
              <MenuItem key={o.value} value={o.value}>
                {o.label}
              </MenuItem>
            ))}
          </Select>
        </Box>
      </FormDialog>

      {/* 邀请 */}
      <FormDialog open={showInviteDialog} title={t('inviteCreate')} loading={savingInvite} saveLabel={t('generateInvite')} onClose={() => setShowInviteDialog(false)} onSave={() => void onSaveInvite()}>
        <Box component="form" onSubmit={(e) => { e.preventDefault(); void onSaveInvite() }}>
          <Select size="small" fullWidth value={inviteForm.role} onChange={(e) => setInviteForm({ ...inviteForm, role: e.target.value as OrgMemberRole })}>
            {roleOptions.map((r) => (
              <MenuItem key={r.value} value={r.value}>
                {t(r.label)}
              </MenuItem>
            ))}
          </Select>
          <Select size="small" fullWidth displayEmpty sx={{ mt: 2 }} value={inviteForm.deptId ?? ''} onChange={(e) => setInviteForm({ ...inviteForm, deptId: e.target.value === '' ? null : Number(e.target.value) })}>
            <MenuItem value="">{t('deptOptional')}</MenuItem>
            {deptOptions.map((o) => (
              <MenuItem key={o.value} value={o.value}>
                {o.label}
              </MenuItem>
            ))}
          </Select>
          {inviteResult ? (
            <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mt: 2 }}>
              <code style={{ fontSize: 18 }}>{inviteResult}</code>
              <IconButton size="small" title={t('inviteCopy')} onClick={() => void copyInvite(inviteResult)}>
                <ContentCopyIcon fontSize="small" />
              </IconButton>
            </Box>
          ) : null}
        </Box>
      </FormDialog>

      <ConfirmDialog open={confirm.show} title={confirm.title} content={confirm.content} onClose={() => setConfirm({ show: false, title: '', content: '', action: null })} onConfirm={() => void runConfirm()} />
    </Box>
  )
}

function DeptTreeItem({ active, label, onClick }: { active: boolean; label: string; onClick: () => void }) {
  return (
    <ListItemButton selected={active} onClick={onClick} sx={{ py: 0.5, minHeight: 36 }}>
      <Typography fontSize={14}>{label}</Typography>
    </ListItemButton>
  )
}

// Web-Admin-Vue/src/views/org/OrgView.vue
<template>
  <div>
    <PageHeader :title="t('navOrg')" :subtitle="t('orgSubtitle')">
      <v-btn color="primary" prepend-icon="mdi-plus" @click="openCreateOrg">
        {{ t('orgCreate') }}
      </v-btn>
    </PageHeader>

    <!-- 组织选择 -->
    <v-card class="mb-4">
      <v-card-text class="d-flex align-center ga-3">
        <v-select
          v-model="currentOrgId"
          :items="orgs"
          item-title="name"
          item-value="id"
          :label="t('selectOrg')"
          class="flex-grow-1"
          density="comfortable"
          clearable
          @update:model-value="onSelectOrg"
        />
        <v-btn
          v-if="currentOrgId"
          variant="tonal"
          color="error"
          prepend-icon="mdi-delete-outline"
          @click="confirmDeleteOrg"
        >
          {{ t('deleteOrg') }}
        </v-btn>
      </v-card-text>
    </v-card>

    <v-row v-if="currentOrgId" class="ma-0">
      <!-- 左：部门树 -->
      <v-col cols="12" md="4" class="ps-0">
        <v-card>
          <v-card-title class="d-flex align-center">
            <v-icon icon="mdi-sitemap" class="me-2" />
            {{ t('deptTitle') }}
            <v-spacer />
            <v-btn icon="mdi-plus" size="small" variant="text" :title="t('deptAdd')" @click="openAddDept(null)" />
          </v-card-title>
          <v-divider />
          <v-card-text class="pa-2">
            <v-list density="comfortable" nav>
              <v-list-item
                :active="selectedDeptId == null"
                prepend-icon="mdi-office-building-outline"
                :title="t('allDepartments')"
                @click="selectDept(null)"
              />
              <OrgDeptTree
                v-for="n in deptTree"
                :key="n.id"
                :node="n"
                :selected-id="selectedDeptId"
                @select="selectDept"
                @add="openAddDept"
                @rename="openEditDept"
                @remove="confirmDeleteDept"
              />
            </v-list>
            <div v-if="!departments.length" class="text-medium-emphasis pa-2 text-caption">
              {{ t('noDept') }}
            </div>
          </v-card-text>
        </v-card>
      </v-col>

      <!-- 右：成员 -->
      <v-col cols="12" md="8" class="pe-0">
        <v-card>
          <v-card-title class="d-flex align-center">
            <v-icon icon="mdi-account-group-outline" class="me-2" />
            {{ t('memberTitle') }}
            <v-spacer />
            <v-btn variant="tonal" prepend-icon="mdi-link-variant" class="me-2" @click="openInvite">
              {{ t('inviteCreate') }}
            </v-btn>
            <v-btn color="primary" prepend-icon="mdi-account-plus-outline" @click="openAddMember">
              {{ t('memberAdd') }}
            </v-btn>
          </v-card-title>
          <v-divider />
          <v-card-text>
            <div class="d-flex ga-3 mb-3">
              <DebouncedSearch v-model="memberKeyword" :placeholder="t('searchMember')" class="flex-grow-1" @search="loadMembers(1)" />
            </div>
            <AppTable :headers="memberHeaders" :items="members" :loading="memberLoading" :total="memberTotal" :items-per-page="memberLimit">
              <template #item.nickname="{ item }">{{ item.nickname || '-' }}</template>
              <template #item.role="{ item }">
                <v-select
                  :model-value="item.role"
                  :items="roleOptions"
                  item-title="label"
                  item-value="value"
                  density="compact"
                  hide-details
                  class="role-select"
                  @update:model-value="(v: string) => updateMemberRole(item, v as OrgMemberRole)"
                />
              </template>
              <template #item.deptName="{ item }">{{ item.deptName || '-' }}</template>
              <template #item.actions="{ item }">
                <v-btn icon="mdi-delete-outline" variant="text" size="small" color="error" :title="t('delete')" @click="confirmDeleteMember(item)" />
              </template>
              <template #pagination>
                <AppPagination :page="memberPage" :limit="memberLimit" :total="memberTotal" :loading="memberLoading" @update:page="loadMembers" />
              </template>
            </AppTable>

            <!-- 邀请列表 -->
            <v-divider class="my-4" />
            <div class="text-subtitle-2 mb-2">{{ t('inviteList') }}</div>
            <v-table v-if="invites.length" density="compact">
              <thead>
                <tr>
                  <th>{{ t('inviteCode') }}</th>
                  <th>{{ t('roleCol') }}</th>
                  <th>{{ t('statusCol') }}</th>
                  <th>{{ t('actionCol') }}</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="inv in invites" :key="inv.id">
                  <td><code>{{ inv.code }}</code></td>
                  <td>{{ t(`role${cap(inv.role)}`) }}</td>
                  <td>{{ inv.usedBy ? t('inviteUsed') : t('invitePending') }}</td>
                  <td>
                    <v-btn icon="mdi-content-copy" size="x-small" variant="text" :title="t('inviteCopy')" @click="copyInvite(inv.code)" />
                    <v-btn icon="mdi-delete-outline" size="x-small" variant="text" color="error" :title="t('inviteRevoke')" @click="revokeInvite(inv)" />
                  </td>
                </tr>
              </tbody>
            </v-table>
            <div v-else class="text-medium-emphasis text-caption">{{ t('noInvite') }}</div>
          </v-card-text>
        </v-card>
      </v-col>
    </v-row>

    <v-empty-state v-else icon="mdi-office-building-outline" :title="t('selectOrgFirst')" :text="t('selectOrgFirstHint')" />

    <!-- 新建/编辑组织 -->
    <FormDialog v-model="showOrgDialog" :title="orgForm.id ? t('editOrg') : t('orgCreate')" :loading="savingOrg" @save="onSaveOrg">
      <v-form @submit.prevent="onSaveOrg">
        <v-text-field v-model="orgForm.name" :label="t('orgName')" :rules="[required]" required />
        <v-text-field v-model="orgForm.description" :label="t('orgDescription')" />
      </v-form>
    </FormDialog>

    <!-- 新建/编辑部门 -->
    <FormDialog v-model="showDeptDialog" :title="deptForm.id ? t('editDept') : t('deptAdd')" :loading="savingDept" @save="onSaveDept">
      <v-form @submit.prevent="onSaveDept">
        <v-text-field v-model="deptForm.name" :label="t('deptName')" :rules="[required]" required />
        <v-select
          v-model="deptForm.parentId"
          :items="parentDeptOptions"
          item-title="label"
          item-value="value"
          :label="t('deptParent')"
          clearable
        />
      </v-form>
    </FormDialog>

    <!-- 添加成员 -->
    <FormDialog v-model="showMemberDialog" :title="t('memberAdd')" :loading="savingMember" @save="onSaveMember">
      <v-form @submit.prevent="onSaveMember">
        <v-select
          v-model="memberForm.userId"
          :items="memberUserOptions"
          item-title="label"
          item-value="value"
          :label="t('selectUser')"
          :rules="[required]"
          required
        />
        <v-select v-model="memberForm.role" :items="roleOptions" item-title="label" item-value="value" :label="t('roleCol')" />
        <v-select v-model="memberForm.deptId" :items="deptOptions" item-title="label" item-value="value" :label="t('deptOptional')" clearable />
      </v-form>
    </FormDialog>

    <!-- 邀请 -->
    <FormDialog v-model="showInviteDialog" :title="t('inviteCreate')" :loading="savingInvite" :save-label="t('generateInvite')" @save="onSaveInvite">
      <v-form @submit.prevent="onSaveInvite">
        <v-select v-model="inviteForm.role" :items="roleOptions" item-title="label" item-value="value" :label="t('roleCol')" />
        <v-select v-model="inviteForm.deptId" :items="deptOptions" item-title="label" item-value="value" :label="t('deptOptional')" clearable />
        <div v-if="inviteResult" class="d-flex align-center ga-2 mt-2">
          <code class="text-h6">{{ inviteResult }}</code>
          <v-btn icon="mdi-content-copy" size="small" variant="tonal" :title="t('inviteCopy')" @click="copyInvite(inviteResult)" />
        </div>
      </v-form>
    </FormDialog>

    <ConfirmDialog v-model="confirm.show" :title="confirm.title" :content="confirm.content" @confirm="runConfirm" />
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { useSnackbarStore } from '@/stores/snackbar'
import { orgApi } from '@/api/org'
import { usersApi } from '@/api/users'
import type { Organization, Department, OrgMember, OrgMemberRole, OrgInvite } from '@/types/org'
import type { AdminUser } from '@/types/user'
import PageHeader from '@/components/PageHeader.vue'
import AppTable from '@/components/AppTable.vue'
import AppPagination from '@/components/AppPagination.vue'
import FormDialog from '@/components/FormDialog.vue'
import ConfirmDialog from '@/components/ConfirmDialog.vue'
import DebouncedSearch from '@/components/DebouncedSearch.vue'
import OrgDeptTree from './components/OrgDeptTree.vue'
import { buildDeptTree } from './orgTree'

const { t } = useI18n()
const snackbar = useSnackbarStore()

// ── 组织 ──
const orgs = ref<Organization[]>([])
const currentOrgId = ref<number | null>(null)
const savingOrg = ref(false)

async function loadOrgs() {
  const res = await orgApi.listOrganizations(1, 100)
  orgs.value = res.items
  if (!currentOrgId.value && res.items.length) currentOrgId.value = res.items[0].id
}

function onSelectOrg(id: number | null) {
  currentOrgId.value = id
  selectedDeptId.value = null
  memberPage.value = 1
  if (id) {
    loadDepartments()
    loadMembers(1)
    loadInvites()
  }
}

function openCreateOrg() {
  orgForm.id = 0
  orgForm.name = ''
  orgForm.description = ''
  showOrgDialog.value = true
}

async function onSaveOrg() {
  if (!orgForm.name.trim()) return
  savingOrg.value = true
  try {
    if (orgForm.id) {
      await orgApi.updateOrganization(orgForm.id, { name: orgForm.name, description: orgForm.description })
      snackbar.success(t('saved'))
    } else {
      const org = await orgApi.createOrganization({ name: orgForm.name, description: orgForm.description })
      snackbar.success(t('orgCreated'))
      await loadOrgs()
      currentOrgId.value = org.id
      onSelectOrg(org.id)
    }
    showOrgDialog.value = false
  } catch {
    snackbar.error(t('saveFailed'))
  } finally {
    savingOrg.value = false
  }
}

function confirmDeleteOrg() {
  const orgId = currentOrgId.value
  if (!orgId) return
  confirm.show = true
  confirm.title = t('deleteOrgTitle')
  confirm.content = t('deleteOrgContent')
  confirm.action = async () => {
    await orgApi.removeOrganization(orgId)
    snackbar.success(t('deleted'))
    currentOrgId.value = null
    await loadOrgs()
  }
}

// ── 部门 ──
const departments = ref<Department[]>([])
const selectedDeptId = ref<number | null>(null)
const savingDept = ref(false)
const showDeptDialog = ref(false)
const deptForm = reactive({ id: 0, name: '', parentId: null as number | null })

const deptTree = computed(() => buildDeptTree(departments.value))

async function loadDepartments() {
  if (!currentOrgId.value) return
  departments.value = await orgApi.listDepartments(currentOrgId.value)
}

function selectDept(id: number | null) {
  selectedDeptId.value = id
  loadMembers(1)
}

function openAddDept(parentId: number | null) {
  deptForm.id = 0
  deptForm.name = ''
  deptForm.parentId = parentId
  showDeptDialog.value = true
}

function openEditDept(id: number) {
  const d = departments.value.find((x) => x.id === id)
  if (!d) return
  deptForm.id = d.id
  deptForm.name = d.name
  deptForm.parentId = d.parentId ?? null
  showDeptDialog.value = true
}

const parentDeptOptions = computed(() => {
  // 编辑时排除自身及其子孙（后端也会防环）
  const exclude = new Set<number>()
  if (deptForm.id) {
    const self = departments.value.find((d) => d.id === deptForm.id)
    if (self) {
      const root = buildDeptTree(departments.value).find((n) => n.id === self.id)
      if (root) collect(root, exclude)
    }
  }
  return departments.value
    .filter((d) => !exclude.has(d.id))
    .map((d) => ({ label: d.name, value: d.id }))
})

function collect(node: { id: number; children: unknown[] }, acc: Set<number>) {
  acc.add(node.id)
  for (const c of node.children as Array<{ id: number; children: unknown[] }>) collect(c, acc)
}

async function onSaveDept() {
  if (!deptForm.name.trim()) return
  savingDept.value = true
  try {
    if (deptForm.id) {
      await orgApi.updateDepartment(deptForm.id, { name: deptForm.name, parentId: deptForm.parentId })
    } else {
      if (!currentOrgId.value) return
      await orgApi.createDepartment(currentOrgId.value, { name: deptForm.name, parentId: deptForm.parentId ?? undefined })
    }
    snackbar.success(t('saved'))
    showDeptDialog.value = false
    await loadDepartments()
  } catch {
    snackbar.error(t('saveFailed'))
  } finally {
    savingDept.value = false
  }
}

function confirmDeleteDept(id: number) {
  const d = departments.value.find((x) => x.id === id)
  confirm.show = true
  confirm.title = t('deleteDeptTitle')
  confirm.content = t('deleteDeptContent', { name: d?.name ?? '' })
  confirm.action = async () => {
    await orgApi.removeDepartment(id)
    snackbar.success(t('deleted'))
    if (selectedDeptId.value === id) selectedDeptId.value = null
    await loadDepartments()
    loadMembers(1)
  }
}

// ── 成员 ──
const members = ref<OrgMember[]>([])
const memberTotal = ref(0)
const memberPage = ref(1)
const memberLimit = ref(20)
const memberKeyword = ref('')
const memberLoading = ref(false)
const savingMember = ref(false)
const showMemberDialog = ref(false)
const memberForm = reactive({ userId: null as number | null, role: 'member' as OrgMemberRole, deptId: null as number | null })
const users = ref<AdminUser[]>([])

const memberHeaders = computed(() => [
  { key: 'nickname', title: t('nicknameCol') },
  { key: 'username', title: t('usernameCol') },
  { key: 'email', title: t('emailCol') },
  { key: 'role', title: t('roleCol') },
  { key: 'deptName', title: t('deptCol') },
  { key: 'actions', title: t('actionCol') },
])

const roleOptions = [
  { value: 'owner', label: t('roleOwner') },
  { value: 'admin', label: t('roleAdmin') },
  { value: 'member', label: t('roleMember') },
] as const

const deptOptions = computed(() =>
  departments.value.map((d) => ({ label: d.name, value: d.id })),
)

const memberUserOptions = computed(() =>
  users.value
    .filter((u) => !members.value.some((m) => m.userId === u.id))
    .map((u) => ({ label: `${u.nickname || u.username} (${u.username})`, value: u.id })),
)

async function loadMembers(page = memberPage.value) {
  if (!currentOrgId.value) return
  memberLoading.value = true
  try {
    const res = await orgApi.listMembers(
      currentOrgId.value,
      page,
      memberLimit.value,
      memberKeyword.value || undefined,
      selectedDeptId.value ?? undefined,
    )
    members.value = res.items
    memberTotal.value = res.total
    memberPage.value = page
  } catch {
    snackbar.error(t('loadFailed'))
  } finally {
    memberLoading.value = false
  }
}

async function openAddMember() {
  const res = await usersApi.list(1, 100)
  users.value = res.items
  memberForm.userId = null
  memberForm.role = 'member'
  memberForm.deptId = null
  showMemberDialog.value = true
}

async function onSaveMember() {
  if (!currentOrgId.value || !memberForm.userId) return
  savingMember.value = true
  try {
    await orgApi.addMember(currentOrgId.value, {
      userId: memberForm.userId,
      role: memberForm.role,
      ...(memberForm.deptId ? { deptId: memberForm.deptId } : {}),
    })
    snackbar.success(t('memberAdded'))
    showMemberDialog.value = false
    await loadMembers()
    await loadDepartments()
  } catch {
    snackbar.error(t('saveFailed'))
  } finally {
    savingMember.value = false
  }
}

async function updateMemberRole(item: OrgMember, role: OrgMemberRole) {
  try {
    await orgApi.updateMember(item.id, { role })
    item.role = role
    snackbar.success(t('saved'))
  } catch {
    snackbar.error(t('saveFailed'))
    loadMembers()
  }
}

function confirmDeleteMember(item: OrgMember) {
  confirm.show = true
  confirm.title = t('memberRemove')
  confirm.content = t('memberRemoveContent', { name: item.nickname || item.username || '' })
  confirm.action = async () => {
    await orgApi.removeMember(item.id)
    snackbar.success(t('deleted'))
    await loadMembers()
  }
}

// ── 邀请 ──
const invites = ref<OrgInvite[]>([])
const showInviteDialog = ref(false)
const savingInvite = ref(false)
const inviteForm = reactive({ role: 'member' as OrgMemberRole, deptId: null as number | null })
const inviteResult = ref('')

async function loadInvites() {
  if (!currentOrgId.value) return
  invites.value = await orgApi.listInvites(currentOrgId.value)
}

function openInvite() {
  inviteForm.role = 'member'
  inviteForm.deptId = null
  inviteResult.value = ''
  showInviteDialog.value = true
}

async function onSaveInvite() {
  if (!currentOrgId.value) return
  savingInvite.value = true
  try {
    const inv = await orgApi.createInvite(currentOrgId.value, {
      role: inviteForm.role,
      ...(inviteForm.deptId ? { deptId: inviteForm.deptId } : {}),
    })
    inviteResult.value = inv.code
    await loadInvites()
  } catch {
    snackbar.error(t('saveFailed'))
  } finally {
    savingInvite.value = false
  }
}

async function copyInvite(code: string) {
  try {
    await navigator.clipboard.writeText(code)
    snackbar.success(t('inviteCopied'))
  } catch {
    snackbar.error(t('saveFailed'))
  }
}

function revokeInvite(inv: OrgInvite) {
  confirm.show = true
  confirm.title = t('inviteRevoke')
  confirm.content = t('inviteRevokeContent', { code: inv.code })
  confirm.action = async () => {
    await orgApi.removeInvite(inv.id)
    snackbar.success(t('deleted'))
    await loadInvites()
  }
}

// ── 通用 ──
const showOrgDialog = ref(false)
const orgForm = reactive({ id: 0, name: '', description: '' })
const confirm = reactive({
  show: false,
  title: '',
  content: '',
  action: null as (() => Promise<void>) | null,
})

async function runConfirm() {
  confirm.show = false
  if (confirm.action) await confirm.action()
}

function cap(s: string): string {
  return s ? s.charAt(0).toUpperCase() + s.slice(1) : s
}

function required(v: unknown): true | string {
  return !!v || t('requiredField')
}

onMounted(async () => {
  await loadOrgs()
  if (currentOrgId.value) onSelectOrg(currentOrgId.value)
})
</script>

<style scoped>
.role-select {
  max-width: 130px;
}
</style>
