// Web-Admin-React/src/views/sessions/SessionsView.tsx
// SPDX-License-Identifier: Apache-2.0

import { useEffect, useState } from 'react'
import { Box, Button, IconButton } from '@mui/material'
import RefreshIcon from '@mui/icons-material/Refresh'
import LogoutIcon from '@mui/icons-material/Logout'
import { useTranslation } from 'react-i18next'
import { PageHeader } from '@/components/PageHeader'
import { AppTable, type AppColumn } from '@/components/AppTable'
import { ConfirmDialog } from '@/components/ConfirmDialog'
import { useSnackbarStore } from '@/stores/snackbar'
import { adminApi } from '@/api/admin'
import { formatTime } from '@/utils/format'
import type { AdminSession } from '@/types/admin'

export default function SessionsView() {
  const { t } = useTranslation()
  const snackbar = useSnackbarStore()

  const [sessions, setSessions] = useState<AdminSession[]>([])
  const [loading, setLoading] = useState(false)
  const [showRevoke, setShowRevoke] = useState(false)
  const [pending, setPending] = useState<AdminSession | null>(null)

  async function load() {
    setLoading(true)
    try {
      setSessions(await adminApi.sessions())
    } catch (err) {
      snackbar.error(err instanceof Error ? err.message : t('loadFailed'))
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    void load()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  function confirmRevoke(s: AdminSession) {
    setPending(s)
    setShowRevoke(true)
  }

  async function onRevoke() {
    if (!pending) return
    try {
      await adminApi.revokeSession(pending.id)
      snackbar.success(t('revoked'))
      void load()
    } catch (err) {
      snackbar.error(err instanceof Error ? err.message : t('revokeFailed'))
    } finally {
      setShowRevoke(false)
    }
  }

  const headers: AppColumn<AdminSession>[] = [
    { key: 'id', title: t('idCol'), width: 70 },
    { key: 'username', title: t('userCol'), render: (s) => s.username || '-' },
    { key: 'deviceName', title: t('deviceCol'), render: (s) => s.deviceName || t('unknownDevice') },
    { key: 'ip', title: t('ipCol'), render: (s) => s.ip || '-' },
    { key: 'lastActiveAt', title: t('lastActive'), render: (s) => formatTime(s.lastActiveAt) },
    {
      key: 'actions',
      title: t('actionCol'),
      render: (s) => (
        <IconButton size="small" color="error" onClick={() => confirmRevoke(s)}>
          <LogoutIcon fontSize="small" />
        </IconButton>
      ),
    },
  ]

  return (
    <Box>
      <PageHeader title={t('sessionTitle')}>
        <Button variant="outlined" startIcon={<RefreshIcon />} onClick={() => void load()}>
          {t('refresh')}
        </Button>
      </PageHeader>
      <AppTable headers={headers} items={sessions} loading={loading} emptyText={t('noSessions')} />
      <ConfirmDialog
        open={showRevoke}
        title={t('revokeConfirmTitle')}
        content={t('revokeConfirmContent', { name: pending?.username || pending?.userId || '', id: pending?.id || '' })}
        onClose={() => setShowRevoke(false)}
        onConfirm={() => void onRevoke()}
      />
    </Box>
  )
}

// Web-Admin-Vue/src/views/sessions/SessionsView.vue
<!-- SPDX-License-Identifier: Apache-2.0 -->
<template>
  <div>
    <PageHeader :title="t('sessionTitle')">
      <el-button @click="load">
        <template #icon><AppIcon icon="mdi-refresh" /></template>
        {{ t('refresh') }}
      </el-button>
    </PageHeader>

    <AppTable :headers="headers" :items="sessions" :loading="loading" :total="sessions.length" :items-per-page="sessions.length || 1">
      <template #item.deviceName="{ item }">{{ item.deviceName || t('unknownDevice') }}</template>
      <template #item.lastActiveAt="{ item }">{{ formatTime(item.lastActiveAt) }}</template>
      <template #item.actions="{ item }">
        <el-button text size="small" type="danger" @click="confirmRevoke(item)">
          <AppIcon icon="mdi-logout" />
        </el-button>
      </template>
    </AppTable>

    <ConfirmDialog
      v-model="showRevoke"
      :title="t('revokeConfirmTitle')"
      :content="t('revokeConfirmContent', { name: pending?.username || pending?.userId || '', id: pending?.id || '' })"
      @confirm="onRevoke"
    />
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import PageHeader from '@/components/PageHeader.vue'
import AppTable from '@/components/AppTable.vue'
import ConfirmDialog from '@/components/ConfirmDialog.vue'
import { useSnackbarStore } from '@/stores/snackbar'
import { adminApi } from '@/api/admin'
import { formatTime } from '@/utils/format'
import type { AdminSession } from '@/types/admin'

const { t } = useI18n()
const snackbar = useSnackbarStore()

const sessions = ref<AdminSession[]>([])
const loading = ref(false)

const headers = computed(() => [
  { key: 'id', title: t('idCol') },
  { key: 'username', title: t('userCol') },
  { key: 'deviceName', title: t('deviceCol') },
  { key: 'ip', title: t('ipCol') },
  { key: 'lastActiveAt', title: t('lastActive') },
  { key: 'actions', title: t('actionCol') },
])

async function load() {
  loading.value = true
  try {
    sessions.value = await adminApi.sessions()
  } catch (err) {
    snackbar.error(err instanceof Error ? err.message : t('loadFailed'))
  } finally {
    loading.value = false
  }
}

// 强下线
const showRevoke = ref(false)
const pending = ref<AdminSession | null>(null)
function confirmRevoke(s: AdminSession) {
  pending.value = s
  showRevoke.value = true
}
async function onRevoke() {
  if (!pending.value) return
  try {
    await adminApi.revokeSession(pending.value.id)
    snackbar.success(t('revoked'))
    load()
  } catch (err) {
    snackbar.error(err instanceof Error ? err.message : t('revokeFailed'))
  } finally {
    showRevoke.value = false
  }
}

onMounted(load)
</script>
