// Web-Admin-React/src/views/notifications/NotificationsView.tsx
// SPDX-License-Identifier: Apache-2.0

import { useEffect, useState } from 'react'
import { Box, Button, Card, CardContent, Checkbox, FormControlLabel, MenuItem, Select, TextField, Typography } from '@mui/material'
import SendIcon from '@mui/icons-material/Send'
import { useTranslation } from 'react-i18next'
import { PageHeader } from '@/components/PageHeader'
import { useSnackbarStore } from '@/stores/snackbar'
import { adminApi } from '@/api/admin'
import { usersApi } from '@/api/users'

export default function NotificationsView() {
  const { t } = useTranslation()
  const snackbar = useSnackbarStore()

  const [form, setForm] = useState({ title: '', body: '', type: '' })
  const [sendToAll, setSendToAll] = useState(true)
  const [selectedIds, setSelectedIds] = useState<number[]>([])
  const [userOptions, setUserOptions] = useState<{ label: string; value: number }[]>([])
  const [sending, setSending] = useState(false)

  async function loadUsers() {
    try {
      const res = await usersApi.list(1, 100)
      setUserOptions(res.items.map((u) => ({ label: `${u.username} (${u.nickname})`, value: u.id })))
    } catch {
      // 选人列表加载失败静默，用户仍可发给全体
    }
  }

  useEffect(() => {
    void loadUsers()
  }, [])

  async function onSend() {
    if (!form.title.trim()) {
      snackbar.error(t('titleRequired'))
      return
    }
    if (!sendToAll && selectedIds.length === 0) {
      snackbar.error(t('selectRequired'))
      return
    }
    setSending(true)
    try {
      const res = await adminApi.broadcast({
        title: form.title.trim(),
        body: form.body || undefined,
        type: form.type || undefined,
        ...(sendToAll ? {} : { userIds: selectedIds }),
      })
      snackbar.success(t('broadcastSent', { n: res.sent }))
      setForm({ title: '', body: '', type: '' })
      setSelectedIds([])
    } catch (err) {
      snackbar.error(err instanceof Error ? err.message : t('sendFailed'))
    } finally {
      setSending(false)
    }
  }

  return (
    <Box>
      <PageHeader title={t('navNotifications')} />
      <Card sx={{ maxWidth: 720, mx: 'auto' }}>
        <CardContent>
          <Box component="form" onSubmit={(e) => { e.preventDefault(); void onSend() }}>
            <TextField label={t('broadcastTitle')} required fullWidth margin="dense" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} />
            <TextField label={t('contentLabel')} multiline rows={3} fullWidth margin="dense" value={form.body} onChange={(e) => setForm({ ...form, body: e.target.value })} />
            <TextField label={t('typeLabel')} placeholder={t('typePlaceholder')} fullWidth margin="dense" value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })} />
            <FormControlLabel
              control={<Checkbox checked={sendToAll} onChange={(e) => setSendToAll(e.target.checked)} />}
              label={t('sendToAll')}
              sx={{ mb: 1 }}
            />

            {!sendToAll ? (
              <Select
                multiple
                fullWidth
                size="small"
                value={selectedIds}
                onChange={(e) => setSelectedIds(e.target.value as number[])}
                label={t('selectRecipients', { n: selectedIds.length })}
                renderValue={(sel) => `${t('selectRecipients', { n: sel.length })}`}
              >
                {userOptions.map((o) => (
                  <MenuItem key={o.value} value={o.value}>
                    {o.label}
                  </MenuItem>
                ))}
              </Select>
            ) : null}

            <Button type="submit" color="primary" variant="contained" fullWidth size="large" sx={{ mt: 2 }} loading={sending} startIcon={<SendIcon />}>
              {t('send')}
            </Button>
          </Box>
        </CardContent>
      </Card>
      {!sendToAll ? null : (
        <Typography variant="caption" color="text.secondary" display="block" textAlign="center" mt={1}>
          {t('selectRecipients', { n: selectedIds.length })}
        </Typography>
      )}
    </Box>
  )
}

// Web-Admin-Vue/src/views/notifications/NotificationsView.vue
<!-- SPDX-License-Identifier: Apache-2.0 -->
<template>
  <div>
    <PageHeader :title="t('navNotifications')" />

    <el-card shadow="never" class="mx-auto" style="max-width: 720px">
      <div class="pa-4">
        <el-form @submit.prevent="onSend" label-position="top">
          <el-form-item :label="t('broadcastTitle')">
            <el-input v-model="form.title" required />
          </el-form-item>
          <el-form-item :label="t('contentLabel')">
            <el-input v-model="form.body" type="textarea" :rows="3" />
          </el-form-item>
          <el-form-item :label="t('typeLabel')">
            <el-input v-model="form.type" :placeholder="t('typePlaceholder')" />
          </el-form-item>
          <el-form-item>
            <el-switch v-model="sendToAll" :active-text="t('sendToAll')" class="mb-2" />
          </el-form-item>

          <el-form-item v-if="!sendToAll" :label="t('selectRecipients', { n: selectedIds.length })">
            <el-select v-model="selectedIds" multiple clearable style="width: 100%">
              <el-option v-for="opt in userOptions" :key="opt.value" :label="opt.label" :value="opt.value" />
            </el-select>
          </el-form-item>

          <el-button
            type="primary"
            native-type="submit"
            size="large"
            block
            :loading="sending"
            class="mt-2"
          >
            <template #icon><AppIcon icon="mdi-send" /></template>
            {{ t('send') }}
          </el-button>
        </el-form>
      </div>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import PageHeader from '@/components/PageHeader.vue'
import { useSnackbarStore } from '@/stores/snackbar'
import { adminApi } from '@/api/admin'
import { usersApi } from '@/api/users'

const { t } = useI18n()
const snackbar = useSnackbarStore()

const form = ref({ title: '', body: '', type: '' })
const sendToAll = ref(true)
const selectedIds = ref<number[]>([])
const userOptions = ref<{ label: string; value: number }[]>([])
const sending = ref(false)

async function loadUsers() {
  try {
    const res = await usersApi.list(1, 100)
    userOptions.value = res.items.map((u) => ({ label: `${u.username} (${u.nickname})`, value: u.id }))
  } catch {
    // 选人列表加载失败静默，用户仍可发给全体
  }
}

async function onSend() {
  if (!form.value.title.trim()) {
    snackbar.error(t('titleRequired'))
    return
  }
  if (!sendToAll.value && selectedIds.value.length === 0) {
    snackbar.error(t('selectRequired'))
    return
  }
  sending.value = true
  try {
    const res = await adminApi.broadcast({
      title: form.value.title.trim(),
      body: form.value.body || undefined,
      type: form.value.type || undefined,
      ...(sendToAll.value ? {} : { userIds: selectedIds.value }),
    })
    snackbar.success(t('broadcastSent', { n: res.sent }))
    form.value = { title: '', body: '', type: '' }
    selectedIds.value = []
  } catch (err) {
    snackbar.error(err instanceof Error ? err.message : t('sendFailed'))
  } finally {
    sending.value = false
  }
}

onMounted(loadUsers)
</script>
